import { AgrParalogs } from '../../../../../types/agrParalogs';

// Source: https://www.alliancegenome.org/api/gene/HGNC:620/paralogs?filter.stringency=all&limit=10000
// Retrieved: 2025-07-07
const mock: AgrParalogs = {
  results: [
    {
      category: 'gene_to_gene_paralogy',
      searchable: false,
      geneToGeneParalogy: {
        internal: false,
        obsolete: false,
        subjectGene: {
          type: 'Gene',
          dateCreated: '2004-02-06T17:50:09Z',
          internal: false,
          obsolete: false,
          primaryExternalId: 'HGNC:620',
          taxon: {
            internal: false,
            obsolete: false,
            curie: 'NCBITaxon:9606',
            name: 'Homo sapiens',
            childCount: 0,
            descendantCount: 0,
            notInternalOrObsolete: true,
          },
          geneSymbol: {
            internal: false,
            obsolete: false,
            formatText: 'APP',
            displayText: 'APP',
            notInternalOrObsolete: true,
          },
          geneFullName: {
            internal: false,
            obsolete: false,
            formatText: 'amyloid beta precursor protein',
            displayText: 'amyloid beta precursor protein',
            notInternalOrObsolete: true,
          },
          notInternalOrObsolete: true,
        },
        objectGene: {
          type: 'Gene',
          dateCreated: '2004-01-12T22:23:50Z',
          internal: false,
          obsolete: false,
          primaryExternalId: 'HGNC:598',
          taxon: {
            internal: false,
            obsolete: false,
            curie: 'NCBITaxon:9606',
            name: 'Homo sapiens',
            childCount: 0,
            descendantCount: 0,
            notInternalOrObsolete: true,
          },
          geneSymbol: {
            internal: false,
            obsolete: false,
            formatText: 'APLP2',
            displayText: 'APLP2',
            notInternalOrObsolete: true,
          },
          geneFullName: {
            internal: false,
            obsolete: false,
            formatText: 'amyloid beta precursor like protein 2',
            displayText: 'amyloid beta precursor like protein 2',
            notInternalOrObsolete: true,
          },
          notInternalOrObsolete: true,
        },
        predictionMethodsMatched: [
          {
            internal: false,
            obsolete: false,
            name: 'SonicParanoid',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'Ensembl Compara',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'OrthoFinder',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'OrthoInspector',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'InParanoid',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'PhylomeDB',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'PANTHER',
            notInternalOrObsolete: true,
          },
        ],
        predictionMethodsNotMatched: [
          {
            internal: false,
            obsolete: false,
            name: 'OMA',
            notInternalOrObsolete: true,
          },
        ],
        predictionMethodsNotCalled: [
          {
            internal: false,
            obsolete: false,
            name: 'HGNC',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'SGD',
            notInternalOrObsolete: true,
          },
        ],
        rank: 1,
        length: 810,
        similarity: 66,
        identity: 50,
        notInternalOrObsolete: true,
      },
    },
    {
      category: 'gene_to_gene_paralogy',
      searchable: false,
      geneToGeneParalogy: {
        internal: false,
        obsolete: false,
        subjectGene: {
          type: 'Gene',
          dateCreated: '2004-02-06T17:50:09Z',
          internal: false,
          obsolete: false,
          primaryExternalId: 'HGNC:620',
          taxon: {
            internal: false,
            obsolete: false,
            curie: 'NCBITaxon:9606',
            name: 'Homo sapiens',
            childCount: 0,
            descendantCount: 0,
            notInternalOrObsolete: true,
          },
          geneSymbol: {
            internal: false,
            obsolete: false,
            formatText: 'APP',
            displayText: 'APP',
            notInternalOrObsolete: true,
          },
          geneFullName: {
            internal: false,
            obsolete: false,
            formatText: 'amyloid beta precursor protein',
            displayText: 'amyloid beta precursor protein',
            notInternalOrObsolete: true,
          },
          notInternalOrObsolete: true,
        },
        objectGene: {
          type: 'Gene',
          dateCreated: '2004-02-06T17:50:27Z',
          internal: false,
          obsolete: false,
          primaryExternalId: 'HGNC:597',
          taxon: {
            internal: false,
            obsolete: false,
            curie: 'NCBITaxon:9606',
            name: 'Homo sapiens',
            childCount: 0,
            descendantCount: 0,
            notInternalOrObsolete: true,
          },
          geneSymbol: {
            internal: false,
            obsolete: false,
            formatText: 'APLP1',
            displayText: 'APLP1',
            notInternalOrObsolete: true,
          },
          geneFullName: {
            internal: false,
            obsolete: false,
            formatText: 'amyloid beta precursor like protein 1',
            displayText: 'amyloid beta precursor like protein 1',
            notInternalOrObsolete: true,
          },
          notInternalOrObsolete: true,
        },
        predictionMethodsMatched: [
          {
            internal: false,
            obsolete: false,
            name: 'SonicParanoid',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'Ensembl Compara',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'OrthoFinder',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'OrthoInspector',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'PhylomeDB',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'PANTHER',
            notInternalOrObsolete: true,
          },
        ],
        predictionMethodsNotMatched: [
          {
            internal: false,
            obsolete: false,
            name: 'InParanoid',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'OMA',
            notInternalOrObsolete: true,
          },
        ],
        predictionMethodsNotCalled: [
          {
            internal: false,
            obsolete: false,
            name: 'HGNC',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'SGD',
            notInternalOrObsolete: true,
          },
        ],
        rank: 2,
        length: 776,
        similarity: 51,
        identity: 36,
        notInternalOrObsolete: true,
      },
    },
  ],
  total: 2,
  returnedRecords: 2,
  requestDuration: '0s',
  requestDate: '2025/07/07 19:22:29',
};

export default mock;
