import { AgrOrthologs } from '../../../../../types/agrOrthologs';

// Source: https://www.alliancegenome.org/api/gene/HGNC:620/orthologs?filter.stringency=all&limit=10000
// Retrieved: 2025-07-07
const mock: AgrOrthologs = {
  results: [
    {
      category: 'gene_to_gene_orthology',
      searchable: false,
      stringencyFilter: 'all',
      geneAnnotations: [
        {
          hasDiseaseAnnotations: true,
          hasExpressionAnnotations: false,
          geneIdentifier: 'HGNC:620',
        },
        {
          hasDiseaseAnnotations: false,
          hasExpressionAnnotations: false,
          geneIdentifier: 'FB:FBgn0031560',
        },
      ],
      geneAnnotationsMap: {
        'FB:FBgn0031560': {
          hasDiseaseAnnotations: false,
          hasExpressionAnnotations: false,
          geneIdentifier: 'FB:FBgn0031560',
        },
        'HGNC:620': {
          hasDiseaseAnnotations: true,
          hasExpressionAnnotations: false,
          geneIdentifier: 'HGNC:620',
        },
      },
      geneToGeneOrthologyGenerated: {
        internal: false,
        obsolete: false,
        subjectGene: {
          type: 'Gene',
          internal: false,
          obsolete: false,
          primaryExternalId: 'HGNC:620',
          taxon: {
            internal: false,
            obsolete: false,
            curie: 'NCBITaxon:9606',
            name: 'Homo sapiens',
            childCount: 0,
            descendantCount: 0,
            notInternalOrObsolete: true,
          },
          geneSymbol: {
            internal: false,
            obsolete: false,
            displayText: 'APP',
            notInternalOrObsolete: true,
          },
          notInternalOrObsolete: true,
        },
        objectGene: {
          type: 'Gene',
          internal: false,
          obsolete: false,
          primaryExternalId: 'FB:FBgn0031560',
          taxon: {
            internal: false,
            obsolete: false,
            curie: 'NCBITaxon:7227',
            name: 'Drosophila melanogaster',
            childCount: 0,
            descendantCount: 0,
            notInternalOrObsolete: true,
          },
          geneSymbol: {
            internal: false,
            obsolete: false,
            displayText: 'CG16713',
            notInternalOrObsolete: true,
          },
          notInternalOrObsolete: true,
        },
        isBestScore: {
          internal: false,
          obsolete: false,
          name: 'No',
          notInternalOrObsolete: true,
        },
        isBestScoreReverse: {
          internal: false,
          obsolete: false,
          name: 'No',
          notInternalOrObsolete: true,
        },
        confidence: {
          internal: false,
          obsolete: false,
          name: 'low',
          notInternalOrObsolete: true,
        },
        strictFilter: false,
        moderateFilter: false,
        predictionMethodsMatched: [
          {
            internal: false,
            obsolete: false,
            name: 'PhylomeDB',
            notInternalOrObsolete: true,
          },
        ],
        predictionMethodsNotMatched: [
          {
            internal: false,
            obsolete: false,
            name: 'SonicParanoid',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'OrthoFinder',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'Hieranoid',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'InParanoid',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'PANTHER',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'OMA',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'Ensembl Compara',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'OrthoInspector',
            notInternalOrObsolete: true,
          },
        ],
        predictionMethodsNotCalled: [
          {
            internal: false,
            obsolete: false,
            name: 'Xenbase',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'ZFIN',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'HGNC',
            notInternalOrObsolete: true,
          },
        ],
        notInternalOrObsolete: true,
      },
    },
    {
      category: 'gene_to_gene_orthology',
      searchable: false,
      stringencyFilter: 'stringent',
      geneAnnotations: [
        {
          hasDiseaseAnnotations: true,
          hasExpressionAnnotations: false,
          geneIdentifier: 'HGNC:620',
        },
        {
          hasDiseaseAnnotations: false,
          hasExpressionAnnotations: true,
          geneIdentifier: 'ZFIN:ZDB-GENE-000616-13',
        },
      ],
      geneAnnotationsMap: {
        'ZFIN:ZDB-GENE-000616-13': {
          hasDiseaseAnnotations: false,
          hasExpressionAnnotations: true,
          geneIdentifier: 'ZFIN:ZDB-GENE-000616-13',
        },
        'HGNC:620': {
          hasDiseaseAnnotations: true,
          hasExpressionAnnotations: false,
          geneIdentifier: 'HGNC:620',
        },
      },
      geneToGeneOrthologyGenerated: {
        internal: false,
        obsolete: false,
        subjectGene: {
          type: 'Gene',
          internal: false,
          obsolete: false,
          primaryExternalId: 'HGNC:620',
          taxon: {
            internal: false,
            obsolete: false,
            curie: 'NCBITaxon:9606',
            name: 'Homo sapiens',
            childCount: 0,
            descendantCount: 0,
            notInternalOrObsolete: true,
          },
          geneSymbol: {
            internal: false,
            obsolete: false,
            displayText: 'APP',
            notInternalOrObsolete: true,
          },
          notInternalOrObsolete: true,
        },
        objectGene: {
          type: 'Gene',
          internal: false,
          obsolete: false,
          primaryExternalId: 'ZFIN:ZDB-GENE-000616-13',
          taxon: {
            internal: false,
            obsolete: false,
            curie: 'NCBITaxon:7955',
            name: 'Danio rerio',
            childCount: 0,
            descendantCount: 0,
            notInternalOrObsolete: true,
          },
          geneSymbol: {
            internal: false,
            obsolete: false,
            displayText: 'appa',
            notInternalOrObsolete: true,
          },
          notInternalOrObsolete: true,
        },
        isBestScore: {
          internal: false,
          obsolete: false,
          name: 'Yes',
          notInternalOrObsolete: true,
        },
        isBestScoreReverse: {
          internal: false,
          obsolete: false,
          name: 'Yes',
          notInternalOrObsolete: true,
        },
        confidence: {
          internal: false,
          obsolete: false,
          name: 'high',
          notInternalOrObsolete: true,
        },
        strictFilter: true,
        moderateFilter: true,
        predictionMethodsMatched: [
          {
            internal: false,
            obsolete: false,
            name: 'Hieranoid',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'InParanoid',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'OMA',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'OrthoFinder',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'OrthoInspector',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'PANTHER',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'PhylomeDB',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'SonicParanoid',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'ZFIN',
            notInternalOrObsolete: true,
          },
        ],
        predictionMethodsNotMatched: [
          {
            internal: false,
            obsolete: false,
            name: 'Ensembl Compara',
            notInternalOrObsolete: true,
          },
        ],
        predictionMethodsNotCalled: [
          {
            internal: false,
            obsolete: false,
            name: 'Xenbase',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'HGNC',
            notInternalOrObsolete: true,
          },
        ],
        notInternalOrObsolete: true,
      },
    },
    {
      category: 'gene_to_gene_orthology',
      searchable: false,
      stringencyFilter: 'stringent',
      geneAnnotations: [
        {
          hasDiseaseAnnotations: true,
          hasExpressionAnnotations: false,
          geneIdentifier: 'HGNC:620',
        },
        {
          hasDiseaseAnnotations: true,
          hasExpressionAnnotations: true,
          geneIdentifier: 'RGD:2139',
        },
      ],
      geneAnnotationsMap: {
        'HGNC:620': {
          hasDiseaseAnnotations: true,
          hasExpressionAnnotations: false,
          geneIdentifier: 'HGNC:620',
        },
        'RGD:2139': {
          hasDiseaseAnnotations: true,
          hasExpressionAnnotations: true,
          geneIdentifier: 'RGD:2139',
        },
      },
      geneToGeneOrthologyGenerated: {
        internal: false,
        obsolete: false,
        subjectGene: {
          type: 'Gene',
          internal: false,
          obsolete: false,
          primaryExternalId: 'HGNC:620',
          taxon: {
            internal: false,
            obsolete: false,
            curie: 'NCBITaxon:9606',
            name: 'Homo sapiens',
            childCount: 0,
            descendantCount: 0,
            notInternalOrObsolete: true,
          },
          geneSymbol: {
            internal: false,
            obsolete: false,
            displayText: 'APP',
            notInternalOrObsolete: true,
          },
          notInternalOrObsolete: true,
        },
        objectGene: {
          type: 'Gene',
          internal: false,
          obsolete: false,
          primaryExternalId: 'RGD:2139',
          taxon: {
            internal: false,
            obsolete: false,
            curie: 'NCBITaxon:10116',
            name: 'Rattus norvegicus',
            childCount: 0,
            descendantCount: 0,
            notInternalOrObsolete: true,
          },
          geneSymbol: {
            internal: false,
            obsolete: false,
            displayText: 'App',
            notInternalOrObsolete: true,
          },
          notInternalOrObsolete: true,
        },
        isBestScore: {
          internal: false,
          obsolete: false,
          name: 'Yes',
          notInternalOrObsolete: true,
        },
        isBestScoreReverse: {
          internal: false,
          obsolete: false,
          name: 'Yes',
          notInternalOrObsolete: true,
        },
        confidence: {
          internal: false,
          obsolete: false,
          name: 'high',
          notInternalOrObsolete: true,
        },
        strictFilter: true,
        moderateFilter: true,
        predictionMethodsMatched: [
          {
            internal: false,
            obsolete: false,
            name: 'Hieranoid',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'InParanoid',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'OMA',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'OrthoFinder',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'OrthoInspector',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'PANTHER',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'PhylomeDB',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'HGNC',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'SonicParanoid',
            notInternalOrObsolete: true,
          },
        ],
        predictionMethodsNotMatched: [
          {
            internal: false,
            obsolete: false,
            name: 'Ensembl Compara',
            notInternalOrObsolete: true,
          },
        ],
        predictionMethodsNotCalled: [
          {
            internal: false,
            obsolete: false,
            name: 'Xenbase',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'ZFIN',
            notInternalOrObsolete: true,
          },
        ],
        notInternalOrObsolete: true,
      },
    },
    {
      category: 'gene_to_gene_orthology',
      searchable: false,
      stringencyFilter: 'stringent',
      geneAnnotations: [
        {
          hasDiseaseAnnotations: true,
          hasExpressionAnnotations: false,
          geneIdentifier: 'HGNC:620',
        },
        {
          hasDiseaseAnnotations: false,
          hasExpressionAnnotations: true,
          geneIdentifier: 'FB:FBgn0000108',
        },
      ],
      geneAnnotationsMap: {
        'FB:FBgn0000108': {
          hasDiseaseAnnotations: false,
          hasExpressionAnnotations: true,
          geneIdentifier: 'FB:FBgn0000108',
        },
        'HGNC:620': {
          hasDiseaseAnnotations: true,
          hasExpressionAnnotations: false,
          geneIdentifier: 'HGNC:620',
        },
      },
      geneToGeneOrthologyGenerated: {
        internal: false,
        obsolete: false,
        subjectGene: {
          type: 'Gene',
          internal: false,
          obsolete: false,
          primaryExternalId: 'HGNC:620',
          taxon: {
            internal: false,
            obsolete: false,
            curie: 'NCBITaxon:9606',
            name: 'Homo sapiens',
            childCount: 0,
            descendantCount: 0,
            notInternalOrObsolete: true,
          },
          geneSymbol: {
            internal: false,
            obsolete: false,
            displayText: 'APP',
            notInternalOrObsolete: true,
          },
          notInternalOrObsolete: true,
        },
        objectGene: {
          type: 'Gene',
          internal: false,
          obsolete: false,
          primaryExternalId: 'FB:FBgn0000108',
          taxon: {
            internal: false,
            obsolete: false,
            curie: 'NCBITaxon:7227',
            name: 'Drosophila melanogaster',
            childCount: 0,
            descendantCount: 0,
            notInternalOrObsolete: true,
          },
          geneSymbol: {
            internal: false,
            obsolete: false,
            displayText: 'Appl',
            notInternalOrObsolete: true,
          },
          notInternalOrObsolete: true,
        },
        isBestScore: {
          internal: false,
          obsolete: false,
          name: 'Yes',
          notInternalOrObsolete: true,
        },
        isBestScoreReverse: {
          internal: false,
          obsolete: false,
          name: 'No',
          notInternalOrObsolete: true,
        },
        confidence: {
          internal: false,
          obsolete: false,
          name: 'moderate',
          notInternalOrObsolete: true,
        },
        strictFilter: true,
        moderateFilter: false,
        predictionMethodsMatched: [
          {
            internal: false,
            obsolete: false,
            name: 'Hieranoid',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'InParanoid',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'OMA',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'OrthoFinder',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'OrthoInspector',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'PANTHER',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'SonicParanoid',
            notInternalOrObsolete: true,
          },
        ],
        predictionMethodsNotMatched: [
          {
            internal: false,
            obsolete: false,
            name: 'PhylomeDB',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'Ensembl Compara',
            notInternalOrObsolete: true,
          },
        ],
        predictionMethodsNotCalled: [
          {
            internal: false,
            obsolete: false,
            name: 'Xenbase',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'ZFIN',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'HGNC',
            notInternalOrObsolete: true,
          },
        ],
        notInternalOrObsolete: true,
      },
    },
    {
      category: 'gene_to_gene_orthology',
      searchable: false,
      stringencyFilter: 'stringent',
      geneAnnotations: [
        {
          hasDiseaseAnnotations: true,
          hasExpressionAnnotations: false,
          geneIdentifier: 'HGNC:620',
        },
        {
          hasDiseaseAnnotations: false,
          hasExpressionAnnotations: false,
          geneIdentifier: 'Xenbase:XB-GENE-479154',
        },
      ],
      geneAnnotationsMap: {
        'Xenbase:XB-GENE-479154': {
          hasDiseaseAnnotations: false,
          hasExpressionAnnotations: false,
          geneIdentifier: 'Xenbase:XB-GENE-479154',
        },
        'HGNC:620': {
          hasDiseaseAnnotations: true,
          hasExpressionAnnotations: false,
          geneIdentifier: 'HGNC:620',
        },
      },
      geneToGeneOrthologyGenerated: {
        internal: false,
        obsolete: false,
        subjectGene: {
          type: 'Gene',
          internal: false,
          obsolete: false,
          primaryExternalId: 'HGNC:620',
          taxon: {
            internal: false,
            obsolete: false,
            curie: 'NCBITaxon:9606',
            name: 'Homo sapiens',
            childCount: 0,
            descendantCount: 0,
            notInternalOrObsolete: true,
          },
          geneSymbol: {
            internal: false,
            obsolete: false,
            displayText: 'APP',
            notInternalOrObsolete: true,
          },
          notInternalOrObsolete: true,
        },
        objectGene: {
          type: 'Gene',
          internal: false,
          obsolete: false,
          primaryExternalId: 'Xenbase:XB-GENE-479154',
          taxon: {
            internal: false,
            obsolete: false,
            curie: 'NCBITaxon:8364',
            name: 'Xenopus tropicalis',
            childCount: 0,
            descendantCount: 0,
            notInternalOrObsolete: true,
          },
          geneSymbol: {
            internal: false,
            obsolete: false,
            displayText: 'app',
            notInternalOrObsolete: true,
          },
          notInternalOrObsolete: true,
        },
        isBestScore: {
          internal: false,
          obsolete: false,
          name: 'Yes',
          notInternalOrObsolete: true,
        },
        isBestScoreReverse: {
          internal: false,
          obsolete: false,
          name: 'Yes',
          notInternalOrObsolete: true,
        },
        confidence: {
          internal: false,
          obsolete: false,
          name: 'high',
          notInternalOrObsolete: true,
        },
        strictFilter: true,
        moderateFilter: false,
        predictionMethodsMatched: [
          {
            internal: false,
            obsolete: false,
            name: 'Hieranoid',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'InParanoid',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'OMA',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'OrthoFinder',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'OrthoInspector',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'PANTHER',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'PhylomeDB',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'SonicParanoid',
            notInternalOrObsolete: true,
          },
        ],
        predictionMethodsNotMatched: [
          {
            internal: false,
            obsolete: false,
            name: 'Ensembl Compara',
            notInternalOrObsolete: true,
          },
        ],
        predictionMethodsNotCalled: [
          {
            internal: false,
            obsolete: false,
            name: 'Xenbase',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'ZFIN',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'HGNC',
            notInternalOrObsolete: true,
          },
        ],
        notInternalOrObsolete: true,
      },
    },
    {
      category: 'gene_to_gene_orthology',
      searchable: false,
      stringencyFilter: 'stringent',
      geneAnnotations: [
        {
          hasDiseaseAnnotations: true,
          hasExpressionAnnotations: false,
          geneIdentifier: 'HGNC:620',
        },
        {
          hasDiseaseAnnotations: false,
          hasExpressionAnnotations: false,
          geneIdentifier: 'Xenbase:XB-GENE-17345003',
        },
      ],
      geneAnnotationsMap: {
        'HGNC:620': {
          hasDiseaseAnnotations: true,
          hasExpressionAnnotations: false,
          geneIdentifier: 'HGNC:620',
        },
        'Xenbase:XB-GENE-17345003': {
          hasDiseaseAnnotations: false,
          hasExpressionAnnotations: false,
          geneIdentifier: 'Xenbase:XB-GENE-17345003',
        },
      },
      geneToGeneOrthologyGenerated: {
        internal: false,
        obsolete: false,
        subjectGene: {
          type: 'Gene',
          internal: false,
          obsolete: false,
          primaryExternalId: 'HGNC:620',
          taxon: {
            internal: false,
            obsolete: false,
            curie: 'NCBITaxon:9606',
            name: 'Homo sapiens',
            childCount: 0,
            descendantCount: 0,
            notInternalOrObsolete: true,
          },
          geneSymbol: {
            internal: false,
            obsolete: false,
            displayText: 'APP',
            notInternalOrObsolete: true,
          },
          notInternalOrObsolete: true,
        },
        objectGene: {
          type: 'Gene',
          internal: false,
          obsolete: false,
          primaryExternalId: 'Xenbase:XB-GENE-17345003',
          taxon: {
            internal: false,
            obsolete: false,
            curie: 'NCBITaxon:8355',
            name: 'Xenopus laevis',
            childCount: 0,
            descendantCount: 0,
            notInternalOrObsolete: true,
          },
          geneSymbol: {
            internal: false,
            obsolete: false,
            displayText: 'app.S',
            notInternalOrObsolete: true,
          },
          notInternalOrObsolete: true,
        },
        isBestScore: {
          internal: false,
          obsolete: false,
          name: 'Yes',
          notInternalOrObsolete: true,
        },
        isBestScoreReverse: {
          internal: false,
          obsolete: false,
          name: 'Yes',
          notInternalOrObsolete: true,
        },
        confidence: {
          internal: false,
          obsolete: false,
          name: 'high',
          notInternalOrObsolete: true,
        },
        strictFilter: true,
        moderateFilter: true,
        predictionMethodsMatched: [
          {
            internal: false,
            obsolete: false,
            name: 'Xenbase',
            notInternalOrObsolete: true,
          },
        ],
        notInternalOrObsolete: true,
      },
    },
    {
      category: 'gene_to_gene_orthology',
      searchable: false,
      stringencyFilter: 'all',
      geneAnnotations: [
        {
          hasDiseaseAnnotations: true,
          hasExpressionAnnotations: false,
          geneIdentifier: 'HGNC:620',
        },
        {
          hasDiseaseAnnotations: false,
          hasExpressionAnnotations: false,
          geneIdentifier: 'RGD:69257',
        },
      ],
      geneAnnotationsMap: {
        'RGD:69257': {
          hasDiseaseAnnotations: false,
          hasExpressionAnnotations: false,
          geneIdentifier: 'RGD:69257',
        },
        'HGNC:620': {
          hasDiseaseAnnotations: true,
          hasExpressionAnnotations: false,
          geneIdentifier: 'HGNC:620',
        },
      },
      geneToGeneOrthologyGenerated: {
        internal: false,
        obsolete: false,
        subjectGene: {
          type: 'Gene',
          internal: false,
          obsolete: false,
          primaryExternalId: 'HGNC:620',
          taxon: {
            internal: false,
            obsolete: false,
            curie: 'NCBITaxon:9606',
            name: 'Homo sapiens',
            childCount: 0,
            descendantCount: 0,
            notInternalOrObsolete: true,
          },
          geneSymbol: {
            internal: false,
            obsolete: false,
            displayText: 'APP',
            notInternalOrObsolete: true,
          },
          notInternalOrObsolete: true,
        },
        objectGene: {
          type: 'Gene',
          internal: false,
          obsolete: false,
          primaryExternalId: 'RGD:69257',
          taxon: {
            internal: false,
            obsolete: false,
            curie: 'NCBITaxon:10116',
            name: 'Rattus norvegicus',
            childCount: 0,
            descendantCount: 0,
            notInternalOrObsolete: true,
          },
          geneSymbol: {
            internal: false,
            obsolete: false,
            displayText: 'Aplp1',
            notInternalOrObsolete: true,
          },
          notInternalOrObsolete: true,
        },
        isBestScore: {
          internal: false,
          obsolete: false,
          name: 'No',
          notInternalOrObsolete: true,
        },
        isBestScoreReverse: {
          internal: false,
          obsolete: false,
          name: 'No',
          notInternalOrObsolete: true,
        },
        confidence: {
          internal: false,
          obsolete: false,
          name: 'low',
          notInternalOrObsolete: true,
        },
        strictFilter: false,
        moderateFilter: false,
        predictionMethodsMatched: [
          {
            internal: false,
            obsolete: false,
            name: 'Ensembl Compara',
            notInternalOrObsolete: true,
          },
        ],
        predictionMethodsNotMatched: [
          {
            internal: false,
            obsolete: false,
            name: 'SonicParanoid',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'OrthoFinder',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'Hieranoid',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'HGNC',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'InParanoid',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'PANTHER',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'OMA',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'OrthoInspector',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'PhylomeDB',
            notInternalOrObsolete: true,
          },
        ],
        predictionMethodsNotCalled: [
          {
            internal: false,
            obsolete: false,
            name: 'Xenbase',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'ZFIN',
            notInternalOrObsolete: true,
          },
        ],
        notInternalOrObsolete: true,
      },
    },
    {
      category: 'gene_to_gene_orthology',
      searchable: false,
      stringencyFilter: 'stringent',
      geneAnnotations: [
        {
          hasDiseaseAnnotations: true,
          hasExpressionAnnotations: false,
          geneIdentifier: 'HGNC:620',
        },
        {
          hasDiseaseAnnotations: true,
          hasExpressionAnnotations: true,
          geneIdentifier: 'WB:WBGene00000149',
        },
      ],
      geneAnnotationsMap: {
        'WB:WBGene00000149': {
          hasDiseaseAnnotations: true,
          hasExpressionAnnotations: true,
          geneIdentifier: 'WB:WBGene00000149',
        },
        'HGNC:620': {
          hasDiseaseAnnotations: true,
          hasExpressionAnnotations: false,
          geneIdentifier: 'HGNC:620',
        },
      },
      geneToGeneOrthologyGenerated: {
        internal: false,
        obsolete: false,
        subjectGene: {
          type: 'Gene',
          internal: false,
          obsolete: false,
          primaryExternalId: 'HGNC:620',
          taxon: {
            internal: false,
            obsolete: false,
            curie: 'NCBITaxon:9606',
            name: 'Homo sapiens',
            childCount: 0,
            descendantCount: 0,
            notInternalOrObsolete: true,
          },
          geneSymbol: {
            internal: false,
            obsolete: false,
            displayText: 'APP',
            notInternalOrObsolete: true,
          },
          notInternalOrObsolete: true,
        },
        objectGene: {
          type: 'Gene',
          internal: false,
          obsolete: false,
          primaryExternalId: 'WB:WBGene00000149',
          taxon: {
            internal: false,
            obsolete: false,
            curie: 'NCBITaxon:6239',
            name: 'Caenorhabditis elegans',
            childCount: 0,
            descendantCount: 0,
            notInternalOrObsolete: true,
          },
          geneSymbol: {
            internal: false,
            obsolete: false,
            displayText: 'apl-1',
            notInternalOrObsolete: true,
          },
          notInternalOrObsolete: true,
        },
        isBestScore: {
          internal: false,
          obsolete: false,
          name: 'Yes',
          notInternalOrObsolete: true,
        },
        isBestScoreReverse: {
          internal: false,
          obsolete: false,
          name: 'Yes',
          notInternalOrObsolete: true,
        },
        confidence: {
          internal: false,
          obsolete: false,
          name: 'high',
          notInternalOrObsolete: true,
        },
        strictFilter: true,
        moderateFilter: false,
        predictionMethodsMatched: [
          {
            internal: false,
            obsolete: false,
            name: 'Hieranoid',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'InParanoid',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'OMA',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'OrthoFinder',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'OrthoInspector',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'PANTHER',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'PhylomeDB',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'SonicParanoid',
            notInternalOrObsolete: true,
          },
        ],
        predictionMethodsNotMatched: [
          {
            internal: false,
            obsolete: false,
            name: 'Ensembl Compara',
            notInternalOrObsolete: true,
          },
        ],
        predictionMethodsNotCalled: [
          {
            internal: false,
            obsolete: false,
            name: 'Xenbase',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'ZFIN',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'HGNC',
            notInternalOrObsolete: true,
          },
        ],
        notInternalOrObsolete: true,
      },
    },
    {
      category: 'gene_to_gene_orthology',
      searchable: false,
      stringencyFilter: 'stringent',
      geneAnnotations: [
        {
          hasDiseaseAnnotations: true,
          hasExpressionAnnotations: false,
          geneIdentifier: 'HGNC:620',
        },
        {
          hasDiseaseAnnotations: false,
          hasExpressionAnnotations: true,
          geneIdentifier: 'Xenbase:XB-GENE-479158',
        },
      ],
      geneAnnotationsMap: {
        'HGNC:620': {
          hasDiseaseAnnotations: true,
          hasExpressionAnnotations: false,
          geneIdentifier: 'HGNC:620',
        },
        'Xenbase:XB-GENE-479158': {
          hasDiseaseAnnotations: false,
          hasExpressionAnnotations: true,
          geneIdentifier: 'Xenbase:XB-GENE-479158',
        },
      },
      geneToGeneOrthologyGenerated: {
        internal: false,
        obsolete: false,
        subjectGene: {
          type: 'Gene',
          internal: false,
          obsolete: false,
          primaryExternalId: 'HGNC:620',
          taxon: {
            internal: false,
            obsolete: false,
            curie: 'NCBITaxon:9606',
            name: 'Homo sapiens',
            childCount: 0,
            descendantCount: 0,
            notInternalOrObsolete: true,
          },
          geneSymbol: {
            internal: false,
            obsolete: false,
            displayText: 'APP',
            notInternalOrObsolete: true,
          },
          notInternalOrObsolete: true,
        },
        objectGene: {
          type: 'Gene',
          internal: false,
          obsolete: false,
          primaryExternalId: 'Xenbase:XB-GENE-479158',
          taxon: {
            internal: false,
            obsolete: false,
            curie: 'NCBITaxon:8355',
            name: 'Xenopus laevis',
            childCount: 0,
            descendantCount: 0,
            notInternalOrObsolete: true,
          },
          geneSymbol: {
            internal: false,
            obsolete: false,
            displayText: 'app.L',
            notInternalOrObsolete: true,
          },
          notInternalOrObsolete: true,
        },
        isBestScore: {
          internal: false,
          obsolete: false,
          name: 'Yes',
          notInternalOrObsolete: true,
        },
        isBestScoreReverse: {
          internal: false,
          obsolete: false,
          name: 'Yes',
          notInternalOrObsolete: true,
        },
        confidence: {
          internal: false,
          obsolete: false,
          name: 'high',
          notInternalOrObsolete: true,
        },
        strictFilter: true,
        moderateFilter: true,
        predictionMethodsMatched: [
          {
            internal: false,
            obsolete: false,
            name: 'Xenbase',
            notInternalOrObsolete: true,
          },
        ],
        notInternalOrObsolete: true,
      },
    },
    {
      category: 'gene_to_gene_orthology',
      searchable: false,
      stringencyFilter: 'stringent',
      geneAnnotations: [
        {
          hasDiseaseAnnotations: true,
          hasExpressionAnnotations: false,
          geneIdentifier: 'HGNC:620',
        },
        {
          hasDiseaseAnnotations: false,
          hasExpressionAnnotations: true,
          geneIdentifier: 'MGI:88059',
        },
      ],
      geneAnnotationsMap: {
        'MGI:88059': {
          hasDiseaseAnnotations: false,
          hasExpressionAnnotations: true,
          geneIdentifier: 'MGI:88059',
        },
        'HGNC:620': {
          hasDiseaseAnnotations: true,
          hasExpressionAnnotations: false,
          geneIdentifier: 'HGNC:620',
        },
      },
      geneToGeneOrthologyGenerated: {
        internal: false,
        obsolete: false,
        subjectGene: {
          type: 'Gene',
          internal: false,
          obsolete: false,
          primaryExternalId: 'HGNC:620',
          taxon: {
            internal: false,
            obsolete: false,
            curie: 'NCBITaxon:9606',
            name: 'Homo sapiens',
            childCount: 0,
            descendantCount: 0,
            notInternalOrObsolete: true,
          },
          geneSymbol: {
            internal: false,
            obsolete: false,
            displayText: 'APP',
            notInternalOrObsolete: true,
          },
          notInternalOrObsolete: true,
        },
        objectGene: {
          type: 'Gene',
          internal: false,
          obsolete: false,
          primaryExternalId: 'MGI:88059',
          taxon: {
            internal: false,
            obsolete: false,
            curie: 'NCBITaxon:10090',
            name: 'Mus musculus',
            childCount: 0,
            descendantCount: 0,
            notInternalOrObsolete: true,
          },
          geneSymbol: {
            internal: false,
            obsolete: false,
            displayText: 'App',
            notInternalOrObsolete: true,
          },
          notInternalOrObsolete: true,
        },
        isBestScore: {
          internal: false,
          obsolete: false,
          name: 'Yes',
          notInternalOrObsolete: true,
        },
        isBestScoreReverse: {
          internal: false,
          obsolete: false,
          name: 'Yes',
          notInternalOrObsolete: true,
        },
        confidence: {
          internal: false,
          obsolete: false,
          name: 'high',
          notInternalOrObsolete: true,
        },
        strictFilter: true,
        moderateFilter: true,
        predictionMethodsMatched: [
          {
            internal: false,
            obsolete: false,
            name: 'HGNC',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'Hieranoid',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'InParanoid',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'OMA',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'OrthoFinder',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'OrthoInspector',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'PANTHER',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'PhylomeDB',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'SonicParanoid',
            notInternalOrObsolete: true,
          },
        ],
        predictionMethodsNotMatched: [
          {
            internal: false,
            obsolete: false,
            name: 'Ensembl Compara',
            notInternalOrObsolete: true,
          },
        ],
        predictionMethodsNotCalled: [
          {
            internal: false,
            obsolete: false,
            name: 'Xenbase',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'ZFIN',
            notInternalOrObsolete: true,
          },
        ],
        notInternalOrObsolete: true,
      },
    },
    {
      category: 'gene_to_gene_orthology',
      searchable: false,
      stringencyFilter: 'stringent',
      geneAnnotations: [
        {
          hasDiseaseAnnotations: true,
          hasExpressionAnnotations: false,
          geneIdentifier: 'HGNC:620',
        },
        {
          hasDiseaseAnnotations: false,
          hasExpressionAnnotations: true,
          geneIdentifier: 'ZFIN:ZDB-GENE-020220-1',
        },
      ],
      geneAnnotationsMap: {
        'ZFIN:ZDB-GENE-020220-1': {
          hasDiseaseAnnotations: false,
          hasExpressionAnnotations: true,
          geneIdentifier: 'ZFIN:ZDB-GENE-020220-1',
        },
        'HGNC:620': {
          hasDiseaseAnnotations: true,
          hasExpressionAnnotations: false,
          geneIdentifier: 'HGNC:620',
        },
      },
      geneToGeneOrthologyGenerated: {
        internal: false,
        obsolete: false,
        subjectGene: {
          type: 'Gene',
          internal: false,
          obsolete: false,
          primaryExternalId: 'HGNC:620',
          taxon: {
            internal: false,
            obsolete: false,
            curie: 'NCBITaxon:9606',
            name: 'Homo sapiens',
            childCount: 0,
            descendantCount: 0,
            notInternalOrObsolete: true,
          },
          geneSymbol: {
            internal: false,
            obsolete: false,
            displayText: 'APP',
            notInternalOrObsolete: true,
          },
          notInternalOrObsolete: true,
        },
        objectGene: {
          type: 'Gene',
          internal: false,
          obsolete: false,
          primaryExternalId: 'ZFIN:ZDB-GENE-020220-1',
          taxon: {
            internal: false,
            obsolete: false,
            curie: 'NCBITaxon:7955',
            name: 'Danio rerio',
            childCount: 0,
            descendantCount: 0,
            notInternalOrObsolete: true,
          },
          geneSymbol: {
            internal: false,
            obsolete: false,
            displayText: 'appb',
            notInternalOrObsolete: true,
          },
          notInternalOrObsolete: true,
        },
        isBestScore: {
          internal: false,
          obsolete: false,
          name: 'No',
          notInternalOrObsolete: true,
        },
        isBestScoreReverse: {
          internal: false,
          obsolete: false,
          name: 'Yes',
          notInternalOrObsolete: true,
        },
        confidence: {
          internal: false,
          obsolete: false,
          name: 'moderate',
          notInternalOrObsolete: true,
        },
        strictFilter: true,
        moderateFilter: true,
        predictionMethodsMatched: [
          {
            internal: false,
            obsolete: false,
            name: 'OMA',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'OrthoFinder',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'PANTHER',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'PhylomeDB',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'ZFIN',
            notInternalOrObsolete: true,
          },
        ],
        predictionMethodsNotMatched: [
          {
            internal: false,
            obsolete: false,
            name: 'SonicParanoid',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'Hieranoid',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'InParanoid',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'Ensembl Compara',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'OrthoInspector',
            notInternalOrObsolete: true,
          },
        ],
        predictionMethodsNotCalled: [
          {
            internal: false,
            obsolete: false,
            name: 'Xenbase',
            notInternalOrObsolete: true,
          },
          {
            internal: false,
            obsolete: false,
            name: 'HGNC',
            notInternalOrObsolete: true,
          },
        ],
        notInternalOrObsolete: true,
      },
    },
  ],
  total: 11,
  returnedRecords: 11,
  requestDate: '2025/07/07 18:54:44',
};

export default mock;
