import { CitationsAPIModel } from '../../adapters/citationsConverter';

// uniprot/api/citations/14702039
const mock: CitationsAPIModel = {
  citation: {
    citationType: 'UniProt indexed literatures',
    authors: [
      'Ota T.',
      'Suzuki Y.',
      'Nishikawa T.',
      'Otsuki T.',
      'Sugiyama T.',
      'Irie R.',
      'Wakamatsu A.',
      'Hayashi K.',
      'Sato H.',
      'Nagai K.',
      'Kimura K.',
      'Makita H.',
      'Sekine M.',
      'Obayashi M.',
      'Nishi T.',
      'Shibahara T.',
      'Tanaka T.',
      'Ishii S.',
      'Yamamoto J.',
      'Saito K.',
      'Kawai Y.',
      'Isono Y.',
      'Nakamura Y.',
      'Nagahari K.',
      'Murakami K.',
      'Yasuda T.',
      'Iwayanagi T.',
      'Wagatsuma M.',
      'Shiratori A.',
      'Sudo H.',
      'Hosoiri T.',
      'Kaku Y.',
      'Kodaira H.',
      'Kondo H.',
      'Sugawara M.',
      'Takahashi M.',
      'Kanda K.',
      'Yokoi T.',
      'Furuya T.',
      'Kikkawa E.',
      'Omura Y.',
      'Abe K.',
      'Kamihara K.',
      'Katsuta N.',
      'Sato K.',
      'Tanikawa M.',
      'Yamazaki M.',
      'Ninomiya K.',
      'Ishibashi T.',
      'Yamashita H.',
      'Murakawa K.',
      'Fujimori K.',
      'Tanai H.',
      'Kimata M.',
      'Watanabe M.',
      'Hiraoka S.',
      'Chiba Y.',
      'Ishida S.',
      'Ono Y.',
      'Takiguchi S.',
      'Watanabe S.',
      'Yosida M.',
      'Hotuta T.',
      'Kusano J.',
      'Kanehori K.',
      'Takahashi-Fujii A.',
      'Hara H.',
      'Tanase T.-O.',
      'Nomura Y.',
      'Togiya S.',
      'Komai F.',
      'Hara R.',
      'Takeuchi K.',
      'Arita M.',
      'Imose N.',
      'Musashino K.',
      'Yuuki H.',
      'Oshima A.',
      'Sasaki N.',
      'Aotsuka S.',
      'Yoshikawa Y.',
      'Matsunawa H.',
      'Ichihara T.',
      'Shiohata N.',
      'Sano S.',
      'Moriya S.',
      'Momiyama H.',
      'Satoh N.',
      'Takami S.',
      'Terashima Y.',
      'Suzuki O.',
      'Nakagawa S.',
      'Senoh A.',
      'Mizoguchi H.',
      'Goto Y.',
      'Shimizu F.',
      'Wakebe H.',
      'Hishigaki H.',
      'Watanabe T.',
      'Sugiyama A.',
      'Takemoto M.',
      'Kawakami B.',
      'Yamazaki M.',
      'Watanabe K.',
      'Kumagai A.',
      'Itakura S.',
      'Fukuzumi Y.',
      'Fujimori Y.',
      'Komiyama M.',
      'Tashiro H.',
      'Tanigami A.',
      'Fujiwara T.',
      'Ono T.',
      'Yamada K.',
      'Fujii Y.',
      'Ozaki K.',
      'Hirao M.',
      'Ohmori Y.',
      'Kawabata A.',
      'Hikiji T.',
      'Kobatake N.',
      'Inagaki H.',
      'Ikema Y.',
      'Okamoto S.',
      'Okitani R.',
      'Kawakami T.',
      'Noguchi S.',
      'Itoh T.',
      'Shigeta K.',
      'Senba T.',
      'Matsumura K.',
      'Nakajima Y.',
      'Mizuno T.',
      'Morinaga M.',
      'Sasaki M.',
      'Togashi T.',
      'Oyama M.',
      'Hata H.',
      'Watanabe M.',
      'Komatsu T.',
      'Mizushima-Sugano J.',
      'Satoh T.',
      'Shirai Y.',
      'Takahashi Y.',
      'Nakagawa K.',
      'Okumura K.',
      'Nagase T.',
      'Nomura N.',
      'Kikuchi H.',
      'Masuho Y.',
      'Yamashita R.',
      'Nakai K.',
      'Yada T.',
      'Nakamura Y.',
      'Ohara O.',
      'Isogai T.',
      'Sugano S.',
    ],
    citationCrossReferences: [
      {
        database: 'PubMed',
        id: '14702039',
      },
      {
        database: 'DOI',
        id: '10.1038/ng1285',
      },
    ],
    title:
      'Complete sequencing and characterization of 21,243 full-length human cDNAs.',
    publicationDate: '2004',
    journal: 'Nat. Genet.',
    firstPage: '40',
    lastPage: '45',
    volume: '36',
    completeAuthorList: true,
    literatureAbstract:
      'As a base for human transcriptome and functional genomics, we created the "full- length long Japan" (FLJ) collection of sequenced human cDNAs. We determined the entire sequence of 21,243 selected clones and found that 14,490 cDNAs (10,897 clusters) were unique to the FLJ collection. About half of them (5,416) seemed to be protein-coding. Of those, 1,999 clusters had not been predicted by computational methods. The distribution of GC content of nonpredicted cDNAs had a peak at approximately 58% compared with a peak at approximately 42%for predicted cDNAs. Thus, there seems to be a slight bias against GC-rich transcripts in current gene prediction procedures. The rest of the cDNAs unique to the FLJ collection (5,481) contained no obvious open reading frames (ORFs) and thus are candidate noncoding RNAs. About one-fourth of them (1,378) showed a clear pattern of splicing. The distribution of GC content of noncoding cDNAs was narrow and had a peak at approximately 42%, relatively low compared with that of protein-coding cDNAs.',
  },
  references: [
    {
      source: {
        name: 'UniProtKB reviewed (Swiss-Prot)',
      },
      pubMedId: '14702039',
      sourceCategories: ['Sequence'],
      referenceComments: [
        {
          value: 'Kidney',
          type: 'TISSUE',
        },
        {
          value: 'Thalamus',
          type: 'TISSUE',
        },
      ],
      referencePositions: [
        'NUCLEOTIDE SEQUENCE [LARGE SCALE MRNA] (ISOFORM 2)',
      ],
      referenceNumber: 1,
    },
  ],
  statistics: {
    reviewedProteinCount: 10309,
    unreviewedProteinCount: 2615,
    computationallyMappedProteinCount: 0,
    communityMappedProteinCount: 0,
  },
};

export default mock;
