type OtherType =
  | 'Initiator methionine'
  | 'Signal'
  | 'Propeptide'
  | 'Transit peptide'
  | 'Chain'
  | 'Peptide'
  | 'Topological domain'
  | 'Transmembrane'
  | 'Intramembrane'
  | 'Domain'
  | 'Repeat'
  | 'Calcium binding'
  | 'Zinc finger'
  | 'DNA binding'
  | 'Nucleotide binding'
  | 'Region'
  | 'Coiled coil'
  | 'Motif'
  | 'Compositional bias'
  | 'Active site'
  | 'Metal binding'
  | 'Binding site'
  | 'Site'
  | 'Non-standard residue'
  | 'Modified residue'
  | 'Lipidation'
  | 'Glycosylation'
  | 'Disulfide bond'
  | 'Cross-link'
  | 'Alternative sequence'
  | 'Natural variant'
  | 'Mutagenesis'
  | 'Sequence uncertainty'
  | 'Sequence conflict'
  | 'Non-adjacent residues'
  | 'Non-terminal residue'
  | 'Helix'
  | 'Turn'
  | 'Beta strand'
  | 'Other'; // For anything else

export type FunctionFeatures =
  | 'Domain'
  | 'Repeat'
  | 'Calcium binding'
  | 'Zinc finger'
  | 'DNA binding'
  | 'Nucleotide binding'
  | 'Region'
  | 'Coiled coil'
  | 'Motif'
  | 'Active site'
  | 'Metal binding'
  | 'Binding site'
  | 'Site';

type FeatureType = OtherType | FunctionFeatures;

export default FeatureType;
