apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: __K8S_CERTIFICATE__
      server: __K8S_URL__
    name: wp-webadmin-02
contexts:
  - context:
      cluster: wp-webadmin-02
      user: team-admin-wp-webadmin-02
      namespace: uniprot-front-end
    name: team-admin-wp-webadmin-02
current-context: team-admin-wp-webadmin-02
kind: Config
preferences: {}
users:
  - name: team-admin-wp-webadmin-02
    user:
      token: __K8S_USER_TOKEN__
