import { ExternalLink, Loader } from 'franklin-sites';
import { Link } from 'react-router-dom';

import { Location, LocationToPath } from '../../../../app/config/urls';
import ErrorHandler from '../../../../shared/components/error-pages/ErrorHandler';
import TableFromData, {
  TableFromDataColumn,
} from '../../../../shared/components/table/TableFromData';
import WithTooltip from '../../../../shared/components/WithTooltip';
import externalUrls from '../../../../shared/config/externalUrls';
import useDataApi from '../../../../shared/hooks/useDataApi';
import { stringifyQuery } from '../../../../shared/utils/url';
import { AgrOrthologs, AgrOrthologsResult } from '../../../types/agrOrthologs';
import { getXrefAndTaxonQuery } from '../../../utils/agr-homology';
import styles from './styles/agr-homology.module.scss';

// Lifted from https://github.com/alliance-genome/agr_ui/blob/6f5acc104df6274bb0642a2317a5b6b102a91b32/src/components/orthology/orthologyTable.js#L29
const isBest = (value = '') =>
  typeof value === 'boolean' ? value : !!value.match(/yes/i);

// Lifted from https://github.com/alliance-genome/agr_ui/blob/6f5acc104df6274bb0642a2317a5b6b102a91b32/src/components/homology/constants.js#L1
const ORTHOLOGY_METHODS = [
  {
    method: 'Ensembl Compara',
    tooltip:
      'Orthology relationships inferred by the Ensembl Compara pipeline.',
  },
  {
    method: 'HGNC',
    tooltip:
      'Orthologs manually curated by the HUGO Gene Nomenclature Committee for human–model-organism comparisons.',
  },
  {
    method: 'Hieranoid',
    tooltip:
      'Ortholog predictions generated by the Hieranoid hierarchical algorithm.',
  },
  {
    method: 'InParanoid',
    tooltip: 'Orthologous gene pairs identified using the InParanoid tool.',
  },
  {
    method: 'OMA',
    tooltip:
      'Orthology relationships predicted by the OMA (Orthologous MAtrix) algorithm.',
  },
  {
    method: 'OrthoFinder',
    tooltip:
      'Orthology assignments determined by the OrthoFinder graph-based method.',
  },
  {
    method: 'OrthoInspector',
    tooltip:
      'Orthologs detected using the OrthoInspector homology-detection tool.',
  },
  {
    method: 'PANTHER',
    tooltip:
      'Ortholog relationships assigned by PANTHER’s phylogenetic family models.',
  },
  {
    method: 'PhylomeDB',
    tooltip: 'Orthology calls supported by the PhylomeDB gene-tree database.',
  },
  {
    method: 'SonicParanoid',
    tooltip: 'Orthologs inferred by the SonicParanoid pipeline.',
  },
  {
    method: 'Xenbase',
    tooltip: 'Orthologs manually curated by Xenbase for Xenopus species.',
  },
  {
    method: 'ZFIN',
    tooltip: 'Orthologs manually curated by ZFIN for Danio rerio.',
  },
];
// Lifted, with modification, from https://github.com/alliance-genome/agr_ui/blob/f1ab35ab8a869e2956e87c8c19e0fcce2f7988ed/src/constants.js#L424C14-L424C20
const TAXON_TO_INDEX = new Map(
  [
    'NCBITaxon:9606',
    'NCBITaxon:10090',
    'NCBITaxon:10116',
    'NCBITaxon:8355',
    'NCBITaxon:8364',
    'NCBITaxon:7955',
    'NCBITaxon:7227',
    'NCBITaxon:6239',
    'NCBITaxon:559292',
    'NCBITaxon:2697049',
  ].map((taxon, index) => [taxon, index])
);

const columns: TableFromDataColumn<AgrOrthologsResult>[] = [
  {
    id: 'species',
    label: (
      <WithTooltip tooltip="Target organism in which this ortholog candidate resides.">
        Species
      </WithTooltip>
    ),
    filter: (data, filterValue) =>
      data.geneToGeneOrthologyGenerated.objectGene.taxon.name === filterValue,
    render: (data) => data.geneToGeneOrthologyGenerated.objectGene.taxon.name,
  },
  {
    id: 'gene-symbol',
    label: (
      <WithTooltip tooltip="Gene symbol of the ortholog in the target species.">
        Gene Symbol
      </WithTooltip>
    ),
    getOption: (data) =>
      data.geneToGeneOrthologyGenerated.objectGene.geneSymbol.displayText || '',
    filter: (data, filterValue) =>
      data.geneToGeneOrthologyGenerated.objectGene.geneSymbol.displayText ===
      filterValue,
    render: (data) => {
      const query = getXrefAndTaxonQuery(
        data.geneToGeneOrthologyGenerated.objectGene
      );
      const gene =
        data.geneToGeneOrthologyGenerated.objectGene.geneSymbol.displayText;

      return query ? (
        <Link
          to={{
            pathname: LocationToPath[Location.UniProtKBResults],
            search: stringifyQuery({
              query,
            }),
          }}
        >
          {gene}
        </Link>
      ) : (
        gene
      );
    },
  },

  {
    id: 'best',
    label: (
      <WithTooltip tooltip="Indicates this gene is the top-scoring (highest-count) ortholog candidate within this species.">
        Best
      </WithTooltip>
    ),
    filter: (data, filterValue) =>
      filterValue ===
      (isBest(data.geneToGeneOrthologyGenerated.isBestScore.name)
        ? 'Yes'
        : 'No'),
    render: (data) =>
      isBest(data.geneToGeneOrthologyGenerated.isBestScore.name) ? 'Yes' : 'No',
  },
  {
    id: 'best-reverse',
    label: (
      <WithTooltip tooltip="Indicates this gene pair is also the top-scoring (highest-count) ortholog when roles are reversed (reciprocal best hit).">
        Best Reverse
      </WithTooltip>
    ),
    filter: (data, filterValue) =>
      filterValue ===
      (isBest(data.geneToGeneOrthologyGenerated.isBestScoreReverse.name)
        ? 'Yes'
        : 'No'),
    render: (data) =>
      isBest(data.geneToGeneOrthologyGenerated.isBestScoreReverse.name)
        ? 'Yes'
        : 'No',
  },
  {
    id: 'methods',
    label: (
      <div className={styles['methods-label']}>
        <WithTooltip tooltip="Result of orthology-inference resource and algorithm methods.">
          Method
        </WithTooltip>
        {ORTHOLOGY_METHODS.map(({ method, tooltip }) => (
          <WithTooltip key={method} tooltip={tooltip}>
            <div>{method}</div>
          </WithTooltip>
        ))}
        <WithTooltip tooltip="Number of independent orthology methods that support this gene pair.">
          <div className={styles['match-count-label']}>Match counts</div>
        </WithTooltip>
      </div>
    ),
    render: (data) => {
      const scoreNumerator =
        data.geneToGeneOrthologyGenerated.predictionMethodsMatched.length;
      const scoreDenominator =
        scoreNumerator +
        (data.geneToGeneOrthologyGenerated.predictionMethodsNotMatched
          ?.length || 0);
      return [
        ...ORTHOLOGY_METHODS.map(({ method }) => {
          const predictionMethodsMatchedSet = new Set(
            data.geneToGeneOrthologyGenerated.predictionMethodsMatched?.map(
              (m) => m.name
            )
          );
          const predictionMethodsNotMatchedSet = new Set(
            data.geneToGeneOrthologyGenerated.predictionMethodsNotMatched?.map(
              (m) => m.name
            )
          );
          let symbol: string, title: string;
          if (predictionMethodsMatchedSet.has(method)) {
            symbol = '●';
            title = `Match by ${method}`;
          } else if (predictionMethodsNotMatchedSet.has(method)) {
            symbol = '○';
            title = `No match by ${method}`;
          } else {
            symbol = '-';
            title = `Comparison not available for ${method}`;
          }
          return (
            <span
              key={method}
              title={title}
              className={styles['methods-render']}
            >
              {symbol}
            </span>
          );
        }),
        <span
          key="count"
          title={`${scoreNumerator} matches from ${scoreDenominator} checked methods (${Math.round((100 * scoreNumerator) / scoreDenominator)}%)`}
          className={styles['match-count']}
        >
          {scoreNumerator} of {scoreDenominator}
        </span>,
      ];
    },
  },
];

const getRowId = (data: AgrOrthologsResult) =>
  `${data.geneToGeneOrthologyGenerated.objectGene.taxon.name}-${data.geneToGeneOrthologyGenerated.objectGene.geneSymbol.displayText}`;

type Props = {
  agrId: string;
};

const AgrOrthology = ({ agrId }: Props) => {
  const { data, loading, error, status, progress } = useDataApi<AgrOrthologs>(
    agrId ? externalUrls.AgrHomologs(agrId, 'orthologs') : null
  );

  if (loading) {
    return <Loader progress={progress} />;
  }

  if (error) {
    return <ErrorHandler status={status} error={error} />;
  }

  if (!data?.results?.length) {
    return 'No Orthology data is available from the Alliance of Genome Resources.';
  }

  // Lifted from https://github.com/alliance-genome/agr_ui/blob/f1ab35ab8a869e2956e87c8c19e0fcce2f7988ed/src/components/orthology/orthologyTable.js#L56
  const sorted = data.results.sort((a, b) => {
    const aIndex =
      TAXON_TO_INDEX.get(
        a.geneToGeneOrthologyGenerated.objectGene.taxon.curie
      ) || TAXON_TO_INDEX.size;
    const bIndex =
      TAXON_TO_INDEX.get(
        b.geneToGeneOrthologyGenerated.objectGene.taxon.curie
      ) || TAXON_TO_INDEX.size;
    const indexComparison = aIndex - bIndex;
    if (indexComparison !== 0) {
      return indexComparison;
    }
    const aLength =
      a.geneToGeneOrthologyGenerated.predictionMethodsMatched.length;
    const bLength =
      b.geneToGeneOrthologyGenerated.predictionMethodsMatched.length;
    const lengthComparison = bLength - aLength;
    return lengthComparison;
  });
  // TODO: expand/collapse showing for P05067 when it shouldn't be there
  return (
    <>
      <div className={styles['agr-link']}>
        The data in this table is sourced from the Alliance of Genome Resources.
        <br />
        <ExternalLink url={externalUrls.AgrEntryHomologs(agrId, 'orthology')}>
          View source data
        </ExternalLink>
      </div>
      <TableFromData
        id="agr-orthology"
        columns={columns}
        data={sorted}
        getRowId={getRowId}
        className={styles['agr-orthology-table']}
      />
    </>
  );
};

export default AgrOrthology;
