declare module '*img.svg' {
  const content: string;
  export default content;
}

/**
 * Used to type components generated by the "@svgr/webpack" loader
 */
declare module '*.svg' {
  const content: React.FunctionComponent<React.SVGAttributes<SVGElement>>;
  export default content;
}
declare module '*.png' {
  const content: string;
  export default content;
}

declare module '*.gif' {
  const content: string;
  export default content;
}

declare module '*.jpg' {
  const content: string;
  export default content;
}

declare module '*.jpeg' {
  const content: string;
  export default content;
}

// NOTE: this will not catch keys/classnames that do not exist in the stylesheet
declare module '*.module.scss' {
  const classes: { [key: string]: string };
  export = classes;
}
declare module '*.module.css' {
  const classes: { [key: string]: string };
  export = classes;
}

// Just for one test file
declare module 'react-beautiful-dnd-test-utils';
