/**
 * Used to type components generated by the "@svgr/webpack" loader
 */

// eslint-disable-next-line @typescript-eslint/no-empty-interface
interface SvgrComponent
  extends React.StatelessComponent<React.SVGAttributes<SVGElement>> {}

declare module '*.svg' {
  const content: SvgrComponent;
  export default content;
}
declare module '*.png' {
  const content: string;
  export default content;
}

declare module '*.gif' {
  const content: string;
  export default content;
}

declare module '*.jpg' {
  const content: string;
  export default content;
}

declare module '*.jpeg' {
  const content: string;
  export default content;
}

// NOTE: this will not catch keys/classnames that do not exist in the stylesheet
declare module '*.module.scss' {
  const classes: { [key: string]: string };
  export default classes;
}

// Just for one test file
declare module 'react-beautiful-dnd-test-utils';
