declare module '*img.svg' {
  const content: string;
  export default content;
}

/**
 * Used to type components generated by the "@svgr/webpack" loader
 */
declare module '*.svg' {
  const content: React.FunctionComponent<React.SVGAttributes<SVGElement>>;
  export default content;
}
declare module '*.png' {
  const content: string;
  export default content;
}

declare module '*.gif' {
  const content: string;
  export default content;
}

declare module '*.jpg' {
  const content: string;
  export default content;
}

declare module '*.jpeg' {
  const content: string;
  export default content;
}

// NOTE: this will not catch keys/classnames that do not exist in the stylesheet
declare module '*.module.scss' {
  const classes: { [key: string]: string };
  export = classes;
}
declare module '*.module.css' {
  const classes: { [key: string]: string };
  export = classes;
}

// Side-effect imports of global stylesheets.
declare module '*.scss';
declare module '*.css';

// Custom element registered for side effects only.
declare module '@geneontology/web-components/go-annotation-ribbon-strips';

// Just for one test file
declare module 'react-beautiful-dnd-test-utils';

// Custom elements lib without types
declare module '@swissprot/rhea-reaction-viz-test' {
  const content: CustomElementConstructor;
  export default content;
}
