// Source: uniparc/UPI0000000001/databases
// Retrieved: 2026-01-26
const mock = {
  results: [
    {
      database: 'UniProtKB/Swiss-Prot',
      id: 'P07612',
      versionI: 3,
      version: 3,
      active: true,
      created: '2007-01-23',
      lastUpdated: '2026-01-28',
      geneName: 'OPG099',
      proteinName: 'Entry-fusion complex associated protein OPG095',
      organism: {
        scientificName: 'Vaccinia virus (strain Western Reserve)',
        commonName: 'VACV',
        taxonId: 10254,
      },
      ncbiGi: '138624',
    },
    {
      database: 'UniProtKB/Swiss-Prot',
      id: 'P07612',
      versionI: 1,
      version: 1,
      active: false,
      created: '1988-11-01',
      lastUpdated: '2004-11-23',
      organism: {
        scientificName: 'Vaccinia virus (strain Western Reserve)',
        commonName: 'VACV',
        taxonId: 10254,
      },
    },
    {
      database: 'UniProtKB/TrEMBL',
      id: 'Q6RZL4',
      versionI: 1,
      version: 1,
      active: true,
      created: '2004-07-05',
      lastUpdated: '2026-01-28',
      geneName: 'RPXV077',
      proteinName: 'RPXV077',
      organism: {
        scientificName: 'Rabbitpox virus (strain Utrecht)',
        commonName: 'RPV',
        taxonId: 45417,
      },
    },
    {
      database: 'UniProtKB/TrEMBL',
      id: 'Q76QK2',
      versionI: 1,
      version: 1,
      active: true,
      created: '2004-07-05',
      lastUpdated: '2026-01-28',
      geneName: 'N1R',
      proteinName: 'N1R protein',
      organism: {
        scientificName: 'Cowpox virus (strain GRI-90 / Grishak)',
        commonName: 'CPV',
        taxonId: 265871,
      },
    },
    {
      database: 'UniProtKB/TrEMBL',
      id: 'Q71TT2',
      versionI: 1,
      version: 1,
      active: true,
      created: '2006-04-18',
      lastUpdated: '2026-01-28',
      geneName: 'L1R',
      proteinName: 'L1R',
      organism: {
        scientificName: 'Vaccinia virus',
        commonName: 'VACV',
        taxonId: 10245,
      },
    },
    {
      database: 'UniProtKB/TrEMBL',
      id: 'Q0GNZ6',
      versionI: 1,
      version: 1,
      active: true,
      created: '2006-10-03',
      lastUpdated: '2026-01-28',
      geneName: 'HSPV_VK05_RKI-089',
      proteinName: 'HSPV089',
      organism: {
        scientificName: 'Horsepox virus',
        commonName: 'HSPV',
        taxonId: 397342,
      },
    },
    {
      database: 'UniProtKB/TrEMBL',
      id: 'A0A2I2MDI1',
      versionI: 1,
      version: 1,
      active: true,
      created: '2018-02-28',
      lastUpdated: '2026-01-28',
      geneName: 'L1R',
      proteinName: 'IMV membrane protein',
      organism: {
        scientificName: 'Vaccinia virus (strain Western Reserve)',
        commonName: 'VACV',
        taxonId: 10254,
      },
    },
    {
      database: 'UniProtKB/TrEMBL',
      id: 'G0XTE8',
      versionI: 1,
      version: 1,
      active: true,
      created: '2024-11-27',
      lastUpdated: '2026-01-28',
      geneName: 'CPXV_FIN2000_MAN_093',
      proteinName: 'IMV membrane protein',
      organism: {
        scientificName: 'Cowpox virus',
        commonName: 'CPV',
        taxonId: 10243,
      },
    },
    {
      database: 'UniProtKB/TrEMBL',
      id: 'Q76ZT7',
      versionI: 1,
      version: 1,
      active: false,
      created: '2004-07-05',
      lastUpdated: '2011-06-28',
    },
    {
      database: 'UniProtKB/TrEMBL',
      id: 'A0A7I8V511',
      versionI: 1,
      version: 1,
      active: false,
      created: '2021-04-07',
      lastUpdated: '2021-06-02',
      geneName: 'VACV VK01 RKI-115 CDS',
      proteinName: 'Polyprotein',
      organism: {
        scientificName: 'Homo sapiens',
        commonName: 'Human',
        taxonId: 9606,
      },
    },
    {
      database: 'RefSeq',
      id: 'YP_232970',
      versionI: 1,
      version: 1,
      active: true,
      created: '2005-10-06',
      lastUpdated: '2025-09-02',
      geneName: 'L1R',
      proteinName: 'IMV membrane protein',
      organism: {
        scientificName: 'Vaccinia virus',
        commonName: 'VACV',
        taxonId: 10245,
      },
      ncbiGi: '66275885',
    },
    {
      database: 'RefSeq',
      id: 'YP_010509298',
      versionI: 1,
      version: 1,
      active: true,
      created: '2022-10-19',
      lastUpdated: '2025-09-02',
      geneName: 'OPG095',
      proteinName: 'IMV membrane protein L1R',
      organism: {
        scientificName: 'Horsepox virus',
        commonName: 'HSPV',
        taxonId: 397342,
      },
    },
    {
      database: 'RefSeq',
      id: 'YP_006721',
      versionI: 1,
      version: 1,
      active: false,
      created: '2004-07-08',
      lastUpdated: '2005-07-09',
    },
    {
      database: 'RefSeq',
      id: 'YP_010488138',
      versionI: 1,
      version: 1,
      active: false,
      created: '2022-09-30',
      lastUpdated: '2022-11-07',
      geneName: 'OCZ32_gp108',
      proteinName: 'HSPV089',
      organism: {
        scientificName: 'Horsepox virus',
        commonName: 'HSPV',
        taxonId: 397342,
      },
    },
    {
      database: 'RefSeq',
      id: 'YP_010500340',
      versionI: 1,
      version: 1,
      active: false,
      created: '2022-10-09',
      lastUpdated: '2022-11-07',
      geneName: 'OPG095',
      proteinName: 'IMV membrane protein L1R',
      organism: {
        scientificName: 'Horsepox virus',
        commonName: 'HSPV',
        taxonId: 397342,
      },
    },
    {
      database: 'EMBL',
      id: 'AAO89367',
      versionI: 1,
      version: 1,
      active: true,
      created: '2003-06-16',
      lastUpdated: '2024-07-17',
      geneName: 'VACWR088',
      proteinName: 'IMV membrane protein',
      organism: {
        scientificName: 'Vaccinia virus (strain Western Reserve)',
        commonName: 'VACV',
        taxonId: 10254,
      },
      ncbiGi: '29692194',
      proteomeId: 'UP000000344',
      component: 'Segment',
    },
    {
      database: 'EMBL',
      id: 'CAD90637',
      versionI: 1,
      version: 1,
      active: true,
      created: '2003-06-16',
      lastUpdated: '2024-07-17',
      geneName: 'N1R',
      proteinName: 'N1R protein',
      organism: {
        scientificName: 'Cowpox virus',
        commonName: 'CPV',
        taxonId: 10243,
      },
      ncbiGi: '30519462',
      proteomeId: 'UP000137384',
      component: 'Segment',
    },
    {
      database: 'EMBL',
      id: 'AAS49790',
      versionI: 1,
      version: 1,
      active: true,
      created: '2004-03-31',
      lastUpdated: '2024-07-17',
      geneName: 'RPXV077',
      proteinName: 'RPXV077',
      organism: {
        scientificName: 'Rabbitpox virus',
        taxonId: 32606,
      },
      ncbiGi: '44971440',
      proteomeId: 'UP000166173',
      component: 'Segment',
    },
    {
      database: 'EMBL',
      id: 'ABH08195',
      versionI: 1,
      version: 1,
      active: true,
      created: '2006-09-02',
      lastUpdated: '2025-09-22',
      proteinName: 'HSPV089',
      organism: {
        scientificName: 'Horsepox virus',
        commonName: 'HSPV',
        taxonId: 397342,
      },
      ncbiGi: '111184275',
      proteomeId: 'UP000111173',
      component: 'Segment',
    },
    {
      database: 'EMBL',
      id: 'ADZ29210',
      versionI: 1,
      version: 1,
      active: true,
      created: '2011-08-10',
      lastUpdated: '2024-07-17',
      geneName: 'CPXV_FIN2000_MAN_093',
      proteinName: 'IMV membrane protein',
      organism: {
        scientificName: 'Cowpox virus',
        commonName: 'CPV',
        taxonId: 10243,
      },
      ncbiGi: '325557828',
      proteomeId: 'UP000113999',
      component: 'Segment',
    },
    {
      database: 'EMBL',
      id: 'AGJ91256',
      versionI: 1,
      version: 1,
      active: true,
      created: '2013-04-24',
      lastUpdated: '2024-07-17',
      geneName: 'VACV_TT8_108',
      proteinName: 'Myristylated MP IMV',
      organism: {
        scientificName: 'Vaccinia virus',
        commonName: 'VACV',
        taxonId: 10245,
      },
      ncbiGi: '480542501',
      proteomeId: 'UP000181229',
      component: 'Segment',
    },
    {
      database: 'EMBL',
      id: 'AGJ92346',
      versionI: 1,
      version: 1,
      active: true,
      created: '2013-04-24',
      lastUpdated: '2024-07-17',
      geneName: 'VACV_TT12_108',
      proteinName: 'Myristylated MP IMV',
      organism: {
        scientificName: 'Vaccinia virus',
        commonName: 'VACV',
        taxonId: 10245,
      },
      ncbiGi: '480543595',
      proteomeId: 'UP000181062',
      component: 'Genome',
    },
    {
      database: 'EMBL',
      id: 'AIX99207',
      versionI: 1,
      version: 1,
      active: true,
      created: '2014-12-15',
      lastUpdated: '2024-07-17',
      geneName: 'VAC_TKT3_078',
      proteinName: 'Neutralizing antibody IMV membrane protein target',
      organism: {
        scientificName: 'Vaccinia virus',
        commonName: 'VACV',
        taxonId: 10245,
      },
      ncbiGi: '723605536',
      proteomeId: 'UP000181110',
      component: 'Segment',
    },
    {
      database: 'EMBL',
      id: 'AIX99412',
      versionI: 1,
      version: 1,
      active: true,
      created: '2014-12-15',
      lastUpdated: '2024-07-17',
      geneName: 'VAC_TKT4_078',
      proteinName: 'Neutralizing antibody IMV membrane protein target',
      organism: {
        scientificName: 'Vaccinia virus',
        commonName: 'VACV',
        taxonId: 10245,
      },
      ncbiGi: '723605742',
      proteomeId: 'UP000153808',
      component: 'Segment',
    },
    {
      database: 'EMBL',
      id: 'ALF05084',
      versionI: 1,
      version: 1,
      active: true,
      created: '2015-10-11',
      lastUpdated: '2024-07-17',
      geneName: 'VACV_IOC_B141_114',
      proteinName: 'Neutralizing antibody MV membrane protein',
      organism: {
        scientificName: 'Vaccinia virus',
        commonName: 'VACV',
        taxonId: 10245,
      },
      ncbiGi: '929050100',
      proteomeId: 'UP000097422',
      component: 'Genome',
    },
  ],
};

export default mock;
