import { IDMappingFormConfig } from '../../../types/idMappingFormConfig';

// Source: /api/configure/idmapping/fields
// Retrieved: 2021-10-14
const data: IDMappingFormConfig = {
  groups: [
    {
      groupName: 'UniProt',
      items: [
        {
          displayName: 'UniProtKB',
          name: 'UniProtKB',
          from: false,
          to: true,
        },
        {
          displayName: 'UniProtKB AC/ID',
          name: 'UniProtKB_AC-ID',
          from: true,
          to: false,
          ruleId: 1,
        },
        {
          displayName: 'UniProtKB/Swiss-Prot',
          name: 'UniProtKB-Swiss-Prot',
          from: false,
          to: true,
        },
        {
          displayName: 'UniParc',
          name: 'UniParc',
          from: true,
          to: true,
          ruleId: 2,
        },
        {
          displayName: 'UniRef50',
          name: 'UniRef50',
          from: true,
          to: true,
          ruleId: 3,
        },
        {
          displayName: 'UniRef90',
          name: 'UniRef90',
          from: true,
          to: true,
          ruleId: 4,
        },
        {
          displayName: 'UniRef100',
          name: 'UniRef100',
          from: true,
          to: true,
          ruleId: 5,
        },
        {
          displayName: 'Gene Name',
          name: 'Gene_Name',
          from: true,
          to: true,
          ruleId: 6,
        },
        {
          displayName: 'CRC64',
          name: 'CRC64',
          from: true,
          to: true,
          ruleId: 7,
        },
      ],
    },
    {
      groupName: 'Sequence databases',
      items: [
        {
          displayName: 'CCDS',
          name: 'CCDS',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'EMBL/GenBank/DDBJ',
          name: 'EMBL-GenBank-DDBJ',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'EMBL/GenBank/DDBJ CDS',
          name: 'EMBL-GenBank-DDBJ_CDS',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'PIR',
          name: 'PIR',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'RefSeq',
          name: 'RefSeq',
          from: true,
          to: true,
          ruleId: 7,
        },
      ],
    },
    {
      groupName: '3D structure databases',
      items: [
        {
          displayName: 'PDB',
          name: 'PDB',
          from: true,
          to: true,
          ruleId: 7,
        },
      ],
    },
    {
      groupName: 'Protein-protein interaction databases',
      items: [
        {
          displayName: 'BioGRID',
          name: 'BioGRID',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'ComplexPortal',
          name: 'ComplexPortal',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'DIP',
          name: 'DIP',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'STRING',
          name: 'STRING',
          from: true,
          to: true,
          ruleId: 7,
        },
      ],
    },
    {
      groupName: 'Chemistry',
      items: [
        {
          displayName: 'ChEMBL',
          name: 'ChEMBL',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'DrugBank',
          name: 'DrugBank',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'GuidetoPHARMACOLOGY',
          name: 'GuidetoPHARMACOLOGY',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'SwissLipids',
          name: 'SwissLipids',
          from: true,
          to: true,
          ruleId: 7,
        },
      ],
    },
    {
      groupName: 'Protein family/group databases',
      items: [
        {
          displayName: 'Allergome',
          name: 'Allergome',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'CLAE',
          name: 'CLAE',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'ESTHER',
          name: 'ESTHER',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'MEROPS',
          name: 'MEROPS',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'PeroxiBase',
          name: 'PeroxiBase',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'REBASE',
          name: 'REBASE',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'TCDB',
          name: 'TCDB',
          from: true,
          to: true,
          ruleId: 7,
        },
      ],
    },
    {
      groupName: 'PTM databases',
      items: [
        {
          displayName: 'GlyConnect',
          name: 'GlyConnect',
          from: true,
          to: true,
          ruleId: 7,
        },
      ],
    },
    {
      groupName: 'Genetic variation databases',
      items: [
        {
          displayName: 'BioMuta',
          name: 'BioMuta',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'DMDM',
          name: 'DMDM',
          from: true,
          to: true,
          ruleId: 7,
        },
      ],
    },
    {
      groupName: '2D gel databases',
      items: [
        {
          displayName: 'World-2DPAGE',
          name: 'World-2DPAGE',
          from: true,
          to: true,
          ruleId: 7,
        },
      ],
    },
    {
      groupName: 'Proteomic databases',
      items: [
        {
          displayName: 'CPTAC',
          name: 'CPTAC',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'ProteomicsDB',
          name: 'ProteomicsDB',
          from: true,
          to: true,
          ruleId: 7,
        },
      ],
    },
    {
      groupName: 'Protocols and materials databases',
      items: [
        {
          displayName: 'DNASU',
          name: 'DNASU',
          from: true,
          to: true,
          ruleId: 7,
        },
      ],
    },
    {
      groupName: 'Genome annotation databases',
      items: [
        {
          displayName: 'Ensembl',
          name: 'Ensembl',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'Ensembl Genomes',
          name: 'Ensembl_Genomes',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'Ensembl Genomes Protein',
          name: 'Ensembl_Genomes_Protein',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'Ensembl Genomes Transcript',
          name: 'Ensembl_Genomes_Transcript',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'Ensembl Protein',
          name: 'Ensembl_Protein',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'Ensembl Transcript',
          name: 'Ensembl_Transcript',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'GeneDB',
          name: 'GeneDB',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'GeneID',
          name: 'GeneID',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'KEGG',
          name: 'KEGG',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'PATRIC',
          name: 'PATRIC',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'UCSC',
          name: 'UCSC',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'WBParaSite',
          name: 'WBParaSite',
          from: true,
          to: true,
          ruleId: 7,
        },
      ],
    },
    {
      groupName: 'Organism-specific databases',
      items: [
        {
          displayName: 'ArachnoServer',
          name: 'ArachnoServer',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'Araport',
          name: 'Araport',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'CGD',
          name: 'CGD',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'ConoServer',
          name: 'ConoServer',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'dictyBase',
          name: 'dictyBase',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'EchoBASE',
          name: 'EchoBASE',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'euHCVdb',
          name: 'euHCVdb',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'FlyBase',
          name: 'FlyBase',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'GeneCards',
          name: 'GeneCards',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'GeneReviews',
          name: 'GeneReviews',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'HGNC',
          name: 'HGNC',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'LegioList',
          name: 'LegioList',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'Leproma',
          name: 'Leproma',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'MaizeGDB',
          name: 'MaizeGDB',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'MGI',
          name: 'MGI',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'MIM',
          name: 'MIM',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'neXtProt',
          name: 'neXtProt',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'Orphanet',
          name: 'Orphanet',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'PharmGKB',
          name: 'PharmGKB',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'PomBase',
          name: 'PomBase',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'PseudoCAP',
          name: 'PseudoCAP',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'RGD',
          name: 'RGD',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'SGD',
          name: 'SGD',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'TubercuList',
          name: 'TubercuList',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'VEuPathDB',
          name: 'VEuPathDB',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'VGNC',
          name: 'VGNC',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'WormBase',
          name: 'WormBase',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'WormBase Protein',
          name: 'WormBase_Protein',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'WormBase Transcript',
          name: 'WormBase_Transcript',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'Xenbase',
          name: 'Xenbase',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'ZFIN',
          name: 'ZFIN',
          from: true,
          to: true,
          ruleId: 7,
        },
      ],
    },
    {
      groupName: 'Phylogenomic databases',
      items: [
        {
          displayName: 'eggNOG',
          name: 'eggNOG',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'GeneTree',
          name: 'GeneTree',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'HOGENOM',
          name: 'HOGENOM',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'OMA',
          name: 'OMA',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'OrthoDB',
          name: 'OrthoDB',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'TreeFam',
          name: 'TreeFam',
          from: true,
          to: true,
          ruleId: 7,
        },
      ],
    },
    {
      groupName: 'Enzyme and pathway databases',
      items: [
        {
          displayName: 'BioCyc',
          name: 'BioCyc',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'PlantReactome',
          name: 'PlantReactome',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'Reactome',
          name: 'Reactome',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'UniPathway',
          name: 'UniPathway',
          from: true,
          to: true,
          ruleId: 7,
        },
      ],
    },
    {
      groupName: 'Miscellaneous',
      items: [
        {
          displayName: 'ChiTaRS',
          name: 'ChiTaRS',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'GeneWiki',
          name: 'GeneWiki',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'GenomeRNAi',
          name: 'GenomeRNAi',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'PHI-base',
          name: 'PHI-base',
          from: true,
          to: true,
          ruleId: 7,
        },
      ],
    },
    {
      groupName: 'Gene expression databases',
      items: [
        {
          displayName: 'CollecTF',
          name: 'CollecTF',
          from: true,
          to: true,
          ruleId: 7,
        },
      ],
    },
    {
      groupName: 'Family and domain databases',
      items: [
        {
          displayName: 'DisProt',
          name: 'DisProt',
          from: true,
          to: true,
          ruleId: 7,
        },
        {
          displayName: 'IDEAL',
          name: 'IDEAL',
          from: true,
          to: true,
          ruleId: 7,
        },
      ],
    },
  ],
  rules: [
    {
      ruleId: 1,
      tos: [
        'CCDS',
        'PIR',
        'RefSeq',
        'PDB',
        'BioGRID',
        'ComplexPortal',
        'DIP',
        'STRING',
        'ChEMBL',
        'DrugBank',
        'GuidetoPHARMACOLOGY',
        'SwissLipids',
        'Allergome',
        'ESTHER',
        'MEROPS',
        'CLAE',
        'PeroxiBase',
        'REBASE',
        'TCDB',
        'GlyConnect',
        'BioMuta',
        'DMDM',
        'World-2DPAGE',
        'CPTAC',
        'ProteomicsDB',
        'DNASU',
        'Ensembl',
        'GeneDB',
        'GeneID',
        'KEGG',
        'PATRIC',
        'UCSC',
        'WBParaSite',
        'ArachnoServer',
        'Araport',
        'CGD',
        'ConoServer',
        'dictyBase',
        'EchoBASE',
        'euHCVdb',
        'VEuPathDB',
        'FlyBase',
        'GeneCards',
        'GeneReviews',
        'HGNC',
        'LegioList',
        'Leproma',
        'MaizeGDB',
        'MGI',
        'MIM',
        'neXtProt',
        'Orphanet',
        'PharmGKB',
        'PomBase',
        'PseudoCAP',
        'RGD',
        'SGD',
        'TubercuList',
        'VGNC',
        'WormBase',
        'Xenbase',
        'ZFIN',
        'eggNOG',
        'GeneTree',
        'HOGENOM',
        'OMA',
        'OrthoDB',
        'TreeFam',
        'BioCyc',
        'Reactome',
        'UniPathway',
        'PlantReactome',
        'ChiTaRS',
        'GeneWiki',
        'GenomeRNAi',
        'PHI-base',
        'CollecTF',
        'IDEAL',
        'DisProt',
        'UniProtKB',
        'UniProtKB-Swiss-Prot',
        'UniParc',
        'UniRef50',
        'UniRef90',
        'UniRef100',
        'Gene_Name',
        'CRC64',
        'EMBL-GenBank-DDBJ',
        'EMBL-GenBank-DDBJ_CDS',
        'Ensembl_Protein',
        'Ensembl_Transcript',
        'Ensembl_Genomes',
        'Ensembl_Genomes_Protein',
        'Ensembl_Genomes_Transcript',
        'WormBase_Protein',
        'WormBase_Transcript',
      ],
      defaultTo: 'UniProtKB',
      taxonId: false,
    },
    {
      ruleId: 2,
      tos: ['UniProtKB', 'UniProtKB-Swiss-Prot', 'UniParc'],
      defaultTo: 'UniProtKB',
      taxonId: false,
    },
    {
      ruleId: 3,
      tos: ['UniProtKB', 'UniProtKB-Swiss-Prot', 'UniRef50'],
      defaultTo: 'UniProtKB',
      taxonId: false,
    },
    {
      ruleId: 4,
      tos: ['UniProtKB', 'UniProtKB-Swiss-Prot', 'UniRef90'],
      defaultTo: 'UniProtKB',
      taxonId: false,
    },
    {
      ruleId: 5,
      tos: ['UniProtKB', 'UniProtKB-Swiss-Prot', 'UniRef100'],
      defaultTo: 'UniProtKB',
      taxonId: false,
    },
    {
      ruleId: 6,
      tos: ['UniProtKB', 'UniProtKB-Swiss-Prot'],
      defaultTo: 'UniProtKB',
      taxonId: true,
    },
    {
      ruleId: 7,
      tos: ['UniProtKB', 'UniProtKB-Swiss-Prot'],
      defaultTo: 'UniProtKB',
      taxonId: false,
    },
  ],
};

export default data;
