import { AGRRibbonCategory } from '../../GORibbonHandler';

const goRibbonCategories: AGRRibbonCategory[] = [
  {
    id: 'GO:1234',
    description: '',
    label: 'cellular_component',
    groups: [
      {
        id: 'GO:0005576',
        label: 'extracellular region',
        description: '',
        type: 'Term',
      },
      { id: 'GO:0005634', label: 'nucleus', description: '', type: 'Term' },
      { id: 'GO:0005694', label: 'chromosome', description: '', type: 'Term' },
      {
        id: 'GO:0005739',
        label: 'mitochondrion',
        description: '',
        type: 'Term',
      },
      { id: 'GO:0005768', label: 'endosome', description: '', type: 'Term' },
      { id: 'GO:0005773', label: 'vacuole', description: '', type: 'Term' },
      {
        id: 'GO:0005783',
        label: 'endoplasmic reticulum',
        description: '',
        type: 'Term',
      },
      {
        id: 'GO:0005794',
        label: 'Golgi apparatus',
        description: '',
        type: 'Term',
      },
      { id: 'GO:0005829', label: 'cytosol', description: '', type: 'Term' },
      {
        id: 'GO:0005856',
        label: 'cytoskeleton',
        description: '',
        type: 'Term',
      },
      {
        id: 'GO:0005886',
        label: 'plasma membrane',
        description: '',
        type: 'Term',
      },
      {
        id: 'GO:0030054',
        label: 'cell junction',
        description: '',
        type: 'Term',
      },
      {
        id: 'GO:0031410',
        label: 'cytoplasmic vesicle',
        description: '',
        type: 'Term',
      },
      {
        id: 'GO:0032991',
        label: 'protein-containing complex',
        description: '',
        type: 'Term',
      },
      {
        id: 'GO:0042995',
        label: 'cell projection',
        description: '',
        type: 'Term',
      },
      { id: 'GO:0045202', label: 'synapse', description: '', type: 'Term' },
    ],
  },
  {
    id: 'GO:1234',
    description: '',
    label: 'molecular_function',
    groups: [
      { id: 'GO:0003677', label: 'DNA binding', description: '', type: 'Term' },
      {
        id: 'GO:0003700',
        label: 'DNA-binding transcription factor activity',
        description: '',
        type: 'Term',
      },
      { id: 'GO:0003723', label: 'RNA binding', description: '', type: 'Term' },
      {
        id: 'GO:0003824',
        label: 'catalytic activity',
        description: '',
        type: 'Term',
      },
      {
        id: 'GO:0005102',
        label: 'signaling receptor binding',
        description: '',
        type: 'Term',
      },
      {
        id: 'GO:0005198',
        label: 'structural molecule activity',
        description: '',
        type: 'Term',
      },
      {
        id: 'GO:0005215',
        label: 'transporter activity',
        description: '',
        type: 'Term',
      },
      {
        id: 'GO:0008092',
        label: 'cytoskeletal protein binding',
        description: '',
        type: 'Term',
      },
      {
        id: 'GO:0008134',
        label: 'transcription factor binding',
        description: '',
        type: 'Term',
      },
      {
        id: 'GO:0008289',
        label: 'lipid binding',
        description: '',
        type: 'Term',
      },
      {
        id: 'GO:0030234',
        label: 'enzyme regulator activity',
        description: '',
        type: 'Term',
      },
      {
        id: 'GO:0030246',
        label: 'carbohydrate binding',
        description: '',
        type: 'Term',
      },
      {
        id: 'GO:0036094',
        label: 'small molecule binding',
        description: '',
        type: 'Term',
      },
      {
        id: 'GO:0038023',
        label: 'signaling receptor activity',
        description: '',
        type: 'Term',
      },
      {
        id: 'GO:0046872',
        label: 'metal ion binding',
        description: '',
        type: 'Term',
      },
      {
        id: 'GO:0097367',
        label: 'carbohydrate derivative binding',
        description: '',
        type: 'Term',
      },
    ],
  },
  {
    id: 'GO:1234',
    description: '',
    label: 'biological_process',
    groups: [
      {
        id: 'GO:0000003',
        label: 'reproduction',
        description: '',
        type: 'Term',
      },
      {
        id: 'GO:0002376',
        label: 'immune system process',
        description: '',
        type: 'Term',
      },
      {
        id: 'GO:0005975',
        label: 'carbohydrate metabolic process',
        description: '',
        type: 'Term',
      },
      {
        id: 'GO:0006259',
        label: 'DNA metabolic process',
        description: '',
        type: 'Term',
      },
      {
        id: 'GO:0006629',
        label: 'lipid metabolic process',
        description: '',
        type: 'Term',
      },
      { id: 'GO:0007049', label: 'cell cycle', description: '', type: 'Term' },
      { id: 'GO:0007610', label: 'behavior', description: '', type: 'Term' },
      { id: 'GO:0008219', label: 'cell death', description: '', type: 'Term' },
      {
        id: 'GO:0008283',
        label: 'cell population proliferation',
        description: '',
        type: 'Term',
      },
      {
        id: 'GO:0009056',
        label: 'catabolic process',
        description: '',
        type: 'Term',
      },
      {
        id: 'GO:0016043',
        label: 'cellular component organization',
        description: '',
        type: 'Term',
      },
      {
        id: 'GO:0016070',
        label: 'RNA metabolic process',
        description: '',
        type: 'Term',
      },
      {
        id: 'GO:0019538',
        label: 'protein metabolic process',
        description: '',
        type: 'Term',
      },
      { id: 'GO:0023052', label: 'signaling', description: '', type: 'Term' },
      {
        id: 'GO:0030154',
        label: 'cell differentiation',
        description: '',
        type: 'Term',
      },
      {
        id: 'GO:0032502',
        label: 'developmental process',
        description: '',
        type: 'Term',
      },
      {
        id: 'GO:0042592',
        label: 'homeostatic process',
        description: '',
        type: 'Term',
      },
      {
        id: 'GO:0050877',
        label: 'nervous system process',
        description: '',
        type: 'Term',
      },
      {
        id: 'GO:0050896',
        label: 'response to stimulus',
        description: '',
        type: 'Term',
      },
      {
        id: 'GO:0051234',
        label: 'establishment of localization',
        description: '',
        type: 'Term',
      },
      {
        id: 'GO:1901135',
        label: 'carbohydrate derivative metabolic process',
        description: '',
        type: 'Term',
      },
    ],
  },
];

export default goRibbonCategories;
