import { SlimSet } from '../../GORibbonHandler';

const goSlimAGR: SlimSet = {
  name: 'goslim_agr',
  id: 'goslim_agr',
  associations: [
    {
      associations: null,
      name: 'extracellular region',
      id: 'GO:0005576',
      aspect: 'cellular_component',
    },
    {
      associations: null,
      name: 'nucleus',
      id: 'GO:0005634',
      aspect: 'cellular_component',
    },
    {
      associations: null,
      name: 'chromosome',
      id: 'GO:0005694',
      aspect: 'cellular_component',
    },
    {
      associations: null,
      name: 'mitochondrion',
      id: 'GO:0005739',
      aspect: 'cellular_component',
    },
    {
      associations: null,
      name: 'endosome',
      id: 'GO:0005768',
      aspect: 'cellular_component',
    },
    {
      associations: null,
      name: 'vacuole',
      id: 'GO:0005773',
      aspect: 'cellular_component',
    },
    {
      associations: null,
      name: 'endoplasmic reticulum',
      id: 'GO:0005783',
      aspect: 'cellular_component',
    },
    {
      associations: null,
      name: 'Golgi apparatus',
      id: 'GO:0005794',
      aspect: 'cellular_component',
    },
    {
      associations: null,
      name: 'cytosol',
      id: 'GO:0005829',
      aspect: 'cellular_component',
    },
    {
      associations: null,
      name: 'cytoskeleton',
      id: 'GO:0005856',
      aspect: 'cellular_component',
    },
    {
      associations: null,
      name: 'plasma membrane',
      id: 'GO:0005886',
      aspect: 'cellular_component',
    },
    {
      associations: null,
      name: 'cell junction',
      id: 'GO:0030054',
      aspect: 'cellular_component',
    },
    {
      associations: null,
      name: 'cytoplasmic vesicle',
      id: 'GO:0031410',
      aspect: 'cellular_component',
    },
    {
      associations: null,
      name: 'protein-containing complex',
      id: 'GO:0032991',
      aspect: 'cellular_component',
    },
    {
      associations: null,
      name: 'cell projection',
      id: 'GO:0042995',
      aspect: 'cellular_component',
    },
    {
      associations: null,
      name: 'synapse',
      id: 'GO:0045202',
      aspect: 'cellular_component',
    },
    {
      associations: null,
      name: 'DNA binding',
      id: 'GO:0003677',
      aspect: 'molecular_function',
    },
    {
      associations: null,
      name: 'DNA-binding transcription factor activity',
      id: 'GO:0003700',
      aspect: 'molecular_function',
    },
    {
      associations: null,
      name: 'RNA binding',
      id: 'GO:0003723',
      aspect: 'molecular_function',
    },
    {
      associations: null,
      name: 'catalytic activity',
      id: 'GO:0003824',
      aspect: 'molecular_function',
    },
    {
      associations: null,
      name: 'signaling receptor binding',
      id: 'GO:0005102',
      aspect: 'molecular_function',
    },
    {
      associations: null,
      name: 'structural molecule activity',
      id: 'GO:0005198',
      aspect: 'molecular_function',
    },
    {
      associations: null,
      name: 'transporter activity',
      id: 'GO:0005215',
      aspect: 'molecular_function',
    },
    {
      associations: null,
      name: 'cytoskeletal protein binding',
      id: 'GO:0008092',
      aspect: 'molecular_function',
    },
    {
      associations: null,
      name: 'transcription factor binding',
      id: 'GO:0008134',
      aspect: 'molecular_function',
    },
    {
      associations: null,
      name: 'lipid binding',
      id: 'GO:0008289',
      aspect: 'molecular_function',
    },
    {
      associations: null,
      name: 'enzyme regulator activity',
      id: 'GO:0030234',
      aspect: 'molecular_function',
    },
    {
      associations: null,
      name: 'carbohydrate binding',
      id: 'GO:0030246',
      aspect: 'molecular_function',
    },
    {
      associations: null,
      name: 'small molecule binding',
      id: 'GO:0036094',
      aspect: 'molecular_function',
    },
    {
      associations: null,
      name: 'signaling receptor activity',
      id: 'GO:0038023',
      aspect: 'molecular_function',
    },
    {
      associations: null,
      name: 'metal ion binding',
      id: 'GO:0046872',
      aspect: 'molecular_function',
    },
    {
      associations: null,
      name: 'carbohydrate derivative binding',
      id: 'GO:0097367',
      aspect: 'molecular_function',
    },
    {
      associations: null,
      name: 'reproduction',
      id: 'GO:0000003',
      aspect: 'biological_process',
    },
    {
      associations: null,
      name: 'immune system process',
      id: 'GO:0002376',
      aspect: 'biological_process',
    },
    {
      associations: null,
      name: 'carbohydrate metabolic process',
      id: 'GO:0005975',
      aspect: 'biological_process',
    },
    {
      associations: null,
      name: 'DNA metabolic process',
      id: 'GO:0006259',
      aspect: 'biological_process',
    },
    {
      associations: null,
      name: 'lipid metabolic process',
      id: 'GO:0006629',
      aspect: 'biological_process',
    },
    {
      associations: null,
      name: 'cell cycle',
      id: 'GO:0007049',
      aspect: 'biological_process',
    },
    {
      associations: null,
      name: 'behavior',
      id: 'GO:0007610',
      aspect: 'biological_process',
    },
    {
      associations: null,
      name: 'cell death',
      id: 'GO:0008219',
      aspect: 'biological_process',
    },
    {
      associations: null,
      name: 'cell population proliferation',
      id: 'GO:0008283',
      aspect: 'biological_process',
    },
    {
      associations: null,
      name: 'catabolic process',
      id: 'GO:0009056',
      aspect: 'biological_process',
    },
    {
      associations: null,
      name: 'cellular component organization',
      id: 'GO:0016043',
      aspect: 'biological_process',
    },
    {
      associations: null,
      name: 'RNA metabolic process',
      id: 'GO:0016070',
      aspect: 'biological_process',
    },
    {
      associations: null,
      name: 'protein metabolic process',
      id: 'GO:0019538',
      aspect: 'biological_process',
    },
    {
      associations: null,
      name: 'signaling',
      id: 'GO:0023052',
      aspect: 'biological_process',
    },
    {
      associations: null,
      name: 'cell differentiation',
      id: 'GO:0030154',
      aspect: 'biological_process',
    },
    {
      associations: null,
      name: 'developmental process',
      id: 'GO:0032502',
      aspect: 'biological_process',
    },
    {
      associations: null,
      name: 'homeostatic process',
      id: 'GO:0042592',
      aspect: 'biological_process',
    },
    {
      associations: null,
      name: 'nervous system process',
      id: 'GO:0050877',
      aspect: 'biological_process',
    },
    {
      associations: null,
      name: 'response to stimulus',
      id: 'GO:0050896',
      aspect: 'biological_process',
    },
    {
      associations: null,
      name: 'establishment of localization',
      id: 'GO:0051234',
      aspect: 'biological_process',
    },
    {
      associations: null,
      name: 'carbohydrate derivative metabolic process',
      id: 'GO:1901135',
      aspect: 'biological_process',
    },
  ],
};

export default goSlimAGR;
