import { SearchResults } from '../../../shared/types/results';
import { TaxonomyAPIModel } from '../adapters/taxonomyConverter';

// Source: taxonomy/search?size=2&query=primate
// Retrieved: 2025-06-13
const mock: SearchResults<TaxonomyAPIModel> = {
  results: [
    {
      scientificName: 'Primate lentivirus group',
      taxonId: 11652,
      mnemonic: '9PLVG',
      parent: {
        scientificName: 'Lentivirus',
        taxonId: 11646,
      },
      rank: 'clade',
      hidden: false,
      active: true,
      otherNames: ['Primate immunodeficiency viruses'],
      lineage: [
        {
          scientificName: 'Viruses',
          taxonId: 10239,
          rank: 'no rank',
          hidden: false,
        },
        {
          scientificName: 'Riboviria',
          commonName: 'RNA viruses and retroviruses',
          taxonId: 2559587,
          rank: 'realm',
          hidden: false,
        },
        {
          scientificName: 'Pararnavirae',
          taxonId: 2732397,
          rank: 'kingdom',
          hidden: false,
        },
        {
          scientificName: 'Artverviricota',
          taxonId: 2732409,
          rank: 'phylum',
          hidden: false,
        },
        {
          scientificName: 'Revtraviricetes',
          taxonId: 2732514,
          rank: 'class',
          hidden: false,
        },
        {
          scientificName: 'Ortervirales',
          taxonId: 2169561,
          rank: 'order',
          hidden: false,
        },
        {
          scientificName: 'Retroviridae',
          taxonId: 11632,
          rank: 'family',
          hidden: false,
        },
        {
          scientificName: 'Orthoretrovirinae',
          taxonId: 327045,
          rank: 'subfamily',
          hidden: false,
        },
        {
          scientificName: 'Lentivirus',
          taxonId: 11646,
          rank: 'genus',
          hidden: false,
        },
      ],
      statistics: {
        reviewedProteinCount: 0,
        unreviewedProteinCount: 36491,
        referenceProteomeCount: 0,
        proteomeCount: 0,
      },
    },
    {
      scientificName: 'Pediculidae',
      commonName: 'body lice',
      taxonId: 121221,
      mnemonic: '9NEOP',
      parent: {
        scientificName: 'Anoplura',
        commonName: 'sucking lice',
        taxonId: 30005,
      },
      rank: 'family',
      hidden: false,
      active: true,
      otherNames: ['primate body lice'],
      lineage: [
        {
          scientificName: 'cellular organisms',
          taxonId: 131567,
          rank: 'no rank',
          hidden: true,
        },
        {
          scientificName: 'Eukaryota',
          commonName: 'eucaryotes',
          taxonId: 2759,
          rank: 'domain',
          hidden: false,
        },
        {
          scientificName: 'Opisthokonta',
          taxonId: 33154,
          rank: 'clade',
          hidden: true,
        },
        {
          scientificName: 'Metazoa',
          commonName: 'metazoans',
          taxonId: 33208,
          rank: 'kingdom',
          hidden: false,
        },
        {
          scientificName: 'Eumetazoa',
          taxonId: 6072,
          rank: 'clade',
          hidden: true,
        },
        {
          scientificName: 'Bilateria',
          taxonId: 33213,
          rank: 'clade',
          hidden: true,
        },
        {
          scientificName: 'Protostomia',
          taxonId: 33317,
          rank: 'clade',
          hidden: true,
        },
        {
          scientificName: 'Ecdysozoa',
          taxonId: 1206794,
          rank: 'clade',
          hidden: false,
        },
        {
          scientificName: 'Panarthropoda',
          taxonId: 88770,
          rank: 'clade',
          hidden: true,
        },
        {
          scientificName: 'Arthropoda',
          commonName: 'arthropods',
          taxonId: 6656,
          rank: 'phylum',
          hidden: false,
        },
        {
          scientificName: 'Mandibulata',
          taxonId: 197563,
          rank: 'clade',
          hidden: true,
        },
        {
          scientificName: 'Pancrustacea',
          taxonId: 197562,
          rank: 'clade',
          hidden: true,
        },
        {
          scientificName: 'Hexapoda',
          commonName: 'hexapods',
          taxonId: 6960,
          rank: 'subphylum',
          hidden: false,
        },
        {
          scientificName: 'Insecta',
          commonName: 'insects',
          taxonId: 50557,
          rank: 'class',
          hidden: false,
        },
        {
          scientificName: 'Dicondylia',
          taxonId: 85512,
          rank: 'clade',
          hidden: true,
        },
        {
          scientificName: 'Pterygota',
          commonName: 'winged insects',
          taxonId: 7496,
          rank: 'subclass',
          hidden: false,
        },
        {
          scientificName: 'Neoptera',
          taxonId: 33340,
          rank: 'infraclass',
          hidden: false,
        },
        {
          scientificName: 'Paraneoptera',
          taxonId: 33342,
          rank: 'cohort',
          hidden: false,
        },
        {
          scientificName: 'Psocodea',
          taxonId: 1930602,
          rank: 'superorder',
          hidden: false,
        },
        {
          scientificName: 'Phthiraptera',
          commonName: 'lice',
          taxonId: 85819,
          rank: 'order',
          hidden: false,
        },
        {
          scientificName: 'Anoplura',
          commonName: 'sucking lice',
          taxonId: 30005,
          rank: 'suborder',
          hidden: false,
        },
      ],
      statistics: {
        reviewedProteinCount: 10,
        unreviewedProteinCount: 11610,
        referenceProteomeCount: 0,
        proteomeCount: 0,
      },
    },
  ],
};
export default mock.results;
