import { TaxonomyAPIModel } from '../adapters/taxonomyConverter';

// Data from /api/taxonomy/search?size=2&query=primate
const mock: TaxonomyAPIModel[] = [
  {
    scientificName: 'Primate lentivirus group',
    taxonId: 11652,
    mnemonic: '9PLVG',
    parentId: 11646,
    rank: 'no rank',
    hidden: false,
    active: true,
    otherNames: ['Primate immunodeficiency viruses'],
    lineage: [
      {
        scientificName: 'Lentivirus',
        commonName: ' ',
        taxonId: 11646,
        rank: 'genus',
        hidden: false,
      },
      {
        scientificName: 'Orthoretrovirinae',
        commonName: ' ',
        taxonId: 327045,
        rank: 'subfamily',
        hidden: false,
      },
      {
        scientificName: 'Retroviridae',
        commonName: ' ',
        taxonId: 11632,
        rank: 'family',
        hidden: false,
      },
      {
        scientificName: 'Ortervirales',
        commonName: ' ',
        taxonId: 2169561,
        rank: 'order',
        hidden: false,
      },
      {
        scientificName: 'Revtraviricetes',
        commonName: ' ',
        taxonId: 2732514,
        rank: 'class',
        hidden: false,
      },
      {
        scientificName: 'Artverviricota',
        commonName: ' ',
        taxonId: 2732409,
        rank: 'phylum',
        hidden: false,
      },
      {
        scientificName: 'Pararnavirae',
        commonName: ' ',
        taxonId: 2732397,
        rank: 'kingdom',
        hidden: false,
      },
      {
        scientificName: 'Riboviria',
        commonName: ' ',
        taxonId: 2559587,
        rank: 'no rank',
        hidden: false,
      },
      {
        scientificName: 'Viruses',
        commonName: ' ',
        taxonId: 10239,
        rank: 'superkingdom',
        hidden: false,
      },
    ],
  },
  {
    scientificName: 'Primate calicivirus',
    taxonId: 37299,
    mnemonic: 'VESV',
    parentId: 35612,
    rank: 'no rank',
    hidden: true,
    active: true,
    lineage: [
      {
        scientificName: 'Vesicular exanthema of swine virus',
        commonName: 'VESV',
        taxonId: 35612,
        rank: 'species',
        hidden: true,
      },
      {
        scientificName: 'Vesivirus',
        commonName: ' ',
        taxonId: 95337,
        rank: 'genus',
        hidden: false,
      },
      {
        scientificName: 'Caliciviridae',
        commonName: ' ',
        taxonId: 11974,
        rank: 'family',
        hidden: false,
      },
      {
        scientificName: 'Picornavirales',
        commonName: ' ',
        taxonId: 464095,
        rank: 'order',
        hidden: false,
      },
      {
        scientificName: 'Pisoniviricetes',
        commonName: ' ',
        taxonId: 2732506,
        rank: 'class',
        hidden: false,
      },
      {
        scientificName: 'Pisuviricota',
        commonName: ' ',
        taxonId: 2732408,
        rank: 'phylum',
        hidden: false,
      },
      {
        scientificName: 'Orthornavirae',
        commonName: ' ',
        taxonId: 2732396,
        rank: 'kingdom',
        hidden: false,
      },
      {
        scientificName: 'Riboviria',
        commonName: ' ',
        taxonId: 2559587,
        rank: 'no rank',
        hidden: false,
      },
      {
        scientificName: 'Viruses',
        commonName: ' ',
        taxonId: 10239,
        rank: 'superkingdom',
        hidden: false,
      },
    ],
    statistics: {
      reviewedProteinCount: 0,
      unreviewedProteinCount: 3,
      referenceProteomeCount: 0,
      proteomeCount: 0,
    },
  },
];

export default mock;
