export enum ContentType {
  fasta = 'text/plain; format=fasta',
  tsv = 'text/plain; format=tsv',
  excel = 'application/vnd.ms-excel',
  xml = 'application/xml',
  rdfXml = 'application/rdf+xml',
  text = 'text/plain; format=flatfile',
  gff = 'text/plain; format=gff',
  list = 'text/plain; format=list',
  json = 'application/json',
  obo = 'text/plain; format=obo',
  embeddings = 'application/x-hdf5',
  peff = 'text/x-peff',
}

export enum FileFormat {
  fasta = 'FASTA',
  fastaCanonical = 'FASTA (canonical)',
  fastaCanonicalIsoform = 'FASTA (canonical & isoform)',
  fastaRepresentative = 'FASTA (representative)',
  fastaSubsequence = 'FASTA (subsequence)',
  tsv = 'TSV',
  tsvIdMappingFromTo = 'TSV (from/to only)',
  excel = 'Excel',
  excelIdMappingFromTo = 'Excel (from/to only)',
  xml = 'XML',
  rdfXml = 'RDF/XML',
  text = 'Text',
  gff = 'GFF',
  list = 'List',
  json = 'JSON',
  jsonIdMappingFromTo = 'JSON (from/to only)',
  obo = 'OBO',
  embeddings = 'Embeddings',
  peff = 'PEFF',
}
