import { SearchResults } from '../../../../../shared/types/results';
import { GeneCentricData } from '../../ComputationallyMappedSequences';

const data: SearchResults<GeneCentricData> = {
  results: [
    {
      proteomeId: 'UP000005640',
      canonicalProtein: {
        id: 'P05067',
        sequence: {
          value:
            'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVREVCSEQAETGPCRAMISRWYFDVTEGKCAPFFYGGCGGNRNNFDTEEYCMAVCGSAMSQSLLKTTQEPLARDPVKLPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEVEPVDARPAADRGLTTRPGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
          length: 770,
          molWeight: 86943,
          crc64: 'A12EE761403740F5',
          md5: '7DD43312CD29A262ACDC0517230BC5CA',
        },
        entryType: 'UniProtKB reviewed (Swiss-Prot)',
        uniProtkbId: 'A4_HUMAN',
        proteinName: 'Amyloid-beta precursor protein',
        organism: { scientificName: 'Homo sapiens', taxonId: 9606 },
        geneName: 'APP',
        proteinExistence: '1: Evidence at protein level',
        flagType: 'Precursor',
        sequenceVersion: 3,
      },
      relatedProteins: [
        {
          id: 'P05067-10',
          sequence: {
            value:
              'MLPGLALLLLAAWTARALEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVRVPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEVEPVDARPAADRGLTTRPGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
            length: 639,
            molWeight: 72553,
            crc64: 'C4120DEC51A59A95',
            md5: 'D04CDFB0E2E908743E7E53F43CA6D9F7',
          },
          entryType: 'UniProtKB reviewed (Swiss-Prot)',
          uniProtkbId: 'A4_HUMAN',
          proteinName: 'Isoform APP639 of Amyloid-beta precursor protein',
          organism: { scientificName: 'Homo sapiens', taxonId: 9606 },
          geneName: 'APP',
          flagType: 'Precursor',
        },
        {
          id: 'P05067-11',
          sequence: {
            value:
              'MDQLEDLLVLFINYVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVREVCSEQAETGPCRAMISRWYFDVTEGKCAPFFYGGCGGNRNNFDTEEYCMAVCGSAIPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEVEPVDARPAADRGLTTRPGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
            length: 746,
            molWeight: 84521,
            crc64: '843411EFBDEFACE3',
            md5: '04E00C8307ADE0838671AB52F9423932',
          },
          entryType: 'UniProtKB reviewed (Swiss-Prot)',
          uniProtkbId: 'A4_HUMAN',
          proteinName: 'Isoform 11 of Amyloid-beta precursor protein',
          organism: { scientificName: 'Homo sapiens', taxonId: 9606 },
          geneName: 'APP',
          flagType: 'Precursor',
        },
        {
          id: 'A0A0A0MRG2',
          sequence: {
            value:
              'MFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVRVPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEVEPVDARPAADRGLTTRPGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
            length: 660,
            molWeight: 75110,
            crc64: '7EC5DD46A8729202',
            md5: '972B5991CA413DEF0B995A7A30B1D000',
          },
          entryType: 'UniProtKB unreviewed (TrEMBL)',
          uniProtkbId: 'A0A0A0MRG2_HUMAN',
          proteinName: 'Amyloid-beta A4 protein',
          organism: { scientificName: 'Homo sapiens', taxonId: 9606 },
          geneName: 'APP',
          proteinExistence: '1: Evidence at protein level',
          flagType: 'Precursor',
          sequenceVersion: 1,
        },
        {
          id: 'H7C2L2',
          sequence: {
            value:
              'XGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVRVSQSLLKTTQEPLARDPVKLPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEA',
            length: 181,
            molWeight: 20378,
            crc64: 'F460F21223DF2838',
            md5: 'AA8E98E65D81B832A460C693363F7C90',
          },
          entryType: 'UniProtKB unreviewed (TrEMBL)',
          uniProtkbId: 'H7C2L2_HUMAN',
          proteinName: 'Amyloid-beta A4 protein',
          organism: { scientificName: 'Homo sapiens', taxonId: 9606 },
          geneName: 'APP',
          proteinExistence: '1: Evidence at protein level',
          flagType: 'Fragment',
          sequenceVersion: 1,
        },
        {
          id: 'H7C0V9',
          sequence: {
            value:
              'XLQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVREVCSEQAETGPCRAMISRWYFDVTEGKCAPFFYGGCGGNRNNFDTEEYCMAVCGSAIPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVGAVAHACNSSILGGQGGQMT',
            length: 485,
            molWeight: 55093,
            crc64: 'A7474F05C4C1B412',
            md5: 'DA84B50EB49263EC36DE7CB19F464D3D',
          },
          entryType: 'UniProtKB unreviewed (TrEMBL)',
          uniProtkbId: 'H7C0V9_HUMAN',
          proteinName: 'Amyloid-beta A4 protein',
          organism: { scientificName: 'Homo sapiens', taxonId: 9606 },
          geneName: 'APP',
          proteinExistence: '1: Evidence at protein level',
          flagType: 'Fragment',
          sequenceVersion: 1,
        },
        {
          id: 'E9PG40',
          sequence: {
            value:
              'MLPGLALLLLAAWTARALEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVREVCSEQAETGPCRAMISRWYFDVTEGKCAPFFYGGCGGNRNNFDTEEYCMAVCGSAMSQSLLKTTQEPLARDPVKLPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEVEPVDARPAADRGLTTRPGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
            length: 714,
            molWeight: 80833,
            crc64: '68CC52E6F29B777B',
            md5: '5FD622C9A68BB112740887CF5BB852AC',
          },
          entryType: 'UniProtKB unreviewed (TrEMBL)',
          uniProtkbId: 'E9PG40_HUMAN',
          proteinName: 'Amyloid-beta A4 protein',
          organism: { scientificName: 'Homo sapiens', taxonId: 9606 },
          geneName: 'APP',
          proteinExistence: '1: Evidence at protein level',
          flagType: 'Precursor',
          sequenceVersion: 1,
        },
        {
          id: 'P05067-2',
          sequence: {
            value:
              'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVREKWYKEVHSGQARWLML',
            length: 305,
            molWeight: 34358,
            crc64: 'D1CCD7237262687A',
            md5: '8048490F3431C1D74DA373E90A7D8D5B',
          },
          entryType: 'UniProtKB reviewed (Swiss-Prot)',
          uniProtkbId: 'A4_HUMAN',
          proteinName: 'Isoform APP305 of Amyloid-beta precursor protein',
          organism: { scientificName: 'Homo sapiens', taxonId: 9606 },
          geneName: 'APP',
          flagType: 'Precursor',
        },
        {
          id: 'P05067-3',
          sequence: {
            value:
              'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVRVPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
            length: 677,
            molWeight: 76760,
            crc64: '48334D3EEF26990E',
            md5: 'A338CD5CABF782539F4A55421B23A595',
          },
          entryType: 'UniProtKB reviewed (Swiss-Prot)',
          uniProtkbId: 'A4_HUMAN',
          proteinName: 'Isoform L-APP677 of Amyloid-beta precursor protein',
          organism: { scientificName: 'Homo sapiens', taxonId: 9606 },
          geneName: 'APP',
          flagType: 'Precursor',
        },
        {
          id: 'P05067-4',
          sequence: {
            value:
              'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVRVPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEVEPVDARPAADRGLTTRPGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
            length: 695,
            molWeight: 78663,
            crc64: '4F6EA0139F969D56',
            md5: 'BD089074F6C0866F6A1081DF3FBEB648',
          },
          entryType: 'UniProtKB reviewed (Swiss-Prot)',
          uniProtkbId: 'A4_HUMAN',
          proteinName: 'Isoform APP695 of Amyloid-beta precursor protein',
          organism: { scientificName: 'Homo sapiens', taxonId: 9606 },
          geneName: 'APP',
          flagType: 'Precursor',
        },
        {
          id: 'P05067-5',
          sequence: {
            value:
              'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVRVSQSLLKTTQEPLARDPVKLPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
            length: 696,
            molWeight: 78866,
            crc64: '66DFDFFCFDB75A72',
            md5: '94203A08AE85B6BB240F0941282243D6',
          },
          entryType: 'UniProtKB reviewed (Swiss-Prot)',
          uniProtkbId: 'A4_HUMAN',
          proteinName: 'Isoform L-APP696 of Amyloid-beta precursor protein',
          organism: { scientificName: 'Homo sapiens', taxonId: 9606 },
          geneName: 'APP',
          flagType: 'Precursor',
        },
        {
          id: 'P05067-6',
          sequence: {
            value:
              'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVRVSQSLLKTTQEPLARDPVKLPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEVEPVDARPAADRGLTTRPGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
            length: 714,
            molWeight: 80769,
            crc64: '124EA691773DC13B',
            md5: '8CA2189A8D89EC9502051E9DBDA6AF9D',
          },
          entryType: 'UniProtKB reviewed (Swiss-Prot)',
          uniProtkbId: 'A4_HUMAN',
          proteinName: 'Isoform APP714 of Amyloid-beta precursor protein',
          organism: { scientificName: 'Homo sapiens', taxonId: 9606 },
          geneName: 'APP',
          flagType: 'Precursor',
        },
        {
          id: 'P05067-7',
          sequence: {
            value:
              'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVREVCSEQAETGPCRAMISRWYFDVTEGKCAPFFYGGCGGNRNNFDTEEYCMAVCGSAIPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
            length: 733,
            molWeight: 82916,
            crc64: '44528239D68A53EE',
            md5: '93307E53EAA95B82664CC2BC9165B156',
          },
          entryType: 'UniProtKB reviewed (Swiss-Prot)',
          uniProtkbId: 'A4_HUMAN',
          proteinName: 'Isoform L-APP733 of Amyloid-beta precursor protein',
          organism: { scientificName: 'Homo sapiens', taxonId: 9606 },
          geneName: 'APP',
          flagType: 'Precursor',
        },
        {
          id: 'P05067-8',
          sequence: {
            value:
              'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVREVCSEQAETGPCRAMISRWYFDVTEGKCAPFFYGGCGGNRNNFDTEEYCMAVCGSAIPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEVEPVDARPAADRGLTTRPGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
            length: 751,
            molWeight: 84819,
            crc64: 'C987C557C5A3714E',
            md5: 'A83D724FA6C8F6A50993DB360949D528',
          },
          entryType: 'UniProtKB reviewed (Swiss-Prot)',
          uniProtkbId: 'A4_HUMAN',
          proteinName: 'Isoform APP751 of Amyloid-beta precursor protein',
          organism: { scientificName: 'Homo sapiens', taxonId: 9606 },
          geneName: 'APP',
          flagType: 'Precursor',
        },
        {
          id: 'P05067-9',
          sequence: {
            value:
              'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVREVCSEQAETGPCRAMISRWYFDVTEGKCAPFFYGGCGGNRNNFDTEEYCMAVCGSAMSQSLLKTTQEPLARDPVKLPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
            length: 752,
            molWeight: 85040,
            crc64: '074CFF767CBED2E0',
            md5: '7D77A2EC2E85AF64D225E470989571D2',
          },
          entryType: 'UniProtKB reviewed (Swiss-Prot)',
          uniProtkbId: 'A4_HUMAN',
          proteinName: 'Isoform L-APP752 of Amyloid-beta precursor protein',
          organism: { scientificName: 'Homo sapiens', taxonId: 9606 },
          geneName: 'APP',
          flagType: 'Precursor',
        },
      ],
    },
  ],
};

export default data;
