import { UniRefLiteAPIModel } from '../../../../../uniref/adapters/uniRefConverter';

const mock: UniRefLiteAPIModel[] = [
  {
    id: 'UniRef50_P05067',
    name: 'Cluster: Amyloid-beta precursor protein',
    updated: '2021-02-10',
    entryType: 'UniRef50',
    commonTaxon: { scientificName: 'cellular organisms', taxonId: 131567 },
    memberCount: 1538,
    organismCount: 454,
    representativeMember: {
      memberIdType: 'UniProtKB ID',
      memberId: 'A4_HUMAN',
      organismName: 'Homo sapiens (Human)',
      organismTaxId: 9606,
      sequenceLength: 770,
      proteinName: 'Amyloid-beta precursor protein',
      accessions: [
        'P05067',
        'B2R5V1',
        'B4DII8',
        'D3DSD1',
        'D3DSD2',
        'D3DSD3',
        'P09000',
        'P78438',
        'Q13764',
        'Q13778',
        'Q13793',
        'Q16011',
        'Q16014',
        'Q16019',
        'Q16020',
        'Q6GSC0',
        'Q8WZ99',
        'Q9BT38',
        'Q9UC33',
        'Q9UCA9',
        'Q9UCB6',
        'Q9UCC8',
        'Q9UCD1',
        'Q9UQ58',
      ],
      uniref90Id: 'UniRef90_P05067',
      uniref100Id: 'UniRef100_P05067',
      uniparcId: { value: 'UPI000002DB1C' },
      sequence: {
        value:
          'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVREVCSEQAETGPCRAMISRWYFDVTEGKCAPFFYGGCGGNRNNFDTEEYCMAVCGSAMSQSLLKTTQEPLARDPVKLPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEVEPVDARPAADRGLTTRPGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
        length: 770,
        molWeight: 86943,
        crc64: 'A12EE761403740F5',
        md5: '7DD43312CD29A262ACDC0517230BC5CA',
      },
    },
    seedId: 'UPI001386A8D7',
    memberIdTypes: [
      'UniProtKB Unreviewed (TrEMBL)',
      'UniProtKB Reviewed (Swiss-Prot)',
      'UniParc',
    ],
    members: [
      'P05067',
      'P12023',
      'Q5IS80',
      'P08592',
      'P79307',
      'Q28053',
      'Q28748',
      'Q28757',
      'Q28280',
      'Q29149',
    ],
    organisms: [
      { scientificName: 'Homo sapiens', commonName: 'Human', taxonId: 9606 },
      { scientificName: 'Mus musculus', commonName: 'Mouse', taxonId: 10090 },
      {
        scientificName: 'Pan troglodytes',
        commonName: 'Chimpanzee',
        taxonId: 9598,
      },
      {
        scientificName: 'Rattus norvegicus',
        commonName: 'Rat',
        taxonId: 10116,
      },
      { scientificName: 'Sus scrofa', commonName: 'Pig', taxonId: 9823 },
      { scientificName: 'Bos taurus', commonName: 'Bovine', taxonId: 9913 },
      {
        scientificName: 'Oryctolagus cuniculus',
        commonName: 'Rabbit',
        taxonId: 9986,
      },
      { scientificName: 'Ovis aries', commonName: 'Sheep', taxonId: 9940 },
      {
        scientificName: 'Canis lupus familiaris',
        commonName: 'Dog',
        taxonId: 9615,
      },
      {
        scientificName: 'Ursus maritimus',
        commonName: 'Polar bear',
        taxonId: 29073,
      },
    ],
  },
  {
    id: 'UniRef90_P05067-8',
    name: 'Cluster: Isoform APP751 of Amyloid-beta precursor protein',
    updated: '2021-02-10',
    entryType: 'UniRef90',
    commonTaxon: { scientificName: 'Amniota', taxonId: 32524 },
    memberCount: 334,
    organismCount: 181,
    representativeMember: {
      memberIdType: 'UniProtKB ID',
      memberId: 'P05067-8',
      organismName: 'Homo sapiens (Human)',
      organismTaxId: 9606,
      sequenceLength: 751,
      proteinName: 'Isoform APP751 of Amyloid-beta precursor protein',
      accessions: ['P05067-8'],
      uniref50Id: 'UniRef50_P05067',
      uniref100Id: 'UniRef100_P05067-8',
      uniparcId: { value: 'UPI000002A2F6' },
      sequence: {
        value:
          'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVREVCSEQAETGPCRAMISRWYFDVTEGKCAPFFYGGCGGNRNNFDTEEYCMAVCGSAIPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEVEPVDARPAADRGLTTRPGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
        length: 751,
        molWeight: 84819,
        crc64: 'C987C557C5A3714E',
        md5: 'A83D724FA6C8F6A50993DB360949D528',
      },
    },
    seedId: 'UPI0011CED4DA',
    memberIdTypes: [
      'UniProtKB Reviewed (Swiss-Prot)',
      'UniProtKB Unreviewed (TrEMBL)',
      'UniParc',
    ],
    members: [
      'P05067-8',
      'Q95241',
      'A0A672TXQ3',
      'Q8JH58',
      'A0A3Q7Y752',
      'A0A1S3GCQ5',
      'A0A6P3DZE3',
      'A0A2U3WVB5',
      'A0A2K5JT40',
      'A0A671EIH7',
    ],
    organisms: [
      { scientificName: 'Homo sapiens', commonName: 'Human', taxonId: 9606 },
      {
        scientificName: 'Saimiri sciureus',
        commonName: 'Common squirrel monkey',
        taxonId: 9521,
      },
      {
        scientificName: 'Strigops habroptila',
        commonName: 'Kakapo',
        taxonId: 2489341,
      },
      {
        scientificName: 'Chelydra serpentina',
        commonName: 'Snapping turtle',
        taxonId: 8475,
      },
      { scientificName: 'Ursus arctos horribilis', taxonId: 116960 },
      {
        scientificName: 'Dipodomys ordii',
        commonName: "Ord's kangaroo rat",
        taxonId: 10020,
      },
      { scientificName: 'Ovis aries', commonName: 'Sheep', taxonId: 9940 },
      {
        scientificName: 'Odobenus rosmarus divergens',
        commonName: 'Pacific walrus',
        taxonId: 9708,
      },
      {
        scientificName: 'Colobus angolensis palliatus',
        commonName: "Peters' Angolan colobus",
        taxonId: 336983,
      },
      {
        scientificName: 'Rhinolophus ferrumequinum',
        commonName: 'Greater horseshoe bat',
        taxonId: 59479,
      },
    ],
  },
  {
    id: 'UniRef90_P05067-5',
    name: 'Cluster: Isoform L-APP696 of Amyloid-beta precursor protein',
    updated: '2021-02-10',
    entryType: 'UniRef90',
    commonTaxon: { scientificName: 'Boreoeutheria', taxonId: 1437010 },
    memberCount: 15,
    organismCount: 12,
    representativeMember: {
      memberIdType: 'UniProtKB ID',
      memberId: 'P05067-5',
      organismName: 'Homo sapiens (Human)',
      organismTaxId: 9606,
      sequenceLength: 696,
      proteinName: 'Isoform L-APP696 of Amyloid-beta precursor protein',
      accessions: ['P05067-5'],
      uniref50Id: 'UniRef50_P05067',
      uniref100Id: 'UniRef100_P05067-5',
      uniparcId: { value: 'UPI000002A2F3' },
      sequence: {
        value:
          'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVRVSQSLLKTTQEPLARDPVKLPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
        length: 696,
        molWeight: 78866,
        crc64: '66DFDFFCFDB75A72',
        md5: '94203A08AE85B6BB240F0941282243D6',
      },
    },
    seedId: 'A0A2K5ZUH1',
    memberIdTypes: [
      'UniProtKB Reviewed (Swiss-Prot)',
      'UniProtKB Unreviewed (TrEMBL)',
      'UniParc',
    ],
    members: [
      'P05067-5',
      'A0A2K5ZUH1',
      'A0A3Q0DQT0',
      'P05067-3',
      'U3FGW5',
      'A0A6J3HSH5',
      'A0A1S3W8A7',
      'UPI00063FC617',
      'UPI000642C8DE',
      'UPI000C2B51AE',
    ],
    organisms: [
      { scientificName: 'Homo sapiens', commonName: 'Human', taxonId: 9606 },
      {
        scientificName: 'Mandrillus leucophaeus',
        commonName: 'Drill',
        taxonId: 9568,
      },
      {
        scientificName: 'Carlito syrichta',
        commonName: 'Philippine tarsier',
        taxonId: 1868482,
      },
      {
        scientificName: 'Callithrix jacchus',
        commonName: 'White-tufted-ear marmoset',
        taxonId: 9483,
      },
      {
        scientificName: 'Sapajus apella',
        commonName: 'Brown-capped capuchin',
        taxonId: 9515,
      },
      {
        scientificName: 'Erinaceus europaeus',
        commonName: 'Western European hedgehog',
        taxonId: 9365,
      },
      { scientificName: 'Propithecus coquereli', taxonId: 379532 },
      { scientificName: 'Microcebus murinus', taxonId: 30608 },
      { scientificName: 'Piliocolobus tephrosceles', taxonId: 591936 },
      { scientificName: 'Gorilla gorilla gorilla', taxonId: 9595 },
    ],
    goTerms: [
      { goId: 'GO:0004867', aspect: 'GO Molecular Function' },
      { goId: 'GO:0008201', aspect: 'GO Molecular Function' },
      { goId: 'GO:0046914', aspect: 'GO Molecular Function' },
      { goId: 'GO:0005905', aspect: 'GO Cellular Component' },
      { goId: 'GO:0043204', aspect: 'GO Cellular Component' },
      { goId: 'GO:0030426', aspect: 'GO Cellular Component' },
      { goId: 'GO:0016021', aspect: 'GO Cellular Component' },
      { goId: 'GO:0005769', aspect: 'GO Cellular Component' },
      { goId: 'GO:0007399', aspect: 'GO Biological Process' },
      { goId: 'GO:0006897', aspect: 'GO Biological Process' },
    ],
  },
  {
    id: 'UniRef90_P05067-10',
    name: 'Cluster: Isoform APP639 of Amyloid-beta precursor protein',
    updated: '2021-02-10',
    entryType: 'UniRef90',
    commonTaxon: { scientificName: 'Amniota', taxonId: 32524 },
    memberCount: 105,
    organismCount: 71,
    representativeMember: {
      memberIdType: 'UniProtKB ID',
      memberId: 'P05067-10',
      organismName: 'Homo sapiens (Human)',
      organismTaxId: 9606,
      sequenceLength: 639,
      proteinName: 'Isoform APP639 of Amyloid-beta precursor protein',
      accessions: ['P05067-10'],
      uniref50Id: 'UniRef50_P05067',
      uniref100Id: 'UniRef100_P05067-10',
      uniparcId: { value: 'UPI00001BE539' },
      sequence: {
        value:
          'MLPGLALLLLAAWTARALEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVRVPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEVEPVDARPAADRGLTTRPGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
        length: 639,
        molWeight: 72553,
        crc64: 'C4120DEC51A59A95',
        md5: 'D04CDFB0E2E908743E7E53F43CA6D9F7',
      },
    },
    seedId: 'UPI0011CF72B0',
    memberIdTypes: [
      'UniProtKB Unreviewed (TrEMBL)',
      'UniProtKB Reviewed (Swiss-Prot)',
      'UniParc',
    ],
    members: [
      'P05067-10',
      'A0A2J8UKK4',
      'A0A2J8MQ67',
      'A0A6G1RMJ2',
      'A0A672TXR1',
      'A0A3Q7Y7C0',
      'A0A2I3GV49',
      'B4DQM1',
      'A0A2K6U8W0',
      'A0A3Q7XIE8',
    ],
    organisms: [
      { scientificName: 'Homo sapiens', commonName: 'Human', taxonId: 9606 },
      {
        scientificName: 'Pongo abelii',
        commonName: 'Sumatran orangutan',
        taxonId: 9601,
      },
      {
        scientificName: 'Pan troglodytes',
        commonName: 'Chimpanzee',
        taxonId: 9598,
      },
      { scientificName: 'Gallirallus okinawae', taxonId: 547194 },
      {
        scientificName: 'Strigops habroptila',
        commonName: 'Kakapo',
        taxonId: 2489341,
      },
      { scientificName: 'Ursus arctos horribilis', taxonId: 116960 },
      {
        scientificName: 'Nomascus leucogenys',
        commonName: 'Northern white-cheeked gibbon',
        taxonId: 61853,
      },
      {
        scientificName: 'Saimiri boliviensis boliviensis',
        commonName: 'Bolivian squirrel monkey',
        taxonId: 39432,
      },
      {
        scientificName: 'Pipra filicauda',
        commonName: 'Wire-tailed manakin',
        taxonId: 649802,
      },
      {
        scientificName: 'Lipotes vexillifer',
        commonName: 'Yangtze river dolphin',
        taxonId: 118797,
      },
    ],
  },
  {
    id: 'UniRef90_P05067-4',
    name: 'Cluster: Isoform APP695 of Amyloid-beta precursor protein',
    updated: '2021-02-10',
    entryType: 'UniRef90',
    commonTaxon: { scientificName: 'Amniota', taxonId: 32524 },
    memberCount: 138,
    organismCount: 120,
    representativeMember: {
      memberIdType: 'UniProtKB ID',
      memberId: 'P05067-4',
      organismName: 'Homo sapiens (Human)',
      organismTaxId: 9606,
      sequenceLength: 695,
      proteinName: 'Isoform APP695 of Amyloid-beta precursor protein',
      accessions: ['P05067-4'],
      uniref50Id: 'UniRef50_P05067',
      uniref100Id: 'UniRef100_P05067-4',
      uniparcId: { value: 'UPI000002A2F2' },
      sequence: {
        value:
          'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVRVPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEVEPVDARPAADRGLTTRPGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
        length: 695,
        molWeight: 78663,
        crc64: '4F6EA0139F969D56',
        md5: 'BD089074F6C0866F6A1081DF3FBEB648',
      },
    },
    seedId: 'UPI001386654F',
    memberIdTypes: [
      'UniProtKB Unreviewed (TrEMBL)',
      'UniProtKB Reviewed (Swiss-Prot)',
      'UniParc',
    ],
    members: [
      'P05067-4',
      'I0FGN2',
      'A0A2K6QWS0',
      'A0A2J8UKM8',
      'A0A2I3SHN1',
      'A0A6D2X899',
      'A0A2K5NR37',
      'A0A2I3MTM7',
      'A0A2R8ZFN4',
      'A0A2K5U6B3',
    ],
    organisms: [
      { scientificName: 'Homo sapiens', commonName: 'Human', taxonId: 9606 },
      {
        scientificName: 'Macaca mulatta',
        commonName: 'Rhesus macaque',
        taxonId: 9544,
      },
      {
        scientificName: 'Rhinopithecus roxellana',
        commonName: 'Golden snub-nosed monkey',
        taxonId: 61622,
      },
      {
        scientificName: 'Pongo abelii',
        commonName: 'Sumatran orangutan',
        taxonId: 9601,
      },
      {
        scientificName: 'Pan troglodytes',
        commonName: 'Chimpanzee',
        taxonId: 9598,
      },
      {
        scientificName: 'Cercocebus atys',
        commonName: 'Sooty mangabey',
        taxonId: 9531,
      },
      {
        scientificName: 'Papio anubis',
        commonName: 'Olive baboon',
        taxonId: 9555,
      },
      {
        scientificName: 'Pan paniscus',
        commonName: 'Pygmy chimpanzee',
        taxonId: 9597,
      },
      {
        scientificName: 'Macaca fascicularis',
        commonName: 'Crab-eating macaque',
        taxonId: 9541,
      },
      {
        scientificName: 'Rhinopithecus bieti',
        commonName: 'Black snub-nosed monkey',
        taxonId: 61621,
      },
    ],
    goTerms: [
      { goId: 'GO:0004867', aspect: 'GO Molecular Function' },
      { goId: 'GO:0008201', aspect: 'GO Molecular Function' },
      { goId: 'GO:0046914', aspect: 'GO Molecular Function' },
      { goId: 'GO:0016021', aspect: 'GO Cellular Component' },
      { goId: 'GO:0048856', aspect: 'GO Biological Process' },
    ],
  },
  {
    id: 'UniRef90_P05067-9',
    name: 'Cluster: Isoform L-APP752 of Amyloid-beta precursor protein',
    updated: '2021-02-10',
    entryType: 'UniRef90',
    commonTaxon: { scientificName: 'Eutheria', taxonId: 9347 },
    memberCount: 85,
    organismCount: 76,
    representativeMember: {
      memberIdType: 'UniProtKB ID',
      memberId: 'P05067-9',
      organismName: 'Homo sapiens (Human)',
      organismTaxId: 9606,
      sequenceLength: 752,
      proteinName: 'Isoform L-APP752 of Amyloid-beta precursor protein',
      accessions: ['P05067-9'],
      uniref50Id: 'UniRef50_P05067',
      uniref100Id: 'UniRef100_P05067-9',
      uniparcId: { value: 'UPI000002A2F7' },
      sequence: {
        value:
          'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVREVCSEQAETGPCRAMISRWYFDVTEGKCAPFFYGGCGGNRNNFDTEEYCMAVCGSAMSQSLLKTTQEPLARDPVKLPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
        length: 752,
        molWeight: 85040,
        crc64: '074CFF767CBED2E0',
        md5: '7D77A2EC2E85AF64D225E470989571D2',
      },
    },
    seedId: 'UPI001386A74E',
    memberIdTypes: [
      'UniProtKB Reviewed (Swiss-Prot)',
      'UniProtKB Unreviewed (TrEMBL)',
      'UniParc',
    ],
    members: [
      'P05067-9',
      'A0A7E6D589',
      'A0A6P3F1U1',
      'Q3TXI9',
      'A0A2U3WVJ9',
      'A0A671EM27',
      'A0A2J8UKJ4',
      'A0A2J8MQ65',
      'A0A6D2XM07',
      'A0A2R8ZIG3',
    ],
    organisms: [
      { scientificName: 'Homo sapiens', commonName: 'Human', taxonId: 9606 },
      {
        scientificName: 'Phyllostomus discolor',
        commonName: 'pale spear-nosed bat',
        taxonId: 89673,
      },
      { scientificName: 'Octodon degus', commonName: 'Degu', taxonId: 10160 },
      { scientificName: 'Mus musculus', commonName: 'Mouse', taxonId: 10090 },
      {
        scientificName: 'Odobenus rosmarus divergens',
        commonName: 'Pacific walrus',
        taxonId: 9708,
      },
      {
        scientificName: 'Rhinolophus ferrumequinum',
        commonName: 'Greater horseshoe bat',
        taxonId: 59479,
      },
      {
        scientificName: 'Pongo abelii',
        commonName: 'Sumatran orangutan',
        taxonId: 9601,
      },
      {
        scientificName: 'Pan troglodytes',
        commonName: 'Chimpanzee',
        taxonId: 9598,
      },
      {
        scientificName: 'Pan paniscus',
        commonName: 'Pygmy chimpanzee',
        taxonId: 9597,
      },
      {
        scientificName: 'Gorilla gorilla gorilla',
        commonName: 'Western lowland gorilla',
        taxonId: 9595,
      },
    ],
    goTerms: [
      { goId: 'GO:0004867', aspect: 'GO Molecular Function' },
      { goId: 'GO:0008201', aspect: 'GO Molecular Function' },
      { goId: 'GO:0046914', aspect: 'GO Molecular Function' },
      { goId: 'GO:0005905', aspect: 'GO Cellular Component' },
      { goId: 'GO:0043204', aspect: 'GO Cellular Component' },
      { goId: 'GO:0030426', aspect: 'GO Cellular Component' },
      { goId: 'GO:0016021', aspect: 'GO Cellular Component' },
      { goId: 'GO:0005769', aspect: 'GO Cellular Component' },
      { goId: 'GO:0007219', aspect: 'GO Biological Process' },
      { goId: 'GO:0007399', aspect: 'GO Biological Process' },
      { goId: 'GO:0006897', aspect: 'GO Biological Process' },
    ],
  },
  {
    id: 'UniRef100_P05067-10',
    name: 'Cluster: Isoform APP639 of Amyloid-beta precursor protein',
    updated: '2020-08-12',
    entryType: 'UniRef100',
    commonTaxon: { scientificName: 'Hominidae', taxonId: 9604 },
    memberCount: 3,
    organismCount: 3,
    representativeMember: {
      memberIdType: 'UniProtKB ID',
      memberId: 'P05067-10',
      organismName: 'Homo sapiens (Human)',
      organismTaxId: 9606,
      sequenceLength: 639,
      proteinName: 'Isoform APP639 of Amyloid-beta precursor protein',
      accessions: ['P05067-10'],
      uniref50Id: 'UniRef50_P05067',
      uniref90Id: 'UniRef90_P05067-10',
      uniparcId: { value: 'UPI00001BE539' },
      sequence: {
        value:
          'MLPGLALLLLAAWTARALEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVRVPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEVEPVDARPAADRGLTTRPGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
        length: 639,
        molWeight: 72553,
        crc64: 'C4120DEC51A59A95',
        md5: 'D04CDFB0E2E908743E7E53F43CA6D9F7',
      },
    },
    seedId: 'A0A2J8UKK4',
    memberIdTypes: [
      'UniProtKB Reviewed (Swiss-Prot)',
      'UniProtKB Unreviewed (TrEMBL)',
    ],
    members: ['P05067-10', 'A0A2J8UKK4', 'A0A2J8MQ67'],
    organisms: [
      { scientificName: 'Homo sapiens', commonName: 'Human', taxonId: 9606 },
      {
        scientificName: 'Pongo abelii',
        commonName: 'Sumatran orangutan',
        taxonId: 9601,
      },
      {
        scientificName: 'Pan troglodytes',
        commonName: 'Chimpanzee',
        taxonId: 9598,
      },
    ],
  },
  {
    id: 'UniRef100_P05067-4',
    name: 'Cluster: Isoform APP695 of Amyloid-beta precursor protein',
    updated: '2020-08-12',
    entryType: 'UniRef100',
    commonTaxon: { scientificName: 'Catarrhini', taxonId: 9526 },
    memberCount: 17,
    organismCount: 12,
    representativeMember: {
      memberIdType: 'UniProtKB ID',
      memberId: 'P05067-4',
      organismName: 'Homo sapiens (Human)',
      organismTaxId: 9606,
      sequenceLength: 695,
      proteinName: 'Isoform APP695 of Amyloid-beta precursor protein',
      accessions: ['P05067-4'],
      uniref50Id: 'UniRef50_P05067',
      uniref90Id: 'UniRef90_P05067-4',
      uniparcId: { value: 'UPI000002A2F2' },
      sequence: {
        value:
          'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVRVPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEVEPVDARPAADRGLTTRPGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
        length: 695,
        molWeight: 78663,
        crc64: '4F6EA0139F969D56',
        md5: 'BD089074F6C0866F6A1081DF3FBEB648',
      },
    },
    seedId: 'I0FGN2',
    memberIdTypes: [
      'UniProtKB Unreviewed (TrEMBL)',
      'UniProtKB Reviewed (Swiss-Prot)',
    ],
    members: [
      'P05067-4',
      'I0FGN2',
      'A0A2K6QWS0',
      'A0A2J8UKM8',
      'A0A2I3SHN1',
      'A0A6D2X899',
      'A0A2K5NR37',
      'A0A2I3MTM7',
      'A0A2R8ZFN4',
      'A0A2K5U6B3',
    ],
    organisms: [
      { scientificName: 'Homo sapiens', commonName: 'Human', taxonId: 9606 },
      {
        scientificName: 'Macaca mulatta',
        commonName: 'Rhesus macaque',
        taxonId: 9544,
      },
      {
        scientificName: 'Rhinopithecus roxellana',
        commonName: 'Golden snub-nosed monkey',
        taxonId: 61622,
      },
      {
        scientificName: 'Pongo abelii',
        commonName: 'Sumatran orangutan',
        taxonId: 9601,
      },
      {
        scientificName: 'Pan troglodytes',
        commonName: 'Chimpanzee',
        taxonId: 9598,
      },
      {
        scientificName: 'Cercocebus atys',
        commonName: 'Sooty mangabey',
        taxonId: 9531,
      },
      {
        scientificName: 'Papio anubis',
        commonName: 'Olive baboon',
        taxonId: 9555,
      },
      {
        scientificName: 'Pan paniscus',
        commonName: 'Pygmy chimpanzee',
        taxonId: 9597,
      },
      {
        scientificName: 'Macaca fascicularis',
        commonName: 'Crab-eating macaque',
        taxonId: 9541,
      },
      {
        scientificName: 'Rhinopithecus bieti',
        commonName: 'Black snub-nosed monkey',
        taxonId: 61621,
      },
    ],
  },
  {
    id: 'UniRef100_P05067-2',
    name: 'Cluster: Isoform APP305 of Amyloid-beta precursor protein',
    updated: '2019-01-16',
    entryType: 'UniRef100',
    commonTaxon: { scientificName: 'Homo sapiens', taxonId: 9606 },
    memberCount: 1,
    organismCount: 1,
    representativeMember: {
      memberIdType: 'UniProtKB ID',
      memberId: 'P05067-2',
      organismName: 'Homo sapiens (Human)',
      organismTaxId: 9606,
      sequenceLength: 305,
      proteinName: 'Isoform APP305 of Amyloid-beta precursor protein',
      accessions: ['P05067-2'],
      uniref50Id: 'UniRef50_P05067-2',
      uniref90Id: 'UniRef90_P05067-2',
      uniparcId: { value: 'UPI000002A2F0' },
      seed: true,
      sequence: {
        value:
          'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVREKWYKEVHSGQARWLML',
        length: 305,
        molWeight: 34358,
        crc64: 'D1CCD7237262687A',
        md5: '8048490F3431C1D74DA373E90A7D8D5B',
      },
    },
    seedId: 'P05067-2',
    memberIdTypes: ['UniProtKB Reviewed (Swiss-Prot)'],
    members: ['P05067-2'],
    organisms: [
      { scientificName: 'Homo sapiens', commonName: 'Human', taxonId: 9606 },
    ],
  },
  {
    id: 'UniRef100_P05067-3',
    name: 'Cluster: Isoform L-APP677 of Amyloid-beta precursor protein',
    updated: '2019-12-18',
    entryType: 'UniRef100',
    commonTaxon: { scientificName: 'Homo sapiens', taxonId: 9606 },
    memberCount: 1,
    organismCount: 1,
    representativeMember: {
      memberIdType: 'UniProtKB ID',
      memberId: 'P05067-3',
      organismName: 'Homo sapiens (Human)',
      organismTaxId: 9606,
      sequenceLength: 677,
      proteinName: 'Isoform L-APP677 of Amyloid-beta precursor protein',
      accessions: ['P05067-3'],
      uniref50Id: 'UniRef50_P05067',
      uniref90Id: 'UniRef90_P05067-5',
      uniparcId: { value: 'UPI000002A2F1' },
      seed: true,
      sequence: {
        value:
          'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVRVPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
        length: 677,
        molWeight: 76760,
        crc64: '48334D3EEF26990E',
        md5: 'A338CD5CABF782539F4A55421B23A595',
      },
    },
    seedId: 'P05067-3',
    memberIdTypes: ['UniProtKB Reviewed (Swiss-Prot)'],
    members: ['P05067-3'],
    organisms: [
      { scientificName: 'Homo sapiens', commonName: 'Human', taxonId: 9606 },
    ],
  },
  {
    id: 'UniRef50_P05067-2',
    name: 'Cluster: Isoform APP305 of Amyloid-beta precursor protein',
    updated: '2021-02-10',
    entryType: 'UniRef50',
    commonTaxon: { scientificName: 'Euteleostomi', taxonId: 117571 },
    memberCount: 8,
    organismCount: 5,
    representativeMember: {
      memberIdType: 'UniProtKB ID',
      memberId: 'P05067-2',
      organismName: 'Homo sapiens (Human)',
      organismTaxId: 9606,
      sequenceLength: 305,
      proteinName: 'Isoform APP305 of Amyloid-beta precursor protein',
      accessions: ['P05067-2'],
      uniref90Id: 'UniRef90_P05067-2',
      uniref100Id: 'UniRef100_P05067-2',
      uniparcId: { value: 'UPI000002A2F0' },
      sequence: {
        value:
          'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVREKWYKEVHSGQARWLML',
        length: 305,
        molWeight: 34358,
        crc64: 'D1CCD7237262687A',
        md5: '8048490F3431C1D74DA373E90A7D8D5B',
      },
    },
    seedId: 'A0A0S7L2K4',
    memberIdTypes: [
      'UniProtKB Unreviewed (TrEMBL)',
      'UniProtKB Reviewed (Swiss-Prot)',
    ],
    members: [
      'P05067-2',
      'M1EBY6',
      'A0A6A5F356',
      'A0A0S7L2S1',
      'A0A0S7L2R9',
      'A0A0S7L2L6',
      'A0A0S7L2K4',
      'A0A4Z2BS44',
    ],
    organisms: [
      { scientificName: 'Homo sapiens', commonName: 'Human', taxonId: 9606 },
      {
        scientificName: 'Mustela putorius furo',
        commonName: 'European domestic ferret',
        taxonId: 9669,
      },
      {
        scientificName: 'Perca fluviatilis',
        commonName: 'European perch',
        taxonId: 8168,
      },
      {
        scientificName: 'Poeciliopsis prolifica',
        commonName: 'blackstripe livebearer',
        taxonId: 188132,
      },
      { scientificName: 'Takifugu bimaculatus', taxonId: 433685 },
    ],
  },
  {
    id: 'UniRef100_P05067-11',
    name: 'Cluster: Isoform 11 of Amyloid-beta precursor protein',
    updated: '2019-01-16',
    entryType: 'UniRef100',
    commonTaxon: { scientificName: 'Homo sapiens', taxonId: 9606 },
    memberCount: 1,
    organismCount: 1,
    representativeMember: {
      memberIdType: 'UniProtKB ID',
      memberId: 'P05067-11',
      organismName: 'Homo sapiens (Human)',
      organismTaxId: 9606,
      sequenceLength: 746,
      proteinName: 'Isoform 11 of Amyloid-beta precursor protein',
      accessions: ['P05067-11'],
      uniref50Id: 'UniRef50_P05067',
      uniref90Id: 'UniRef90_P05067-8',
      uniparcId: { value: 'UPI00017A7091' },
      seed: true,
      sequence: {
        value:
          'MDQLEDLLVLFINYVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVREVCSEQAETGPCRAMISRWYFDVTEGKCAPFFYGGCGGNRNNFDTEEYCMAVCGSAIPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEVEPVDARPAADRGLTTRPGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
        length: 746,
        molWeight: 84521,
        crc64: '843411EFBDEFACE3',
        md5: '04E00C8307ADE0838671AB52F9423932',
      },
    },
    seedId: 'P05067-11',
    memberIdTypes: ['UniProtKB Reviewed (Swiss-Prot)'],
    members: ['P05067-11'],
    organisms: [
      { scientificName: 'Homo sapiens', commonName: 'Human', taxonId: 9606 },
    ],
  },
  {
    id: 'UniRef90_P05067-2',
    name: 'Cluster: Isoform APP305 of Amyloid-beta precursor protein',
    updated: '2020-08-12',
    entryType: 'UniRef90',
    commonTaxon: { scientificName: 'Boreoeutheria', taxonId: 1437010 },
    memberCount: 2,
    organismCount: 2,
    representativeMember: {
      memberIdType: 'UniProtKB ID',
      memberId: 'P05067-2',
      organismName: 'Homo sapiens (Human)',
      organismTaxId: 9606,
      sequenceLength: 305,
      proteinName: 'Isoform APP305 of Amyloid-beta precursor protein',
      accessions: ['P05067-2'],
      uniref50Id: 'UniRef50_P05067-2',
      uniref100Id: 'UniRef100_P05067-2',
      uniparcId: { value: 'UPI000002A2F0' },
      seed: true,
      sequence: {
        value:
          'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVREKWYKEVHSGQARWLML',
        length: 305,
        molWeight: 34358,
        crc64: 'D1CCD7237262687A',
        md5: '8048490F3431C1D74DA373E90A7D8D5B',
      },
    },
    seedId: 'P05067-2',
    memberIdTypes: [
      'UniProtKB Reviewed (Swiss-Prot)',
      'UniProtKB Unreviewed (TrEMBL)',
    ],
    members: ['P05067-2', 'M1EBY6'],
    organisms: [
      { scientificName: 'Homo sapiens', commonName: 'Human', taxonId: 9606 },
      {
        scientificName: 'Mustela putorius furo',
        commonName: 'European domestic ferret',
        taxonId: 9669,
      },
    ],
  },
  {
    id: 'UniRef100_P05067-5',
    name: 'Cluster: Isoform L-APP696 of Amyloid-beta precursor protein',
    updated: '2019-01-16',
    entryType: 'UniRef100',
    commonTaxon: { scientificName: 'Homo sapiens', taxonId: 9606 },
    memberCount: 1,
    organismCount: 1,
    representativeMember: {
      memberIdType: 'UniProtKB ID',
      memberId: 'P05067-5',
      organismName: 'Homo sapiens (Human)',
      organismTaxId: 9606,
      sequenceLength: 696,
      proteinName: 'Isoform L-APP696 of Amyloid-beta precursor protein',
      accessions: ['P05067-5'],
      uniref50Id: 'UniRef50_P05067',
      uniref90Id: 'UniRef90_P05067-5',
      uniparcId: { value: 'UPI000002A2F3' },
      seed: true,
      sequence: {
        value:
          'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVRVSQSLLKTTQEPLARDPVKLPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
        length: 696,
        molWeight: 78866,
        crc64: '66DFDFFCFDB75A72',
        md5: '94203A08AE85B6BB240F0941282243D6',
      },
    },
    seedId: 'P05067-5',
    memberIdTypes: ['UniProtKB Reviewed (Swiss-Prot)'],
    members: ['P05067-5'],
    organisms: [
      { scientificName: 'Homo sapiens', commonName: 'Human', taxonId: 9606 },
    ],
  },
  {
    id: 'UniRef100_P05067-7',
    name: 'Cluster: Isoform L-APP733 of Amyloid-beta precursor protein',
    updated: '2019-01-16',
    entryType: 'UniRef100',
    commonTaxon: { scientificName: 'Homo sapiens', taxonId: 9606 },
    memberCount: 1,
    organismCount: 1,
    representativeMember: {
      memberIdType: 'UniProtKB ID',
      memberId: 'P05067-7',
      organismName: 'Homo sapiens (Human)',
      organismTaxId: 9606,
      sequenceLength: 733,
      proteinName: 'Isoform L-APP733 of Amyloid-beta precursor protein',
      accessions: ['P05067-7'],
      uniref50Id: 'UniRef50_P05067',
      uniref90Id: 'UniRef90_P05067-8',
      uniparcId: { value: 'UPI000002A2F5' },
      seed: true,
      sequence: {
        value:
          'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVREVCSEQAETGPCRAMISRWYFDVTEGKCAPFFYGGCGGNRNNFDTEEYCMAVCGSAIPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
        length: 733,
        molWeight: 82916,
        crc64: '44528239D68A53EE',
        md5: '93307E53EAA95B82664CC2BC9165B156',
      },
    },
    seedId: 'P05067-7',
    memberIdTypes: ['UniProtKB Reviewed (Swiss-Prot)'],
    members: ['P05067-7'],
    organisms: [
      { scientificName: 'Homo sapiens', commonName: 'Human', taxonId: 9606 },
    ],
  },
  {
    id: 'UniRef100_P05067-8',
    name: 'Cluster: Isoform APP751 of Amyloid-beta precursor protein',
    updated: '2019-01-16',
    entryType: 'UniRef100',
    commonTaxon: { scientificName: 'Homo sapiens', taxonId: 9606 },
    memberCount: 2,
    organismCount: 1,
    representativeMember: {
      memberIdType: 'UniProtKB ID',
      memberId: 'P05067-8',
      organismName: 'Homo sapiens (Human)',
      organismTaxId: 9606,
      sequenceLength: 751,
      proteinName: 'Isoform APP751 of Amyloid-beta precursor protein',
      accessions: ['P05067-8'],
      uniref50Id: 'UniRef50_P05067',
      uniref90Id: 'UniRef90_P05067-8',
      uniparcId: { value: 'UPI000002A2F6' },
      seed: true,
      sequence: {
        value:
          'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVREVCSEQAETGPCRAMISRWYFDVTEGKCAPFFYGGCGGNRNNFDTEEYCMAVCGSAIPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEVEPVDARPAADRGLTTRPGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
        length: 751,
        molWeight: 84819,
        crc64: 'C987C557C5A3714E',
        md5: 'A83D724FA6C8F6A50993DB360949D528',
      },
    },
    seedId: 'P05067-8',
    memberIdTypes: ['UniProtKB Reviewed (Swiss-Prot)', 'UniParc'],
    members: ['P05067-8', 'UPI000002DA86'],
    organisms: [
      { scientificName: 'Homo sapiens', commonName: 'Human', taxonId: 9606 },
    ],
  },
  {
    id: 'UniRef100_P05067-9',
    name: 'Cluster: Isoform L-APP752 of Amyloid-beta precursor protein',
    updated: '2019-01-16',
    entryType: 'UniRef100',
    commonTaxon: { scientificName: 'Homo sapiens', taxonId: 9606 },
    memberCount: 1,
    organismCount: 1,
    representativeMember: {
      memberIdType: 'UniProtKB ID',
      memberId: 'P05067-9',
      organismName: 'Homo sapiens (Human)',
      organismTaxId: 9606,
      sequenceLength: 752,
      proteinName: 'Isoform L-APP752 of Amyloid-beta precursor protein',
      accessions: ['P05067-9'],
      uniref50Id: 'UniRef50_P05067',
      uniref90Id: 'UniRef90_P05067-9',
      uniparcId: { value: 'UPI000002A2F7' },
      seed: true,
      sequence: {
        value:
          'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVREVCSEQAETGPCRAMISRWYFDVTEGKCAPFFYGGCGGNRNNFDTEEYCMAVCGSAMSQSLLKTTQEPLARDPVKLPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
        length: 752,
        molWeight: 85040,
        crc64: '074CFF767CBED2E0',
        md5: '7D77A2EC2E85AF64D225E470989571D2',
      },
    },
    seedId: 'P05067-9',
    memberIdTypes: ['UniProtKB Reviewed (Swiss-Prot)'],
    members: ['P05067-9'],
    organisms: [
      { scientificName: 'Homo sapiens', commonName: 'Human', taxonId: 9606 },
    ],
  },
  {
    id: 'UniRef100_P05067-6',
    name: 'Cluster: Isoform APP714 of Amyloid-beta precursor protein',
    updated: '2020-08-12',
    entryType: 'UniRef100',
    commonTaxon: { scientificName: 'Hominidae', taxonId: 9604 },
    memberCount: 3,
    organismCount: 3,
    representativeMember: {
      memberIdType: 'UniProtKB ID',
      memberId: 'P05067-6',
      organismName: 'Homo sapiens (Human)',
      organismTaxId: 9606,
      sequenceLength: 714,
      proteinName: 'Isoform APP714 of Amyloid-beta precursor protein',
      accessions: ['P05067-6'],
      uniref50Id: 'UniRef50_P05067',
      uniref90Id: 'UniRef90_P05067-6',
      uniparcId: { value: 'UPI000002A2F4' },
      seed: true,
      sequence: {
        value:
          'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVRVSQSLLKTTQEPLARDPVKLPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEVEPVDARPAADRGLTTRPGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
        length: 714,
        molWeight: 80769,
        crc64: '124EA691773DC13B',
        md5: '8CA2189A8D89EC9502051E9DBDA6AF9D',
      },
    },
    seedId: 'P05067-6',
    memberIdTypes: [
      'UniProtKB Unreviewed (TrEMBL)',
      'UniProtKB Reviewed (Swiss-Prot)',
    ],
    members: ['P05067-6', 'A0A2J8UKJ9', 'A0A2J8MQ83'],
    organisms: [
      { scientificName: 'Homo sapiens', commonName: 'Human', taxonId: 9606 },
      {
        scientificName: 'Pongo abelii',
        commonName: 'Sumatran orangutan',
        taxonId: 9601,
      },
      {
        scientificName: 'Pan troglodytes',
        commonName: 'Chimpanzee',
        taxonId: 9598,
      },
    ],
  },
  {
    id: 'UniRef90_P05067-6',
    name: 'Cluster: Isoform APP714 of Amyloid-beta precursor protein',
    updated: '2021-02-10',
    entryType: 'UniRef90',
    commonTaxon: { scientificName: 'Boreoeutheria', taxonId: 1437010 },
    memberCount: 24,
    organismCount: 23,
    representativeMember: {
      memberIdType: 'UniProtKB ID',
      memberId: 'P05067-6',
      organismName: 'Homo sapiens (Human)',
      organismTaxId: 9606,
      sequenceLength: 714,
      proteinName: 'Isoform APP714 of Amyloid-beta precursor protein',
      accessions: ['P05067-6'],
      uniref50Id: 'UniRef50_P05067',
      uniref100Id: 'UniRef100_P05067-6',
      uniparcId: { value: 'UPI000002A2F4' },
      sequence: {
        value:
          'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVRVSQSLLKTTQEPLARDPVKLPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEVEPVDARPAADRGLTTRPGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
        length: 714,
        molWeight: 80769,
        crc64: '124EA691773DC13B',
        md5: '8CA2189A8D89EC9502051E9DBDA6AF9D',
      },
    },
    seedId: 'UPI001386BA67',
    memberIdTypes: [
      'UniProtKB Unreviewed (TrEMBL)',
      'UniProtKB Reviewed (Swiss-Prot)',
      'UniParc',
    ],
    members: [
      'P05067-6',
      'A0A2J8UKJ9',
      'A0A2J8MQ83',
      'A0A383YN53',
      'A0A6J2C5P7',
      'A0A5K1UK61',
      'F1P615',
      'A0A287AJD6',
      'A0A4X1UDV2',
      'A0A2Y9K0M0',
    ],
    organisms: [
      { scientificName: 'Homo sapiens', commonName: 'Human', taxonId: 9606 },
      {
        scientificName: 'Pongo abelii',
        commonName: 'Sumatran orangutan',
        taxonId: 9601,
      },
      {
        scientificName: 'Pan troglodytes',
        commonName: 'Chimpanzee',
        taxonId: 9598,
      },
      {
        scientificName: 'Balaenoptera acutorostrata scammoni',
        commonName: 'North Pacific minke whale',
        taxonId: 310752,
      },
      {
        scientificName: 'Zalophus californianus',
        commonName: 'California sealion',
        taxonId: 9704,
      },
      {
        scientificName: 'Callithrix jacchus',
        commonName: 'White-tufted-ear marmoset',
        taxonId: 9483,
      },
      {
        scientificName: 'Canis lupus familiaris',
        commonName: 'Dog',
        taxonId: 9615,
      },
      { scientificName: 'Sus scrofa', commonName: 'Pig', taxonId: 9823 },
      { scientificName: 'Enhydra lutris kenyoni', taxonId: 391180 },
      {
        scientificName: 'Odobenus rosmarus divergens',
        commonName: 'Pacific walrus',
        taxonId: 9708,
      },
    ],
    goTerms: [
      { goId: 'GO:0004867', aspect: 'GO Molecular Function' },
      { goId: 'GO:0008201', aspect: 'GO Molecular Function' },
      { goId: 'GO:0046914', aspect: 'GO Molecular Function' },
      { goId: 'GO:0005905', aspect: 'GO Cellular Component' },
      { goId: 'GO:0043204', aspect: 'GO Cellular Component' },
      { goId: 'GO:0030426', aspect: 'GO Cellular Component' },
      { goId: 'GO:0016021', aspect: 'GO Cellular Component' },
      { goId: 'GO:0005769', aspect: 'GO Cellular Component' },
      { goId: 'GO:0007399', aspect: 'GO Biological Process' },
    ],
  },
  {
    id: 'UniRef100_P05067',
    name: 'Cluster: Amyloid-beta precursor protein',
    updated: '2020-08-12',
    entryType: 'UniRef100',
    commonTaxon: { scientificName: 'Catarrhini', taxonId: 9526 },
    memberCount: 4,
    organismCount: 2,
    representativeMember: {
      memberIdType: 'UniProtKB ID',
      memberId: 'A4_HUMAN',
      organismName: 'Homo sapiens (Human)',
      organismTaxId: 9606,
      sequenceLength: 770,
      proteinName: 'Amyloid-beta precursor protein',
      accessions: [
        'P05067',
        'B2R5V1',
        'B4DII8',
        'D3DSD1',
        'D3DSD2',
        'D3DSD3',
        'P09000',
        'P78438',
        'Q13764',
        'Q13778',
        'Q13793',
        'Q16011',
        'Q16014',
        'Q16019',
        'Q16020',
        'Q6GSC0',
        'Q8WZ99',
        'Q9BT38',
        'Q9UC33',
        'Q9UCA9',
        'Q9UCB6',
        'Q9UCC8',
        'Q9UCD1',
        'Q9UQ58',
      ],
      uniref50Id: 'UniRef50_P05067',
      uniref90Id: 'UniRef90_P05067',
      uniparcId: { value: 'UPI000002DB1C' },
      seed: true,
      sequence: {
        value:
          'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVREVCSEQAETGPCRAMISRWYFDVTEGKCAPFFYGGCGGNRNNFDTEEYCMAVCGSAMSQSLLKTTQEPLARDPVKLPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEVEPVDARPAADRGLTTRPGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
        length: 770,
        molWeight: 86943,
        crc64: 'A12EE761403740F5',
        md5: '7DD43312CD29A262ACDC0517230BC5CA',
      },
    },
    seedId: 'P05067',
    memberIdTypes: [
      'UniProtKB Unreviewed (TrEMBL)',
      'UniProtKB Reviewed (Swiss-Prot)',
      'UniParc',
    ],
    members: ['P05067', 'A0A140VJC8', 'O97584', 'UPI0000110448'],
    organisms: [
      { scientificName: 'Homo sapiens', commonName: 'Human', taxonId: 9606 },
      {
        scientificName: 'Macaca mulatta',
        commonName: 'Rhesus macaque',
        taxonId: 9544,
      },
    ],
  },
  {
    id: 'UniRef90_P05067',
    name: 'Cluster: Amyloid-beta precursor protein',
    updated: '2021-02-10',
    entryType: 'UniRef90',
    commonTaxon: { scientificName: 'cellular organisms', taxonId: 131567 },
    memberCount: 374,
    organismCount: 268,
    representativeMember: {
      memberIdType: 'UniProtKB ID',
      memberId: 'A4_HUMAN',
      organismName: 'Homo sapiens (Human)',
      organismTaxId: 9606,
      sequenceLength: 770,
      proteinName: 'Amyloid-beta precursor protein',
      accessions: [
        'P05067',
        'B2R5V1',
        'B4DII8',
        'D3DSD1',
        'D3DSD2',
        'D3DSD3',
        'P09000',
        'P78438',
        'Q13764',
        'Q13778',
        'Q13793',
        'Q16011',
        'Q16014',
        'Q16019',
        'Q16020',
        'Q6GSC0',
        'Q8WZ99',
        'Q9BT38',
        'Q9UC33',
        'Q9UCA9',
        'Q9UCB6',
        'Q9UCC8',
        'Q9UCD1',
        'Q9UQ58',
      ],
      uniref50Id: 'UniRef50_P05067',
      uniref100Id: 'UniRef100_P05067',
      uniparcId: { value: 'UPI000002DB1C' },
      sequence: {
        value:
          'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVREVCSEQAETGPCRAMISRWYFDVTEGKCAPFFYGGCGGNRNNFDTEEYCMAVCGSAMSQSLLKTTQEPLARDPVKLPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEVEPVDARPAADRGLTTRPGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
        length: 770,
        molWeight: 86943,
        crc64: 'A12EE761403740F5',
        md5: '7DD43312CD29A262ACDC0517230BC5CA',
      },
    },
    seedId: 'UPI001386A8D7',
    memberIdTypes: [
      'UniProtKB Unreviewed (TrEMBL)',
      'UniProtKB Reviewed (Swiss-Prot)',
      'UniParc',
    ],
    members: [
      'P05067',
      'Q5IS80',
      'P12023',
      'P79307',
      'P08592',
      'Q28053',
      'Q28748',
      'Q28757',
      'Q28280',
      'Q29149',
    ],
    organisms: [
      { scientificName: 'Homo sapiens', commonName: 'Human', taxonId: 9606 },
      {
        scientificName: 'Pan troglodytes',
        commonName: 'Chimpanzee',
        taxonId: 9598,
      },
      { scientificName: 'Mus musculus', commonName: 'Mouse', taxonId: 10090 },
      { scientificName: 'Sus scrofa', commonName: 'Pig', taxonId: 9823 },
      {
        scientificName: 'Rattus norvegicus',
        commonName: 'Rat',
        taxonId: 10116,
      },
      { scientificName: 'Bos taurus', commonName: 'Bovine', taxonId: 9913 },
      {
        scientificName: 'Oryctolagus cuniculus',
        commonName: 'Rabbit',
        taxonId: 9986,
      },
      { scientificName: 'Ovis aries', commonName: 'Sheep', taxonId: 9940 },
      {
        scientificName: 'Canis lupus familiaris',
        commonName: 'Dog',
        taxonId: 9615,
      },
      {
        scientificName: 'Ursus maritimus',
        commonName: 'Polar bear',
        taxonId: 29073,
      },
    ],
  },
];

export default mock;
