import { UniRefLiteAPIModel } from '../../../../../uniref/adapters/uniRefConverter';

// /api/uniref/search?query=(uniprot_id:P05067%20OR%20uniprot_id:P05067-1%20OR%20uniprot_id:P05067-2%20OR%20uniprot_id:P05067-3%20OR%20uniprot_id:P05067-4%20OR%20uniprot_id:P05067-5%20OR%20uniprot_id:P05067-6%20OR%20uniprot_id:P05067-7%20OR%20uniprot_id:P05067-8%20OR%20uniprot_id:P05067-9%20OR%20uniprot_id:P05067-10%20OR%20uniprot_id:P05067-11)
const mock: UniRefLiteAPIModel[] = [
  {
    id: 'UniRef50_P05067',
    name: 'Cluster: Amyloid-beta precursor protein',
    updated: '2021-04-07',
    entryType: 'UniRef50',
    commonTaxon: { scientificName: 'cellular organisms', taxonId: 131567 },
    memberCount: 1549,
    organismCount: 563,
    representativeMember: {
      memberIdType: 'UniProtKB ID',
      memberId: 'A4_HUMAN',
      organismName: 'Homo sapiens (Human)',
      organismTaxId: 9606,
      sequenceLength: 770,
      proteinName: 'Amyloid-beta precursor protein',
      accessions: [
        'P05067',
        'B2R5V1',
        'B4DII8',
        'D3DSD1',
        'D3DSD2',
        'D3DSD3',
        'P09000',
        'P78438',
        'Q13764',
        'Q13778',
        'Q13793',
        'Q16011',
        'Q16014',
        'Q16019',
        'Q16020',
        'Q6GSC0',
        'Q8WZ99',
        'Q9BT38',
        'Q9UC33',
        'Q9UCA9',
        'Q9UCB6',
        'Q9UCC8',
        'Q9UCD1',
        'Q9UQ58',
      ],
      uniref90Id: 'UniRef90_P05067',
      uniref100Id: 'UniRef100_P05067',
      uniparcId: { value: 'UPI000002DB1C' },
      sequence: {
        value:
          'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVREVCSEQAETGPCRAMISRWYFDVTEGKCAPFFYGGCGGNRNNFDTEEYCMAVCGSAMSQSLLKTTQEPLARDPVKLPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEVEPVDARPAADRGLTTRPGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
        length: 770,
        molWeight: 86943,
        crc64: 'A12EE761403740F5',
        md5: '7DD43312CD29A262ACDC0517230BC5CA',
      },
    },
    seedId: 'UPI001386A8D7',
    memberIdTypes: [
      'UniProtKB Reviewed (Swiss-Prot)',
      'UniProtKB Unreviewed (TrEMBL)',
      'UniParc',
    ],
    members: [
      'P05067',
      'P12023',
      'Q5IS80',
      'P08592',
      'P79307',
      'Q28053',
      'Q28748',
      'Q28757',
      'Q28280',
      'Q29149',
    ],
    organisms: [
      { scientificName: 'Homo sapiens', commonName: 'Human', taxonId: 9606 },
      { scientificName: 'Mus musculus', commonName: 'Mouse', taxonId: 10090 },
      {
        scientificName: 'Pan troglodytes',
        commonName: 'Chimpanzee',
        taxonId: 9598,
      },
      {
        scientificName: 'Rattus norvegicus',
        commonName: 'Rat',
        taxonId: 10116,
      },
      { scientificName: 'Sus scrofa', commonName: 'Pig', taxonId: 9823 },
      { scientificName: 'Bos taurus', commonName: 'Bovine', taxonId: 9913 },
      {
        scientificName: 'Oryctolagus cuniculus',
        commonName: 'Rabbit',
        taxonId: 9986,
      },
      { scientificName: 'Ovis aries', commonName: 'Sheep', taxonId: 9940 },
      {
        scientificName: 'Canis lupus familiaris',
        commonName: 'Dog',
        taxonId: 9615,
      },
      {
        scientificName: 'Ursus maritimus',
        commonName: 'Polar bear',
        taxonId: 29073,
      },
    ],
  },
  {
    id: 'UniRef90_P05067-8',
    name: 'Cluster: Isoform APP751 of Amyloid-beta precursor protein',
    updated: '2021-04-07',
    entryType: 'UniRef90',
    commonTaxon: { scientificName: 'Amniota', taxonId: 32524 },
    memberCount: 370,
    organismCount: 196,
    representativeMember: {
      memberIdType: 'UniProtKB ID',
      memberId: 'P05067-8',
      organismName: 'Homo sapiens (Human)',
      organismTaxId: 9606,
      sequenceLength: 751,
      proteinName: 'Isoform APP751 of Amyloid-beta precursor protein',
      accessions: ['P05067-8'],
      uniref50Id: 'UniRef50_P05067',
      uniref100Id: 'UniRef100_P05067-8',
      uniparcId: { value: 'UPI000002A2F6' },
      sequence: {
        value:
          'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVREVCSEQAETGPCRAMISRWYFDVTEGKCAPFFYGGCGGNRNNFDTEEYCMAVCGSAIPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEVEPVDARPAADRGLTTRPGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
        length: 751,
        molWeight: 84819,
        crc64: 'C987C557C5A3714E',
        md5: 'A83D724FA6C8F6A50993DB360949D528',
      },
    },
    seedId: 'UPI0011CED4DA',
    memberIdTypes: [
      'UniProtKB Reviewed (Swiss-Prot)',
      'UniProtKB Unreviewed (TrEMBL)',
      'UniParc',
    ],
    members: [
      'P05067-8',
      'Q95241',
      'A0A672TXQ3',
      'Q8JH58',
      'A0A674K557',
      'A0A3Q7Y752',
      'A0A7J8A4I5',
      'A0A6P3GZH0',
      'A0A1S3GCQ5',
      'Q9DGJ7',
    ],
    organisms: [
      { scientificName: 'Homo sapiens', commonName: 'Human', taxonId: 9606 },
      {
        scientificName: 'Saimiri sciureus',
        commonName: 'Common squirrel monkey',
        taxonId: 9521,
      },
      {
        scientificName: 'Strigops habroptila',
        commonName: 'Kakapo',
        taxonId: 2489341,
      },
      {
        scientificName: 'Chelydra serpentina',
        commonName: 'Snapping turtle',
        taxonId: 8475,
      },
      {
        scientificName: 'Terrapene carolina triunguis',
        commonName: 'Three-toed box turtle',
        taxonId: 2587831,
      },
      { scientificName: 'Ursus arctos horribilis', taxonId: 116960 },
      {
        scientificName: 'Pipistrellus kuhlii',
        commonName: "Kuhl's pipistrelle",
        taxonId: 59472,
      },
      { scientificName: 'Bison bison bison', taxonId: 43346 },
      {
        scientificName: 'Dipodomys ordii',
        commonName: "Ord's kangaroo rat",
        taxonId: 10020,
      },
      {
        scientificName: 'Gallus gallus',
        commonName: 'Chicken',
        taxonId: 9031,
      },
    ],
  },
  {
    id: 'UniRef50_P05067-5',
    name: 'Cluster: Isoform L-APP696 of Amyloid-beta precursor protein',
    updated: '2021-04-07',
    entryType: 'UniRef50',
    commonTaxon: { scientificName: 'Gnathostomata', taxonId: 7776 },
    memberCount: 331,
    organismCount: 202,
    representativeMember: {
      memberIdType: 'UniProtKB ID',
      memberId: 'P05067-5',
      organismName: 'Homo sapiens (Human)',
      organismTaxId: 9606,
      sequenceLength: 696,
      proteinName: 'Isoform L-APP696 of Amyloid-beta precursor protein',
      accessions: ['P05067-5'],
      uniref90Id: 'UniRef90_P05067-5',
      uniref100Id: 'UniRef100_P05067-5',
      uniparcId: { value: 'UPI000002A2F3' },
      sequence: {
        value:
          'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVRVSQSLLKTTQEPLARDPVKLPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
        length: 696,
        molWeight: 78866,
        crc64: '66DFDFFCFDB75A72',
        md5: '94203A08AE85B6BB240F0941282243D6',
      },
    },
    seedId: 'A0A674H3K2',
    memberIdTypes: [
      'UniProtKB Reviewed (Swiss-Prot)',
      'UniProtKB Unreviewed (TrEMBL)',
      'UniParc',
    ],
    members: [
      'P05067-5',
      'A0A674H3K2',
      'A0A674GBF3',
      'A0A7K8MKT4',
      'A0A7L0Y4F0',
      'A0A7K7L7U3',
      'A0A6I9HNH8',
      'A0A7K8EYC4',
      'A0A2K6U8W0',
      'A0A672TUL7',
    ],
    organisms: [
      { scientificName: 'Homo sapiens', commonName: 'Human', taxonId: 9606 },
      {
        scientificName: 'Taeniopygia guttata',
        commonName: 'Zebra finch',
        taxonId: 59729,
      },
      { scientificName: 'Ptilorrhoa leucosticta', taxonId: 449384 },
      { scientificName: 'Ploceus nigricollis', taxonId: 441696 },
      { scientificName: 'Asarcornis scutulata', taxonId: 75869 },
      {
        scientificName: 'Geospiza fortis',
        commonName: 'Medium ground-finch',
        taxonId: 48883,
      },
      { scientificName: 'Struthidea cinerea', taxonId: 181839 },
      {
        scientificName: 'Saimiri boliviensis boliviensis',
        commonName: 'Bolivian squirrel monkey',
        taxonId: 39432,
      },
      {
        scientificName: 'Strigops habroptila',
        commonName: 'Kakapo',
        taxonId: 2489341,
      },
      { scientificName: 'Ursus arctos horribilis', taxonId: 116960 },
    ],
    goTerms: [
      { goId: 'GO:0008201', aspect: 'GO Molecular Function' },
      { goId: 'GO:0016021', aspect: 'GO Cellular Component' },
      { goId: 'GO:0048731', aspect: 'GO Biological Process' },
    ],
  },
  {
    id: 'UniRef90_P05067-5',
    name: 'Cluster: Isoform L-APP696 of Amyloid-beta precursor protein',
    updated: '2021-04-07',
    entryType: 'UniRef90',
    commonTaxon: { scientificName: 'Amniota', taxonId: 32524 },
    memberCount: 111,
    organismCount: 74,
    representativeMember: {
      memberIdType: 'UniProtKB ID',
      memberId: 'P05067-5',
      organismName: 'Homo sapiens (Human)',
      organismTaxId: 9606,
      sequenceLength: 696,
      proteinName: 'Isoform L-APP696 of Amyloid-beta precursor protein',
      accessions: ['P05067-5'],
      uniref50Id: 'UniRef50_P05067-5',
      uniref100Id: 'UniRef100_P05067-5',
      uniparcId: { value: 'UPI000002A2F3' },
      sequence: {
        value:
          'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVRVSQSLLKTTQEPLARDPVKLPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
        length: 696,
        molWeight: 78866,
        crc64: '66DFDFFCFDB75A72',
        md5: '94203A08AE85B6BB240F0941282243D6',
      },
    },
    seedId: 'A0A674H3K2',
    memberIdTypes: [
      'UniProtKB Reviewed (Swiss-Prot)',
      'UniProtKB Unreviewed (TrEMBL)',
      'UniParc',
    ],
    members: [
      'P05067-5',
      'A0A674H3K2',
      'A0A674GBF3',
      'A0A7L0Y4F0',
      'A0A7K8MKT4',
      'A0A7K7L7U3',
      'A0A6I9HNH8',
      'A0A7K8EYC4',
      'A0A3Q7XIE8',
      'A0A672TUL7',
    ],
    organisms: [
      { scientificName: 'Homo sapiens', commonName: 'Human', taxonId: 9606 },
      {
        scientificName: 'Taeniopygia guttata',
        commonName: 'Zebra finch',
        taxonId: 59729,
      },
      { scientificName: 'Ploceus nigricollis', taxonId: 441696 },
      { scientificName: 'Ptilorrhoa leucosticta', taxonId: 449384 },
      { scientificName: 'Asarcornis scutulata', taxonId: 75869 },
      {
        scientificName: 'Geospiza fortis',
        commonName: 'Medium ground-finch',
        taxonId: 48883,
      },
      { scientificName: 'Struthidea cinerea', taxonId: 181839 },
      { scientificName: 'Ursus arctos horribilis', taxonId: 116960 },
      {
        scientificName: 'Strigops habroptila',
        commonName: 'Kakapo',
        taxonId: 2489341,
      },
      {
        scientificName: 'Saimiri boliviensis boliviensis',
        commonName: 'Bolivian squirrel monkey',
        taxonId: 39432,
      },
    ],
    goTerms: [
      { goId: 'GO:0008201', aspect: 'GO Molecular Function' },
      { goId: 'GO:0046914', aspect: 'GO Molecular Function' },
      { goId: 'GO:0005798', aspect: 'GO Cellular Component' },
      { goId: 'GO:0016021', aspect: 'GO Cellular Component' },
      { goId: 'GO:0007399', aspect: 'GO Biological Process' },
    ],
  },
  {
    id: 'UniRef90_P05067-4',
    name: 'Cluster: Isoform APP695 of Amyloid-beta precursor protein',
    updated: '2021-04-07',
    entryType: 'UniRef90',
    commonTaxon: { scientificName: 'Amniota', taxonId: 32524 },
    memberCount: 146,
    organismCount: 126,
    representativeMember: {
      memberIdType: 'UniProtKB ID',
      memberId: 'P05067-4',
      organismName: 'Homo sapiens (Human)',
      organismTaxId: 9606,
      sequenceLength: 695,
      proteinName: 'Isoform APP695 of Amyloid-beta precursor protein',
      accessions: ['P05067-4'],
      uniref50Id: 'UniRef50_P05067',
      uniref100Id: 'UniRef100_P05067-4',
      uniparcId: { value: 'UPI000002A2F2' },
      sequence: {
        value:
          'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVRVPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEVEPVDARPAADRGLTTRPGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
        length: 695,
        molWeight: 78663,
        crc64: '4F6EA0139F969D56',
        md5: 'BD089074F6C0866F6A1081DF3FBEB648',
      },
    },
    seedId: 'UPI001386654F',
    memberIdTypes: [
      'UniProtKB Reviewed (Swiss-Prot)',
      'UniProtKB Unreviewed (TrEMBL)',
      'UniParc',
    ],
    members: [
      'P05067-4',
      'I0FGN2',
      'A0A2K6QWS0',
      'A0A2J8UKM8',
      'A0A2I3SHN1',
      'A0A6D2X899',
      'A0A2K5NR37',
      'A0A2I3MTM7',
      'A0A2R8ZFN4',
      'A0A2K5U6B3',
    ],
    organisms: [
      { scientificName: 'Homo sapiens', commonName: 'Human', taxonId: 9606 },
      {
        scientificName: 'Macaca mulatta',
        commonName: 'Rhesus macaque',
        taxonId: 9544,
      },
      {
        scientificName: 'Rhinopithecus roxellana',
        commonName: 'Golden snub-nosed monkey',
        taxonId: 61622,
      },
      {
        scientificName: 'Pongo abelii',
        commonName: 'Sumatran orangutan',
        taxonId: 9601,
      },
      {
        scientificName: 'Pan troglodytes',
        commonName: 'Chimpanzee',
        taxonId: 9598,
      },
      {
        scientificName: 'Cercocebus atys',
        commonName: 'Sooty mangabey',
        taxonId: 9531,
      },
      {
        scientificName: 'Papio anubis',
        commonName: 'Olive baboon',
        taxonId: 9555,
      },
      {
        scientificName: 'Pan paniscus',
        commonName: 'Pygmy chimpanzee',
        taxonId: 9597,
      },
      {
        scientificName: 'Macaca fascicularis',
        commonName: 'Crab-eating macaque',
        taxonId: 9541,
      },
      {
        scientificName: 'Rhinopithecus bieti',
        commonName: 'Black snub-nosed monkey',
        taxonId: 61621,
      },
    ],
    goTerms: [
      { goId: 'GO:0004867', aspect: 'GO Molecular Function' },
      { goId: 'GO:0008201', aspect: 'GO Molecular Function' },
      { goId: 'GO:0046914', aspect: 'GO Molecular Function' },
      { goId: 'GO:0005798', aspect: 'GO Cellular Component' },
      { goId: 'GO:0016021', aspect: 'GO Cellular Component' },
      { goId: 'GO:0048856', aspect: 'GO Biological Process' },
    ],
  },
  {
    id: 'UniRef90_P05067-9',
    name: 'Cluster: Isoform L-APP752 of Amyloid-beta precursor protein',
    updated: '2021-04-07',
    entryType: 'UniRef90',
    commonTaxon: { scientificName: 'Amniota', taxonId: 32524 },
    memberCount: 89,
    organismCount: 78,
    representativeMember: {
      memberIdType: 'UniProtKB ID',
      memberId: 'P05067-9',
      organismName: 'Homo sapiens (Human)',
      organismTaxId: 9606,
      sequenceLength: 752,
      proteinName: 'Isoform L-APP752 of Amyloid-beta precursor protein',
      accessions: ['P05067-9'],
      uniref50Id: 'UniRef50_P05067',
      uniref100Id: 'UniRef100_P05067-9',
      uniparcId: { value: 'UPI000002A2F7' },
      sequence: {
        value:
          'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVREVCSEQAETGPCRAMISRWYFDVTEGKCAPFFYGGCGGNRNNFDTEEYCMAVCGSAMSQSLLKTTQEPLARDPVKLPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
        length: 752,
        molWeight: 85040,
        crc64: '074CFF767CBED2E0',
        md5: '7D77A2EC2E85AF64D225E470989571D2',
      },
    },
    seedId: 'UPI001386A74E',
    memberIdTypes: [
      'UniProtKB Reviewed (Swiss-Prot)',
      'UniProtKB Unreviewed (TrEMBL)',
      'UniParc',
    ],
    members: [
      'P05067-9',
      'A0A7J8HMQ4',
      'A0A671EM27',
      'A0A7J8ADA2',
      'A0A2Y9EZH0',
      'A0A286Y237',
      'A0A1S3GE02',
      'A0A6I9IKC7',
      'A0A3Q7P2Y3',
      'A0A6J2CA92',
    ],
    organisms: [
      { scientificName: 'Homo sapiens', commonName: 'Human', taxonId: 9606 },
      {
        scientificName: 'Rousettus aegyptiacus',
        commonName: 'Egyptian rousette',
        taxonId: 9407,
      },
      {
        scientificName: 'Rhinolophus ferrumequinum',
        commonName: 'Greater horseshoe bat',
        taxonId: 59479,
      },
      {
        scientificName: 'Physeter macrocephalus',
        commonName: 'Sperm whale',
        taxonId: 9755,
      },
      {
        scientificName: 'Cavia porcellus',
        commonName: 'Guinea pig',
        taxonId: 10141,
      },
      {
        scientificName: 'Dipodomys ordii',
        commonName: "Ord's kangaroo rat",
        taxonId: 10020,
      },
      {
        scientificName: 'Vicugna pacos',
        commonName: 'Alpaca',
        taxonId: 30538,
      },
      {
        scientificName: 'Callorhinus ursinus',
        commonName: 'Northern fur seal',
        taxonId: 34884,
      },
      {
        scientificName: 'Zalophus californianus',
        commonName: 'California sealion',
        taxonId: 9704,
      },
      {
        scientificName: 'Cebus imitator',
        commonName: 'Panamanian white-faced capuchin',
        taxonId: 2715852,
      },
    ],
    goTerms: [
      { goId: 'GO:0008201', aspect: 'GO Molecular Function' },
      { goId: 'GO:0005798', aspect: 'GO Cellular Component' },
      { goId: 'GO:0016021', aspect: 'GO Cellular Component' },
      { goId: 'GO:0007219', aspect: 'GO Biological Process' },
      { goId: 'GO:0007399', aspect: 'GO Biological Process' },
      { goId: 'GO:0006897', aspect: 'GO Biological Process' },
    ],
  },
  {
    id: 'UniRef100_P05067-2',
    name: 'Cluster: Isoform APP305 of Amyloid-beta precursor protein',
    updated: '2019-01-16',
    entryType: 'UniRef100',
    commonTaxon: { scientificName: 'Homo sapiens', taxonId: 9606 },
    memberCount: 1,
    organismCount: 1,
    representativeMember: {
      memberIdType: 'UniProtKB ID',
      memberId: 'P05067-2',
      organismName: 'Homo sapiens (Human)',
      organismTaxId: 9606,
      sequenceLength: 305,
      proteinName: 'Isoform APP305 of Amyloid-beta precursor protein',
      accessions: ['P05067-2'],
      uniref50Id: 'UniRef50_P05067-2',
      uniref90Id: 'UniRef90_P05067-2',
      uniparcId: { value: 'UPI000002A2F0' },
      seed: true,
      sequence: {
        value:
          'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVREKWYKEVHSGQARWLML',
        length: 305,
        molWeight: 34358,
        crc64: 'D1CCD7237262687A',
        md5: '8048490F3431C1D74DA373E90A7D8D5B',
      },
    },
    seedId: 'P05067-2',
    memberIdTypes: ['UniProtKB Reviewed (Swiss-Prot)'],
    members: ['P05067-2'],
    organisms: [
      { scientificName: 'Homo sapiens', commonName: 'Human', taxonId: 9606 },
    ],
  },
  {
    id: 'UniRef100_P05067-11',
    name: 'Cluster: Isoform 11 of Amyloid-beta precursor protein',
    updated: '2019-01-16',
    entryType: 'UniRef100',
    commonTaxon: { scientificName: 'Homo sapiens', taxonId: 9606 },
    memberCount: 1,
    organismCount: 1,
    representativeMember: {
      memberIdType: 'UniProtKB ID',
      memberId: 'P05067-11',
      organismName: 'Homo sapiens (Human)',
      organismTaxId: 9606,
      sequenceLength: 746,
      proteinName: 'Isoform 11 of Amyloid-beta precursor protein',
      accessions: ['P05067-11'],
      uniref50Id: 'UniRef50_P05067',
      uniref90Id: 'UniRef90_P05067-8',
      uniparcId: { value: 'UPI00017A7091' },
      seed: true,
      sequence: {
        value:
          'MDQLEDLLVLFINYVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVREVCSEQAETGPCRAMISRWYFDVTEGKCAPFFYGGCGGNRNNFDTEEYCMAVCGSAIPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEVEPVDARPAADRGLTTRPGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
        length: 746,
        molWeight: 84521,
        crc64: '843411EFBDEFACE3',
        md5: '04E00C8307ADE0838671AB52F9423932',
      },
    },
    seedId: 'P05067-11',
    memberIdTypes: ['UniProtKB Reviewed (Swiss-Prot)'],
    members: ['P05067-11'],
    organisms: [
      { scientificName: 'Homo sapiens', commonName: 'Human', taxonId: 9606 },
    ],
  },
  {
    id: 'UniRef90_P05067-2',
    name: 'Cluster: Isoform APP305 of Amyloid-beta precursor protein',
    updated: '2021-04-07',
    entryType: 'UniRef90',
    commonTaxon: { scientificName: 'Homo sapiens', taxonId: 9606 },
    memberCount: 1,
    organismCount: 1,
    representativeMember: {
      memberIdType: 'UniProtKB ID',
      memberId: 'P05067-2',
      organismName: 'Homo sapiens (Human)',
      organismTaxId: 9606,
      sequenceLength: 305,
      proteinName: 'Isoform APP305 of Amyloid-beta precursor protein',
      accessions: ['P05067-2'],
      uniref50Id: 'UniRef50_P05067-2',
      uniref100Id: 'UniRef100_P05067-2',
      uniparcId: { value: 'UPI000002A2F0' },
      seed: true,
      sequence: {
        value:
          'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVREKWYKEVHSGQARWLML',
        length: 305,
        molWeight: 34358,
        crc64: 'D1CCD7237262687A',
        md5: '8048490F3431C1D74DA373E90A7D8D5B',
      },
    },
    seedId: 'P05067-2',
    memberIdTypes: ['UniProtKB Reviewed (Swiss-Prot)'],
    members: ['P05067-2'],
    organisms: [
      { scientificName: 'Homo sapiens', commonName: 'Human', taxonId: 9606 },
    ],
  },
  {
    id: 'UniRef100_P05067-3',
    name: 'Cluster: Isoform L-APP677 of Amyloid-beta precursor protein',
    updated: '2019-12-18',
    entryType: 'UniRef100',
    commonTaxon: { scientificName: 'Homo sapiens', taxonId: 9606 },
    memberCount: 1,
    organismCount: 1,
    representativeMember: {
      memberIdType: 'UniProtKB ID',
      memberId: 'P05067-3',
      organismName: 'Homo sapiens (Human)',
      organismTaxId: 9606,
      sequenceLength: 677,
      proteinName: 'Isoform L-APP677 of Amyloid-beta precursor protein',
      accessions: ['P05067-3'],
      uniref50Id: 'UniRef50_P05067-5',
      uniref90Id: 'UniRef90_P05067-5',
      uniparcId: { value: 'UPI000002A2F1' },
      seed: true,
      sequence: {
        value:
          'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVRVPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
        length: 677,
        molWeight: 76760,
        crc64: '48334D3EEF26990E',
        md5: 'A338CD5CABF782539F4A55421B23A595',
      },
    },
    seedId: 'P05067-3',
    memberIdTypes: ['UniProtKB Reviewed (Swiss-Prot)'],
    members: ['P05067-3'],
    organisms: [
      { scientificName: 'Homo sapiens', commonName: 'Human', taxonId: 9606 },
    ],
  },
  {
    id: 'UniRef50_P05067-2',
    name: 'Cluster: Isoform APP305 of Amyloid-beta precursor protein',
    updated: '2021-04-07',
    entryType: 'UniRef50',
    commonTaxon: { scientificName: 'Homo sapiens', taxonId: 9606 },
    memberCount: 1,
    organismCount: 1,
    representativeMember: {
      memberIdType: 'UniProtKB ID',
      memberId: 'P05067-2',
      organismName: 'Homo sapiens (Human)',
      organismTaxId: 9606,
      sequenceLength: 305,
      proteinName: 'Isoform APP305 of Amyloid-beta precursor protein',
      accessions: ['P05067-2'],
      uniref90Id: 'UniRef90_P05067-2',
      uniref100Id: 'UniRef100_P05067-2',
      uniparcId: { value: 'UPI000002A2F0' },
      seed: true,
      sequence: {
        value:
          'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVREKWYKEVHSGQARWLML',
        length: 305,
        molWeight: 34358,
        crc64: 'D1CCD7237262687A',
        md5: '8048490F3431C1D74DA373E90A7D8D5B',
      },
    },
    seedId: 'P05067-2',
    memberIdTypes: ['UniProtKB Reviewed (Swiss-Prot)'],
    members: ['P05067-2'],
    organisms: [
      { scientificName: 'Homo sapiens', commonName: 'Human', taxonId: 9606 },
    ],
  },
  {
    id: 'UniRef100_P05067-10',
    name: 'Cluster: Isoform APP639 of Amyloid-beta precursor protein',
    updated: '2021-04-07',
    entryType: 'UniRef100',
    commonTaxon: { scientificName: 'Hominidae', taxonId: 9604 },
    memberCount: 3,
    organismCount: 3,
    representativeMember: {
      memberIdType: 'UniProtKB ID',
      memberId: 'P05067-10',
      organismName: 'Homo sapiens (Human)',
      organismTaxId: 9606,
      sequenceLength: 639,
      proteinName: 'Isoform APP639 of Amyloid-beta precursor protein',
      accessions: ['P05067-10'],
      uniref50Id: 'UniRef50_P05067-10',
      uniref90Id: 'UniRef90_P05067-10',
      uniparcId: { value: 'UPI00001BE539' },
      sequence: {
        value:
          'MLPGLALLLLAAWTARALEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVRVPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEVEPVDARPAADRGLTTRPGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
        length: 639,
        molWeight: 72553,
        crc64: 'C4120DEC51A59A95',
        md5: 'D04CDFB0E2E908743E7E53F43CA6D9F7',
      },
    },
    seedId: 'A0A2J8UKK4',
    memberIdTypes: [
      'UniProtKB Reviewed (Swiss-Prot)',
      'UniProtKB Unreviewed (TrEMBL)',
    ],
    members: ['P05067-10', 'A0A2J8UKK4', 'A0A2J8MQ67'],
    organisms: [
      { scientificName: 'Homo sapiens', commonName: 'Human', taxonId: 9606 },
      {
        scientificName: 'Pongo abelii',
        commonName: 'Sumatran orangutan',
        taxonId: 9601,
      },
      {
        scientificName: 'Pan troglodytes',
        commonName: 'Chimpanzee',
        taxonId: 9598,
      },
    ],
  },
  {
    id: 'UniRef100_P05067-4',
    name: 'Cluster: Isoform APP695 of Amyloid-beta precursor protein',
    updated: '2021-04-07',
    entryType: 'UniRef100',
    commonTaxon: { scientificName: 'Catarrhini', taxonId: 9526 },
    memberCount: 17,
    organismCount: 12,
    representativeMember: {
      memberIdType: 'UniProtKB ID',
      memberId: 'P05067-4',
      organismName: 'Homo sapiens (Human)',
      organismTaxId: 9606,
      sequenceLength: 695,
      proteinName: 'Isoform APP695 of Amyloid-beta precursor protein',
      accessions: ['P05067-4'],
      uniref50Id: 'UniRef50_P05067',
      uniref90Id: 'UniRef90_P05067-4',
      uniparcId: { value: 'UPI000002A2F2' },
      sequence: {
        value:
          'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVRVPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEVEPVDARPAADRGLTTRPGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
        length: 695,
        molWeight: 78663,
        crc64: '4F6EA0139F969D56',
        md5: 'BD089074F6C0866F6A1081DF3FBEB648',
      },
    },
    seedId: 'I0FGN2',
    memberIdTypes: [
      'UniProtKB Reviewed (Swiss-Prot)',
      'UniProtKB Unreviewed (TrEMBL)',
    ],
    members: [
      'P05067-4',
      'I0FGN2',
      'A0A2K6QWS0',
      'A0A2J8UKM8',
      'A0A2I3SHN1',
      'A0A6D2X899',
      'A0A2K5NR37',
      'A0A2I3MTM7',
      'A0A2R8ZFN4',
      'A0A2K5U6B3',
    ],
    organisms: [
      { scientificName: 'Homo sapiens', commonName: 'Human', taxonId: 9606 },
      {
        scientificName: 'Macaca mulatta',
        commonName: 'Rhesus macaque',
        taxonId: 9544,
      },
      {
        scientificName: 'Rhinopithecus roxellana',
        commonName: 'Golden snub-nosed monkey',
        taxonId: 61622,
      },
      {
        scientificName: 'Pongo abelii',
        commonName: 'Sumatran orangutan',
        taxonId: 9601,
      },
      {
        scientificName: 'Pan troglodytes',
        commonName: 'Chimpanzee',
        taxonId: 9598,
      },
      {
        scientificName: 'Cercocebus atys',
        commonName: 'Sooty mangabey',
        taxonId: 9531,
      },
      {
        scientificName: 'Papio anubis',
        commonName: 'Olive baboon',
        taxonId: 9555,
      },
      {
        scientificName: 'Pan paniscus',
        commonName: 'Pygmy chimpanzee',
        taxonId: 9597,
      },
      {
        scientificName: 'Macaca fascicularis',
        commonName: 'Crab-eating macaque',
        taxonId: 9541,
      },
      {
        scientificName: 'Rhinopithecus bieti',
        commonName: 'Black snub-nosed monkey',
        taxonId: 61621,
      },
    ],
  },
  {
    id: 'UniRef50_P05067-10',
    name: 'Cluster: Isoform APP639 of Amyloid-beta precursor protein',
    updated: '2021-04-07',
    entryType: 'UniRef50',
    commonTaxon: { scientificName: 'Gnathostomata', taxonId: 7776 },
    memberCount: 238,
    organismCount: 119,
    representativeMember: {
      memberIdType: 'UniProtKB ID',
      memberId: 'P05067-10',
      organismName: 'Homo sapiens (Human)',
      organismTaxId: 9606,
      sequenceLength: 639,
      proteinName: 'Isoform APP639 of Amyloid-beta precursor protein',
      accessions: ['P05067-10'],
      uniref90Id: 'UniRef90_P05067-10',
      uniref100Id: 'UniRef100_P05067-10',
      uniparcId: { value: 'UPI00001BE539' },
      sequence: {
        value:
          'MLPGLALLLLAAWTARALEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVRVPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEVEPVDARPAADRGLTTRPGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
        length: 639,
        molWeight: 72553,
        crc64: 'C4120DEC51A59A95',
        md5: 'D04CDFB0E2E908743E7E53F43CA6D9F7',
      },
    },
    seedId: 'A0A669F576',
    memberIdTypes: [
      'UniProtKB Reviewed (Swiss-Prot)',
      'UniProtKB Unreviewed (TrEMBL)',
      'UniParc',
    ],
    members: [
      'P05067-10',
      'A0A2J8UKK4',
      'A0A2J8MQ67',
      'A0A2I3SP96',
      'A0A4W2DEQ7',
      'A0A6I9KGJ2',
      'A0A7J8A478',
      'A0A2U3WVA0',
      'A0A2I3G872',
      'A0A340Y268',
    ],
    organisms: [
      { scientificName: 'Homo sapiens', commonName: 'Human', taxonId: 9606 },
      {
        scientificName: 'Pongo abelii',
        commonName: 'Sumatran orangutan',
        taxonId: 9601,
      },
      {
        scientificName: 'Pan troglodytes',
        commonName: 'Chimpanzee',
        taxonId: 9598,
      },
      {
        scientificName: 'Bos indicus x Bos taurus',
        commonName: 'Hybrid cattle',
        taxonId: 30522,
      },
      {
        scientificName: 'Chrysochloris asiatica',
        commonName: 'Cape golden mole',
        taxonId: 185453,
      },
      {
        scientificName: 'Pipistrellus kuhlii',
        commonName: "Kuhl's pipistrelle",
        taxonId: 59472,
      },
      {
        scientificName: 'Odobenus rosmarus divergens',
        commonName: 'Pacific walrus',
        taxonId: 9708,
      },
      {
        scientificName: 'Nomascus leucogenys',
        commonName: 'Northern white-cheeked gibbon',
        taxonId: 61853,
      },
      {
        scientificName: 'Lipotes vexillifer',
        commonName: 'Yangtze river dolphin',
        taxonId: 118797,
      },
      {
        scientificName: 'Erinaceus europaeus',
        commonName: 'Western European hedgehog',
        taxonId: 9365,
      },
    ],
    goTerms: [
      { goId: 'GO:0008201', aspect: 'GO Molecular Function' },
      { goId: 'GO:0046914', aspect: 'GO Molecular Function' },
      { goId: 'GO:0005798', aspect: 'GO Cellular Component' },
      { goId: 'GO:0016021', aspect: 'GO Cellular Component' },
      { goId: 'GO:0048856', aspect: 'GO Biological Process' },
    ],
  },
  {
    id: 'UniRef90_P05067-10',
    name: 'Cluster: Isoform APP639 of Amyloid-beta precursor protein',
    updated: '2021-04-07',
    entryType: 'UniRef90',
    commonTaxon: { scientificName: 'Amniota', taxonId: 32524 },
    memberCount: 24,
    organismCount: 23,
    representativeMember: {
      memberIdType: 'UniProtKB ID',
      memberId: 'P05067-10',
      organismName: 'Homo sapiens (Human)',
      organismTaxId: 9606,
      sequenceLength: 639,
      proteinName: 'Isoform APP639 of Amyloid-beta precursor protein',
      accessions: ['P05067-10'],
      uniref50Id: 'UniRef50_P05067-10',
      uniref100Id: 'UniRef100_P05067-10',
      uniparcId: { value: 'UPI00001BE539' },
      sequence: {
        value:
          'MLPGLALLLLAAWTARALEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVRVPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEVEPVDARPAADRGLTTRPGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
        length: 639,
        molWeight: 72553,
        crc64: 'C4120DEC51A59A95',
        md5: 'D04CDFB0E2E908743E7E53F43CA6D9F7',
      },
    },
    seedId: 'UPI0006D7458C',
    memberIdTypes: [
      'UniProtKB Reviewed (Swiss-Prot)',
      'UniProtKB Unreviewed (TrEMBL)',
      'UniParc',
    ],
    members: [
      'P05067-10',
      'A0A2J8UKK4',
      'A0A2J8MQ67',
      'A0A2I3SP96',
      'A0A6I9KGJ2',
      'A0A4W2DEQ7',
      'A0A7J8A478',
      'A0A2U3WVA0',
      'A0A2I3G872',
      'A0A340Y268',
    ],
    organisms: [
      { scientificName: 'Homo sapiens', commonName: 'Human', taxonId: 9606 },
      {
        scientificName: 'Pongo abelii',
        commonName: 'Sumatran orangutan',
        taxonId: 9601,
      },
      {
        scientificName: 'Pan troglodytes',
        commonName: 'Chimpanzee',
        taxonId: 9598,
      },
      {
        scientificName: 'Chrysochloris asiatica',
        commonName: 'Cape golden mole',
        taxonId: 185453,
      },
      {
        scientificName: 'Bos indicus x Bos taurus',
        commonName: 'Hybrid cattle',
        taxonId: 30522,
      },
      {
        scientificName: 'Pipistrellus kuhlii',
        commonName: "Kuhl's pipistrelle",
        taxonId: 59472,
      },
      {
        scientificName: 'Odobenus rosmarus divergens',
        commonName: 'Pacific walrus',
        taxonId: 9708,
      },
      {
        scientificName: 'Nomascus leucogenys',
        commonName: 'Northern white-cheeked gibbon',
        taxonId: 61853,
      },
      {
        scientificName: 'Lipotes vexillifer',
        commonName: 'Yangtze river dolphin',
        taxonId: 118797,
      },
      {
        scientificName: 'Erinaceus europaeus',
        commonName: 'Western European hedgehog',
        taxonId: 9365,
      },
    ],
    goTerms: [
      { goId: 'GO:0004867', aspect: 'GO Molecular Function' },
      { goId: 'GO:0008201', aspect: 'GO Molecular Function' },
      { goId: 'GO:0046914', aspect: 'GO Molecular Function' },
      { goId: 'GO:0005905', aspect: 'GO Cellular Component' },
      { goId: 'GO:0005798', aspect: 'GO Cellular Component' },
      { goId: 'GO:0043204', aspect: 'GO Cellular Component' },
      { goId: 'GO:0030426', aspect: 'GO Cellular Component' },
      { goId: 'GO:0016021', aspect: 'GO Cellular Component' },
      { goId: 'GO:0005769', aspect: 'GO Cellular Component' },
      { goId: 'GO:0007399', aspect: 'GO Biological Process' },
      { goId: 'GO:0006897', aspect: 'GO Biological Process' },
    ],
  },
  {
    id: 'UniRef100_P05067-8',
    name: 'Cluster: Isoform APP751 of Amyloid-beta precursor protein',
    updated: '2019-01-16',
    entryType: 'UniRef100',
    commonTaxon: { scientificName: 'Homo sapiens', taxonId: 9606 },
    memberCount: 2,
    organismCount: 1,
    representativeMember: {
      memberIdType: 'UniProtKB ID',
      memberId: 'P05067-8',
      organismName: 'Homo sapiens (Human)',
      organismTaxId: 9606,
      sequenceLength: 751,
      proteinName: 'Isoform APP751 of Amyloid-beta precursor protein',
      accessions: ['P05067-8'],
      uniref50Id: 'UniRef50_P05067',
      uniref90Id: 'UniRef90_P05067-8',
      uniparcId: { value: 'UPI000002A2F6' },
      seed: true,
      sequence: {
        value:
          'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVREVCSEQAETGPCRAMISRWYFDVTEGKCAPFFYGGCGGNRNNFDTEEYCMAVCGSAIPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEVEPVDARPAADRGLTTRPGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
        length: 751,
        molWeight: 84819,
        crc64: 'C987C557C5A3714E',
        md5: 'A83D724FA6C8F6A50993DB360949D528',
      },
    },
    seedId: 'P05067-8',
    memberIdTypes: ['UniProtKB Reviewed (Swiss-Prot)', 'UniParc'],
    members: ['P05067-8', 'UPI000002DA86'],
    organisms: [
      { scientificName: 'Homo sapiens', commonName: 'Human', taxonId: 9606 },
    ],
  },
  {
    id: 'UniRef100_P05067-9',
    name: 'Cluster: Isoform L-APP752 of Amyloid-beta precursor protein',
    updated: '2019-01-16',
    entryType: 'UniRef100',
    commonTaxon: { scientificName: 'Homo sapiens', taxonId: 9606 },
    memberCount: 1,
    organismCount: 1,
    representativeMember: {
      memberIdType: 'UniProtKB ID',
      memberId: 'P05067-9',
      organismName: 'Homo sapiens (Human)',
      organismTaxId: 9606,
      sequenceLength: 752,
      proteinName: 'Isoform L-APP752 of Amyloid-beta precursor protein',
      accessions: ['P05067-9'],
      uniref50Id: 'UniRef50_P05067',
      uniref90Id: 'UniRef90_P05067-9',
      uniparcId: { value: 'UPI000002A2F7' },
      seed: true,
      sequence: {
        value:
          'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVREVCSEQAETGPCRAMISRWYFDVTEGKCAPFFYGGCGGNRNNFDTEEYCMAVCGSAMSQSLLKTTQEPLARDPVKLPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
        length: 752,
        molWeight: 85040,
        crc64: '074CFF767CBED2E0',
        md5: '7D77A2EC2E85AF64D225E470989571D2',
      },
    },
    seedId: 'P05067-9',
    memberIdTypes: ['UniProtKB Reviewed (Swiss-Prot)'],
    members: ['P05067-9'],
    organisms: [
      { scientificName: 'Homo sapiens', commonName: 'Human', taxonId: 9606 },
    ],
  },
  {
    id: 'UniRef100_P05067-6',
    name: 'Cluster: Isoform APP714 of Amyloid-beta precursor protein',
    updated: '2021-04-07',
    entryType: 'UniRef100',
    commonTaxon: { scientificName: 'Hominidae', taxonId: 9604 },
    memberCount: 3,
    organismCount: 3,
    representativeMember: {
      memberIdType: 'UniProtKB ID',
      memberId: 'P05067-6',
      organismName: 'Homo sapiens (Human)',
      organismTaxId: 9606,
      sequenceLength: 714,
      proteinName: 'Isoform APP714 of Amyloid-beta precursor protein',
      accessions: ['P05067-6'],
      uniref50Id: 'UniRef50_P05067',
      uniref90Id: 'UniRef90_P05067-6',
      uniparcId: { value: 'UPI000002A2F4' },
      seed: true,
      sequence: {
        value:
          'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVRVSQSLLKTTQEPLARDPVKLPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEVEPVDARPAADRGLTTRPGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
        length: 714,
        molWeight: 80769,
        crc64: '124EA691773DC13B',
        md5: '8CA2189A8D89EC9502051E9DBDA6AF9D',
      },
    },
    seedId: 'P05067-6',
    memberIdTypes: [
      'UniProtKB Reviewed (Swiss-Prot)',
      'UniProtKB Unreviewed (TrEMBL)',
    ],
    members: ['P05067-6', 'A0A2J8UKJ9', 'A0A2J8MQ83'],
    organisms: [
      { scientificName: 'Homo sapiens', commonName: 'Human', taxonId: 9606 },
      {
        scientificName: 'Pongo abelii',
        commonName: 'Sumatran orangutan',
        taxonId: 9601,
      },
      {
        scientificName: 'Pan troglodytes',
        commonName: 'Chimpanzee',
        taxonId: 9598,
      },
    ],
  },
  {
    id: 'UniRef90_P05067-6',
    name: 'Cluster: Isoform APP714 of Amyloid-beta precursor protein',
    updated: '2021-04-07',
    entryType: 'UniRef90',
    commonTaxon: { scientificName: 'Boreoeutheria', taxonId: 1437010 },
    memberCount: 23,
    organismCount: 21,
    representativeMember: {
      memberIdType: 'UniProtKB ID',
      memberId: 'P05067-6',
      organismName: 'Homo sapiens (Human)',
      organismTaxId: 9606,
      sequenceLength: 714,
      proteinName: 'Isoform APP714 of Amyloid-beta precursor protein',
      accessions: ['P05067-6'],
      uniref50Id: 'UniRef50_P05067',
      uniref100Id: 'UniRef100_P05067-6',
      uniparcId: { value: 'UPI000002A2F4' },
      sequence: {
        value:
          'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVRVSQSLLKTTQEPLARDPVKLPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEVEPVDARPAADRGLTTRPGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
        length: 714,
        molWeight: 80769,
        crc64: '124EA691773DC13B',
        md5: '8CA2189A8D89EC9502051E9DBDA6AF9D',
      },
    },
    seedId: 'UPI001386BA67',
    memberIdTypes: [
      'UniProtKB Reviewed (Swiss-Prot)',
      'UniProtKB Unreviewed (TrEMBL)',
      'UniParc',
    ],
    members: [
      'P05067-6',
      'A0A2J8UKJ9',
      'A0A2J8MQ83',
      'A0A287AJD6',
      'A0A4X1UDV2',
      'A0A2U3WV95',
      'F1P615',
      'A0A2Y9K0M0',
      'A0A6J2C5P7',
      'A0A5K1UK61',
    ],
    organisms: [
      { scientificName: 'Homo sapiens', commonName: 'Human', taxonId: 9606 },
      {
        scientificName: 'Pongo abelii',
        commonName: 'Sumatran orangutan',
        taxonId: 9601,
      },
      {
        scientificName: 'Pan troglodytes',
        commonName: 'Chimpanzee',
        taxonId: 9598,
      },
      { scientificName: 'Sus scrofa', commonName: 'Pig', taxonId: 9823 },
      {
        scientificName: 'Odobenus rosmarus divergens',
        commonName: 'Pacific walrus',
        taxonId: 9708,
      },
      {
        scientificName: 'Canis lupus familiaris',
        commonName: 'Dog',
        taxonId: 9615,
      },
      { scientificName: 'Enhydra lutris kenyoni', taxonId: 391180 },
      {
        scientificName: 'Zalophus californianus',
        commonName: 'California sealion',
        taxonId: 9704,
      },
      {
        scientificName: 'Callithrix jacchus',
        commonName: 'White-tufted-ear marmoset',
        taxonId: 9483,
      },
      {
        scientificName: 'Oryctolagus cuniculus',
        commonName: 'Rabbit',
        taxonId: 9986,
      },
    ],
    goTerms: [
      { goId: 'GO:0008201', aspect: 'GO Molecular Function' },
      { goId: 'GO:0005905', aspect: 'GO Cellular Component' },
      { goId: 'GO:0005798', aspect: 'GO Cellular Component' },
      { goId: 'GO:0043204', aspect: 'GO Cellular Component' },
      { goId: 'GO:0030426', aspect: 'GO Cellular Component' },
      { goId: 'GO:0016021', aspect: 'GO Cellular Component' },
      { goId: 'GO:0005769', aspect: 'GO Cellular Component' },
      { goId: 'GO:0007399', aspect: 'GO Biological Process' },
    ],
  },
  {
    id: 'UniRef100_P05067-5',
    name: 'Cluster: Isoform L-APP696 of Amyloid-beta precursor protein',
    updated: '2019-01-16',
    entryType: 'UniRef100',
    commonTaxon: { scientificName: 'Homo sapiens', taxonId: 9606 },
    memberCount: 1,
    organismCount: 1,
    representativeMember: {
      memberIdType: 'UniProtKB ID',
      memberId: 'P05067-5',
      organismName: 'Homo sapiens (Human)',
      organismTaxId: 9606,
      sequenceLength: 696,
      proteinName: 'Isoform L-APP696 of Amyloid-beta precursor protein',
      accessions: ['P05067-5'],
      uniref50Id: 'UniRef50_P05067-5',
      uniref90Id: 'UniRef90_P05067-5',
      uniparcId: { value: 'UPI000002A2F3' },
      seed: true,
      sequence: {
        value:
          'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVRVSQSLLKTTQEPLARDPVKLPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
        length: 696,
        molWeight: 78866,
        crc64: '66DFDFFCFDB75A72',
        md5: '94203A08AE85B6BB240F0941282243D6',
      },
    },
    seedId: 'P05067-5',
    memberIdTypes: ['UniProtKB Reviewed (Swiss-Prot)'],
    members: ['P05067-5'],
    organisms: [
      { scientificName: 'Homo sapiens', commonName: 'Human', taxonId: 9606 },
    ],
  },
  {
    id: 'UniRef100_P05067-7',
    name: 'Cluster: Isoform L-APP733 of Amyloid-beta precursor protein',
    updated: '2019-01-16',
    entryType: 'UniRef100',
    commonTaxon: { scientificName: 'Homo sapiens', taxonId: 9606 },
    memberCount: 1,
    organismCount: 1,
    representativeMember: {
      memberIdType: 'UniProtKB ID',
      memberId: 'P05067-7',
      organismName: 'Homo sapiens (Human)',
      organismTaxId: 9606,
      sequenceLength: 733,
      proteinName: 'Isoform L-APP733 of Amyloid-beta precursor protein',
      accessions: ['P05067-7'],
      uniref50Id: 'UniRef50_P05067',
      uniref90Id: 'UniRef90_P05067-8',
      uniparcId: { value: 'UPI000002A2F5' },
      seed: true,
      sequence: {
        value:
          'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVREVCSEQAETGPCRAMISRWYFDVTEGKCAPFFYGGCGGNRNNFDTEEYCMAVCGSAIPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
        length: 733,
        molWeight: 82916,
        crc64: '44528239D68A53EE',
        md5: '93307E53EAA95B82664CC2BC9165B156',
      },
    },
    seedId: 'P05067-7',
    memberIdTypes: ['UniProtKB Reviewed (Swiss-Prot)'],
    members: ['P05067-7'],
    organisms: [
      { scientificName: 'Homo sapiens', commonName: 'Human', taxonId: 9606 },
    ],
  },
  {
    id: 'UniRef100_P05067',
    name: 'Cluster: Amyloid-beta precursor protein',
    updated: '2021-04-07',
    entryType: 'UniRef100',
    commonTaxon: { scientificName: 'Catarrhini', taxonId: 9526 },
    memberCount: 4,
    organismCount: 2,
    representativeMember: {
      memberIdType: 'UniProtKB ID',
      memberId: 'A4_HUMAN',
      organismName: 'Homo sapiens (Human)',
      organismTaxId: 9606,
      sequenceLength: 770,
      proteinName: 'Amyloid-beta precursor protein',
      accessions: [
        'P05067',
        'B2R5V1',
        'B4DII8',
        'D3DSD1',
        'D3DSD2',
        'D3DSD3',
        'P09000',
        'P78438',
        'Q13764',
        'Q13778',
        'Q13793',
        'Q16011',
        'Q16014',
        'Q16019',
        'Q16020',
        'Q6GSC0',
        'Q8WZ99',
        'Q9BT38',
        'Q9UC33',
        'Q9UCA9',
        'Q9UCB6',
        'Q9UCC8',
        'Q9UCD1',
        'Q9UQ58',
      ],
      uniref50Id: 'UniRef50_P05067',
      uniref90Id: 'UniRef90_P05067',
      uniparcId: { value: 'UPI000002DB1C' },
      seed: true,
      sequence: {
        value:
          'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVREVCSEQAETGPCRAMISRWYFDVTEGKCAPFFYGGCGGNRNNFDTEEYCMAVCGSAMSQSLLKTTQEPLARDPVKLPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEVEPVDARPAADRGLTTRPGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
        length: 770,
        molWeight: 86943,
        crc64: 'A12EE761403740F5',
        md5: '7DD43312CD29A262ACDC0517230BC5CA',
      },
    },
    seedId: 'P05067',
    memberIdTypes: [
      'UniProtKB Reviewed (Swiss-Prot)',
      'UniProtKB Unreviewed (TrEMBL)',
      'UniParc',
    ],
    members: ['P05067', 'A0A140VJC8', 'O97584', 'UPI0000110448'],
    organisms: [
      { scientificName: 'Homo sapiens', commonName: 'Human', taxonId: 9606 },
      {
        scientificName: 'Macaca mulatta',
        commonName: 'Rhesus macaque',
        taxonId: 9544,
      },
    ],
  },
  {
    id: 'UniRef90_P05067',
    name: 'Cluster: Amyloid-beta precursor protein',
    updated: '2021-04-07',
    entryType: 'UniRef90',
    commonTaxon: { scientificName: 'cellular organisms', taxonId: 131567 },
    memberCount: 466,
    organismCount: 357,
    representativeMember: {
      memberIdType: 'UniProtKB ID',
      memberId: 'A4_HUMAN',
      organismName: 'Homo sapiens (Human)',
      organismTaxId: 9606,
      sequenceLength: 770,
      proteinName: 'Amyloid-beta precursor protein',
      accessions: [
        'P05067',
        'B2R5V1',
        'B4DII8',
        'D3DSD1',
        'D3DSD2',
        'D3DSD3',
        'P09000',
        'P78438',
        'Q13764',
        'Q13778',
        'Q13793',
        'Q16011',
        'Q16014',
        'Q16019',
        'Q16020',
        'Q6GSC0',
        'Q8WZ99',
        'Q9BT38',
        'Q9UC33',
        'Q9UCA9',
        'Q9UCB6',
        'Q9UCC8',
        'Q9UCD1',
        'Q9UQ58',
      ],
      uniref50Id: 'UniRef50_P05067',
      uniref100Id: 'UniRef100_P05067',
      uniparcId: { value: 'UPI000002DB1C' },
      sequence: {
        value:
          'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVREVCSEQAETGPCRAMISRWYFDVTEGKCAPFFYGGCGGNRNNFDTEEYCMAVCGSAMSQSLLKTTQEPLARDPVKLPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEVEPVDARPAADRGLTTRPGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
        length: 770,
        molWeight: 86943,
        crc64: 'A12EE761403740F5',
        md5: '7DD43312CD29A262ACDC0517230BC5CA',
      },
    },
    seedId: 'UPI001386A8D7',
    memberIdTypes: [
      'UniProtKB Reviewed (Swiss-Prot)',
      'UniProtKB Unreviewed (TrEMBL)',
      'UniParc',
    ],
    members: [
      'P05067',
      'P08592',
      'Q5IS80',
      'P79307',
      'P12023',
      'Q28053',
      'Q28748',
      'Q28757',
      'Q28280',
      'Q29149',
    ],
    organisms: [
      { scientificName: 'Homo sapiens', commonName: 'Human', taxonId: 9606 },
      {
        scientificName: 'Rattus norvegicus',
        commonName: 'Rat',
        taxonId: 10116,
      },
      {
        scientificName: 'Pan troglodytes',
        commonName: 'Chimpanzee',
        taxonId: 9598,
      },
      { scientificName: 'Sus scrofa', commonName: 'Pig', taxonId: 9823 },
      { scientificName: 'Mus musculus', commonName: 'Mouse', taxonId: 10090 },
      { scientificName: 'Bos taurus', commonName: 'Bovine', taxonId: 9913 },
      {
        scientificName: 'Oryctolagus cuniculus',
        commonName: 'Rabbit',
        taxonId: 9986,
      },
      { scientificName: 'Ovis aries', commonName: 'Sheep', taxonId: 9940 },
      {
        scientificName: 'Canis lupus familiaris',
        commonName: 'Dog',
        taxonId: 9615,
      },
      {
        scientificName: 'Ursus maritimus',
        commonName: 'Polar bear',
        taxonId: 29073,
      },
    ],
  },
];

export default mock;
