import { UniRefLiteAPIModel } from '../../../../../uniref/adapters/uniRefConverter';

const mock: { results: UniRefLiteAPIModel[] } = {
  results: [
    {
      id: 'UniRef90_P05067-4',
      name: 'Cluster: Isoform APP695 of Amyloid-beta precursor protein',
      updated: '2022-01-19',
      entryType: 'UniRef90',
      commonTaxon: {
        scientificName: 'Amniota',
        taxonId: 32524,
      },
      memberCount: 197,
      organismCount: 170,
      representativeMember: {
        memberIdType: 'UniProtKB ID',
        memberId: 'P05067-4',
        organismName: 'Homo sapiens (Human)',
        organismTaxId: 9606,
        sequenceLength: 695,
        proteinName: 'Isoform APP695 of Amyloid-beta precursor protein',
        accessions: ['P05067-4'],
        uniref50Id: 'UniRef50_P05067',
        uniref100Id: 'UniRef100_P05067-4',
        uniparcId: 'UPI000002A2F2',
        sequence: {
          value:
            'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVRVPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEVEPVDARPAADRGLTTRPGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
          length: 695,
          molWeight: 78663,
          crc64: '4F6EA0139F969D56',
          md5: 'BD089074F6C0866F6A1081DF3FBEB648',
        },
      },
      seedId: 'UPI001386654F',
      memberIdTypes: [
        'UniProtKB Reviewed (Swiss-Prot)',
        'UniParc',
        'UniProtKB Unreviewed (TrEMBL)',
      ],
      members: [
        'P05067-4',
        'I0FGN2',
        'A0A2K6QWS0',
        'A0A2J8UKM8',
        'A0A2I3SHN1',
        'A0A6D2X899',
        'A0A2K5NR37',
        'A0A2I3MTM7',
        'A0A2R8ZFN4',
        'A0A2K5U6B3',
      ],
      organisms: [
        {
          scientificName: 'Homo sapiens',
          commonName: 'Human',
          taxonId: 9606,
        },
        {
          scientificName: 'Macaca mulatta',
          commonName: 'Rhesus macaque',
          taxonId: 9544,
        },
        {
          scientificName: 'Rhinopithecus roxellana',
          commonName: 'Golden snub-nosed monkey',
          taxonId: 61622,
        },
        {
          scientificName: 'Pongo abelii',
          commonName: 'Sumatran orangutan',
          taxonId: 9601,
        },
        {
          scientificName: 'Pan troglodytes',
          commonName: 'Chimpanzee',
          taxonId: 9598,
        },
        {
          scientificName: 'Cercocebus atys',
          commonName: 'Sooty mangabey',
          taxonId: 9531,
        },
        {
          scientificName: 'Papio anubis',
          commonName: 'Olive baboon',
          taxonId: 9555,
        },
        {
          scientificName: 'Pan paniscus',
          commonName: 'Pygmy chimpanzee',
          taxonId: 9597,
        },
        {
          scientificName: 'Macaca fascicularis',
          commonName: 'Crab-eating macaque',
          taxonId: 9541,
        },
        {
          scientificName: 'Rhinopithecus bieti',
          commonName: 'Black snub-nosed monkey',
          taxonId: 61621,
        },
      ],
      goTerms: [
        {
          goId: 'GO:0004867',
          aspect: 'GO Molecular Function',
        },
        {
          goId: 'GO:0008201',
          aspect: 'GO Molecular Function',
        },
        {
          goId: 'GO:0046914',
          aspect: 'GO Molecular Function',
        },
        {
          goId: 'GO:0005798',
          aspect: 'GO Cellular Component',
        },
        {
          goId: 'GO:0016021',
          aspect: 'GO Cellular Component',
        },
        {
          goId: 'GO:0048856',
          aspect: 'GO Biological Process',
        },
      ],
    },
    {
      id: 'UniRef50_P05067',
      name: 'Cluster: Amyloid-beta precursor protein',
      updated: '2022-01-19',
      entryType: 'UniRef50',
      commonTaxon: {
        scientificName: 'cellular organisms',
        taxonId: 131567,
      },
      memberCount: 2173,
      organismCount: 672,
      representativeMember: {
        memberIdType: 'UniProtKB ID',
        memberId: 'A4_HUMAN',
        organismName: 'Homo sapiens (Human)',
        organismTaxId: 9606,
        sequenceLength: 770,
        proteinName: 'Amyloid-beta precursor protein',
        accessions: [
          'P05067',
          'B2R5V1',
          'B4DII8',
          'D3DSD1',
          'D3DSD2',
          'D3DSD3',
          'P09000',
          'P78438',
          'Q13764',
          'Q13778',
          'Q13793',
          'Q16011',
          'Q16014',
          'Q16019',
          'Q16020',
          'Q6GSC0',
          'Q8WZ99',
          'Q9BT38',
          'Q9UC33',
          'Q9UCA9',
          'Q9UCB6',
          'Q9UCC8',
          'Q9UCD1',
          'Q9UQ58',
        ],
        uniref90Id: 'UniRef90_P05067',
        uniref100Id: 'UniRef100_P05067',
        uniparcId: 'UPI000002DB1C',
        sequence: {
          value:
            'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVREVCSEQAETGPCRAMISRWYFDVTEGKCAPFFYGGCGGNRNNFDTEEYCMAVCGSAMSQSLLKTTQEPLARDPVKLPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEVEPVDARPAADRGLTTRPGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
          length: 770,
          molWeight: 86943,
          crc64: 'A12EE761403740F5',
          md5: '7DD43312CD29A262ACDC0517230BC5CA',
        },
      },
      seedId: 'UPI001386A8D7',
      memberIdTypes: [
        'UniProtKB Reviewed (Swiss-Prot)',
        'UniParc',
        'UniProtKB Unreviewed (TrEMBL)',
      ],
      members: [
        'P05067',
        'P12023',
        'Q5IS80',
        'P53601',
        'P29216',
        'P08592',
        'Q60495',
        'P79307',
        'Q28053',
        'Q28280',
      ],
      organisms: [
        {
          scientificName: 'Homo sapiens',
          commonName: 'Human',
          taxonId: 9606,
        },
        {
          scientificName: 'Mus musculus',
          commonName: 'Mouse',
          taxonId: 10090,
        },
        {
          scientificName: 'Pan troglodytes',
          commonName: 'Chimpanzee',
          taxonId: 9598,
        },
        {
          scientificName: 'Macaca fascicularis',
          commonName: 'Crab-eating macaque',
          taxonId: 9541,
        },
        {
          scientificName: 'Macaca mulatta',
          commonName: 'Rhesus macaque',
          taxonId: 9544,
        },
        {
          scientificName: 'Rattus norvegicus',
          commonName: 'Rat',
          taxonId: 10116,
        },
        {
          scientificName: 'Cavia porcellus',
          commonName: 'Guinea pig',
          taxonId: 10141,
        },
        {
          scientificName: 'Sus scrofa',
          commonName: 'Pig',
          taxonId: 9823,
        },
        {
          scientificName: 'Bos taurus',
          commonName: 'Bovine',
          taxonId: 9913,
        },
        {
          scientificName: 'Canis lupus familiaris',
          commonName: 'Dog',
          taxonId: 9615,
        },
      ],
    },
    {
      id: 'UniRef100_P05067-4',
      name: 'Cluster: Isoform APP695 of Amyloid-beta precursor protein',
      updated: '2022-01-19',
      entryType: 'UniRef100',
      commonTaxon: {
        scientificName: 'Catarrhini',
        taxonId: 9526,
      },
      memberCount: 18,
      organismCount: 13,
      representativeMember: {
        memberIdType: 'UniProtKB ID',
        memberId: 'P05067-4',
        organismName: 'Homo sapiens (Human)',
        organismTaxId: 9606,
        sequenceLength: 695,
        proteinName: 'Isoform APP695 of Amyloid-beta precursor protein',
        accessions: ['P05067-4'],
        uniref50Id: 'UniRef50_P05067',
        uniref90Id: 'UniRef90_P05067-4',
        uniparcId: 'UPI000002A2F2',
        sequence: {
          value:
            'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVRVPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEVEPVDARPAADRGLTTRPGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
          length: 695,
          molWeight: 78663,
          crc64: '4F6EA0139F969D56',
          md5: 'BD089074F6C0866F6A1081DF3FBEB648',
        },
      },
      seedId: 'I0FGN2',
      memberIdTypes: [
        'UniProtKB Reviewed (Swiss-Prot)',
        'UniProtKB Unreviewed (TrEMBL)',
      ],
      members: [
        'P05067-4',
        'I0FGN2',
        'A0A2K6QWS0',
        'A0A2J8UKM8',
        'A0A2I3SHN1',
        'A0A6D2X899',
        'A0A2K5NR37',
        'A0A2I3MTM7',
        'A0A2R8ZFN4',
        'A0A2K5U6B3',
      ],
      organisms: [
        {
          scientificName: 'Homo sapiens',
          commonName: 'Human',
          taxonId: 9606,
        },
        {
          scientificName: 'Macaca mulatta',
          commonName: 'Rhesus macaque',
          taxonId: 9544,
        },
        {
          scientificName: 'Rhinopithecus roxellana',
          commonName: 'Golden snub-nosed monkey',
          taxonId: 61622,
        },
        {
          scientificName: 'Pongo abelii',
          commonName: 'Sumatran orangutan',
          taxonId: 9601,
        },
        {
          scientificName: 'Pan troglodytes',
          commonName: 'Chimpanzee',
          taxonId: 9598,
        },
        {
          scientificName: 'Cercocebus atys',
          commonName: 'Sooty mangabey',
          taxonId: 9531,
        },
        {
          scientificName: 'Papio anubis',
          commonName: 'Olive baboon',
          taxonId: 9555,
        },
        {
          scientificName: 'Pan paniscus',
          commonName: 'Pygmy chimpanzee',
          taxonId: 9597,
        },
        {
          scientificName: 'Macaca fascicularis',
          commonName: 'Crab-eating macaque',
          taxonId: 9541,
        },
        {
          scientificName: 'Rhinopithecus bieti',
          commonName: 'Black snub-nosed monkey',
          taxonId: 61621,
        },
      ],
    },
  ],
};
export default mock;
